<?php
namespace App\Http\Controllers;
use App\Services\{ConversationInbox,VoiceLab,WhatsAppQrTemplates};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class ConversationController extends Controller {
 private function workspace(Request $r,bool $manage=false):int{abort_unless($r->user()->voice_workspace_id===1,403);if($manage)abort_unless(in_array($r->user()->voice_role,['admin','supervisor'],true),403);return 1;}
 public function index(Request $r){
  $w=$this->workspace($r);$d=$r->validate(['status'=>'nullable|in:open,closed','sender_id'=>'nullable|integer|min:1','search'=>'nullable|string|max:80','page'=>'nullable|integer|min:1|max:10000']);$s=app(ConversationInbox::class);$visible=$s->visible($w,$r->user());$manage=in_array($r->user()->voice_role,['admin','supervisor'],true);
  $allQueues=DB::table('voice_live_queues')->where('workspace_id',$w)->get(['id','name','agent_ids']);$queues=$manage?$allQueues:$allQueues->filter(fn($q)=>in_array($r->user()->id,json_decode($q->agent_ids,true),true))->values();
  $allowed=(clone $visible)->distinct()->pluck('sender_id')->merge(DB::table('wa_inbox_routes')->where('workspace_id',$w)->whereIn('queue_id',$queues->pluck('id'))->pluck('sender_id'))->unique();
  $counts=(clone $visible)->selectRaw("sender_id,count(*) as total,sum(case when status='open' then 1 else 0 end) as open_count,sum(case when status='closed' then 1 else 0 end) as closed_count,sum(case when status='open' and last_inbound_at is not null and (read_at is null or last_inbound_at>read_at) then 1 else 0 end) as unread_count")->groupBy('sender_id')->get()->keyBy('sender_id');
  $senders=DB::table('wa_senders')->where('workspace_id',$w)->when(!$manage,fn($q)=>$q->whereIn('id',$allowed))->get(['id','label','number','provider','status'])->map(function($sender)use($counts){$c=$counts->get($sender->id);$sender->counts=['total'=>(int)($c->total??0),'open'=>(int)($c->open_count??0),'closed'=>(int)($c->closed_count??0),'unread'=>(int)($c->unread_count??0)];return $sender;});
  if(isset($d['sender_id']))abort_unless($senders->contains('id',$d['sender_id']),404);
  $query=$visible->when($d['sender_id']??null,fn($q)=>$q->where('sender_id',$d['sender_id']))->when($d['status']??null,fn($q)=>$q->where('status',$d['status']))->when($d['search']??null,fn($q)=>$q->where('phone','like','%'.preg_replace('/[^0-9+]/','',$d['search']).'%'));
  $rows=$query->orderByDesc('last_message_at')->orderBy('id')->paginate(30);
  return response()->json(['rows'=>$rows,'user_id'=>$r->user()->id,'can_manage'=>$manage,'agents'=>DB::table('users')->where('voice_workspace_id',$w)->where('voice_enabled',true)->get(['id','name']),'queues'=>$queues,'senders'=>$senders,'routes'=>$manage?DB::table('wa_inbox_routes')->where('workspace_id',$w)->get():[],'templates'=>app(WhatsAppQrTemplates::class)->catalog($w),'leads'=>$manage?DB::table('social_leads')->where('workspace_id',$w)->latest()->limit(50)->get():[]])->header('Cache-Control','no-store, private');
 }
 public function show(Request $r,string $id){$w=$this->workspace($r);$c=app(ConversationInbox::class)->visible($w,$r->user())->where('id',$id)->firstOrFail();$d=$r->validate(['page'=>'nullable|integer|min:1|max:10000']);$messages=DB::table('wa_messages')->where('workspace_id',$w)->where('conversation_id',$id)->orderByDesc('created_at')->orderByDesc('id')->paginate(50,['id','direction','provider','status','body','speech_asset_id','interactive','created_at','button_id','button_label','campaign_id','user_id']);$contact=$c->contact_id?DB::table('voice_contacts')->where('workspace_id',$w)->where('id',$c->contact_id)->first(['id','name','phone','suppressed_at']):null;$campaign=DB::table('wa_messages')->where('workspace_id',$w)->where('conversation_id',$id)->whereNotNull('campaign_id')->orderByDesc('created_at')->value('campaign_id');if($contact&&$campaign)$contact=app(\App\Services\VoiceAudience::class)->personalize($w,$campaign,$contact);return response()->json(['conversation'=>$c,'messages'=>$messages,'contact'=>$contact])->header('Cache-Control','no-store, private');}
 public function audio(Request $r,string $id,string $message){$w=$this->workspace($r);app(ConversationInbox::class)->visible($w,$r->user())->where('id',$id)->firstOrFail();$m=DB::table('wa_messages')->where('workspace_id',$w)->where('conversation_id',$id)->where('id',$message)->firstOrFail();abort_unless($m->speech_asset_id,404);return response()->file(app(\App\Services\SpeechStudio::class)->file($w,$m->speech_asset_id,'mp3'),['Content-Type'=>'audio/mpeg','Cache-Control'=>'private, no-store']);}
 public function assign(Request $r,string $id){$w=$this->workspace($r);$d=$r->validate(['user_id'=>'nullable|integer','queue_id'=>'nullable|integer','revision'=>'required|integer|min:1','status'=>'required|in:open,closed']);return DB::transaction(function()use($w,$r,$id,$d){DB::table('voice_runtime')->where('id',1)->lockForUpdate()->firstOrFail();$c=app(ConversationInbox::class)->visible($w,$r->user())->where('id',$id)->firstOrFail();abort_unless($c->revision===$d['revision'],409,'A conversa mudou. Atualize antes de salvar.');$manage=in_array($r->user()->voice_role,['admin','supervisor'],true);
  if(!$manage)abort_unless(($c->assigned_user_id===null||$c->assigned_user_id===$r->user()->id)&&($d['user_id']??null)===$r->user()->id&&($d['queue_id']??null)===$c->queue_id,403);
  $queue=isset($d['queue_id'])?DB::table('voice_live_queues')->where('workspace_id',$w)->where('id',$d['queue_id'])->firstOrFail():null;
  if(isset($d['user_id'])){DB::table('users')->where('voice_workspace_id',$w)->where('voice_enabled',true)->where('id',$d['user_id'])->firstOrFail();abort_if($queue&&!in_array($d['user_id'],json_decode($queue->agent_ids,true),true),422,'O atendente precisa pertencer à fila.');}
  DB::table('wa_conversations')->where('id',$id)->update(['assigned_user_id'=>$d['user_id']??null,'queue_id'=>$d['queue_id']??null,'status'=>$d['status'],'revision'=>$c->revision+1,'updated_at'=>now()]);app(VoiceLab::class)->audit($w,$r->user()->id,'conversation.assigned',$id,$d);return ['ok'=>true];});}
 public function read(Request $r,string $id){$w=$this->workspace($r);app(ConversationInbox::class)->visible($w,$r->user())->where('id',$id)->firstOrFail();DB::table('wa_conversations')->where('id',$id)->update(['read_at'=>now()]);return ['ok'=>true];}
 public function send(Request $r,string $id){$w=$this->workspace($r);$d=$r->validate(['idempotency_key'=>'required|uuid','speech_asset_id'=>'nullable|uuid','body'=>'required_without_all:qr_template_id,speech_asset_id|nullable|string|max:4000','qr_template_id'=>'nullable|uuid','experimental_confirmed'=>'sometimes|boolean']);$m=app(ConversationInbox::class)->send($w,$r->user(),$id,$d);return ['id'=>$m->id,'status'=>$m->status];}
 public function route(Request $r){$w=$this->workspace($r,true);$d=$r->validate(['sender_id'=>'required|integer','queue_id'=>'required|integer','enabled'=>'required|boolean','max_open'=>'required|integer|between:1,20','apply_pending'=>'sometimes|boolean']);return DB::transaction(function()use($w,$r,$d){DB::table('voice_runtime')->where('id',1)->lockForUpdate()->firstOrFail();DB::table('wa_senders')->where('workspace_id',$w)->where('id',$d['sender_id'])->firstOrFail();DB::table('voice_live_queues')->where('workspace_id',$w)->where('id',$d['queue_id'])->firstOrFail();$pending=(bool)($d['apply_pending']??false);unset($d['apply_pending']);$existing=DB::table('wa_inbox_routes')->where('sender_id',$d['sender_id'])->first();DB::table('wa_inbox_routes')->updateOrInsert(['sender_id'=>$d['sender_id']],$d+['workspace_id'=>$w,'created_at'=>$existing?->created_at??now(),'updated_at'=>now()]);$applied=0;if($pending)$applied=DB::table('wa_conversations')->where('workspace_id',$w)->where('sender_id',$d['sender_id'])->where('status','open')->whereNull('assigned_user_id')->whereNull('queue_id')->update(['queue_id'=>$d['queue_id'],'revision'=>DB::raw('revision+1'),'updated_at'=>now()]);app(VoiceLab::class)->audit($w,$r->user()->id,'conversation.route',$d['sender_id'],$d+['pending_linked'=>$applied]);return ['ok'=>true,'pending_linked'=>$applied];});}
}
