<?php
namespace App\Http\Controllers;
use Carbon\CarbonImmutable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class InboundReportsController extends Controller {
 private const ZONE='America/Sao_Paulo';
 private function workspace(Request $r):int{abort_unless($r->user()->voice_workspace_id===1&&in_array($r->user()->voice_role,['admin','supervisor'],true),403);return 1;}
 private function outcome(object $c):string{return $c->answered_at?'answered':(!$c->capacity_released_at?'active':($c->status==='unavailable'?'unavailable':'abandoned'));}
 private function filters(Request $r):array{$d=$r->validate(['from'=>'required|date_format:Y-m-d','to'=>'required|date_format:Y-m-d|after_or_equal:from','queue_id'=>'nullable|integer|min:1','user_id'=>'nullable|integer|min:1','outcome'=>'nullable|in:answered,active,unavailable,abandoned','page'=>'nullable|integer|between:1,10000']);abort_if(CarbonImmutable::parse($d['from'])->diffInDays(CarbonImmutable::parse($d['to']))>89,422,'Use um período de até 90 dias.');return $d;}
 private function query(int $w,array $d){return DB::table('voice_inbound_calls as c')->where('c.workspace_id',$w)->where('c.created_at','>=',CarbonImmutable::parse($d['from'],self::ZONE)->utc())->where('c.created_at','<',CarbonImmutable::parse($d['to'],self::ZONE)->addDay()->utc())->when($d['queue_id']??null,fn($q)=>$q->where('c.queue_id',$d['queue_id']))->when($d['user_id']??null,fn($q)=>$q->where('c.user_id',$d['user_id']));}
 public function index(Request $r){$w=$this->workspace($r);$d=$this->filters($r);if(isset($d['queue_id']))DB::table('voice_live_queues')->where('workspace_id',$w)->where('id',$d['queue_id'])->firstOrFail();if(isset($d['user_id']))DB::table('users')->where('voice_workspace_id',$w)->where('id',$d['user_id'])->firstOrFail();$base=$this->query($w,$d);$counts=['total'=>0,'answered'=>0,'active'=>0,'unavailable'=>0,'abandoned'=>0,'tabulation_pending'=>0,'transferred'=>0];$days=[];$waits=[];$agents=[];
  for($day=CarbonImmutable::parse($d['from']);$day->toDateString()<=$d['to'];$day=$day->addDay())$days[$day->toDateString()]=['date'=>$day->toDateString(),'answered'=>0,'active'=>0,'unavailable'=>0,'abandoned'=>0];
  foreach((clone $base)->select('c.id','c.created_at','c.answered_at','c.capacity_released_at','c.status','c.user_id')->orderBy('c.id')->cursor()as $c){$outcome=$this->outcome($c);$counts['total']++;$counts[$outcome]++;$date=CarbonImmutable::parse($c->created_at,'UTC')->setTimezone(self::ZONE)->toDateString();$days[$date][$outcome]++;if($c->status==='tabulation')$counts['tabulation_pending']++;if($c->answered_at)$waits[]=max(0,CarbonImmutable::parse($c->created_at)->diffInSeconds(CarbonImmutable::parse($c->answered_at)));if($c->user_id){$agents[$c->user_id]??=['user_id'=>$c->user_id,'total'=>0,'answered'=>0];$agents[$c->user_id]['total']++;if($c->answered_at)$agents[$c->user_id]['answered']++;}}
  $counts['transferred']=DB::table('voice_inbound_offers')->whereIn('call_id',(clone $base)->select('c.id'))->where('status','transferred')->distinct()->count('call_id');$names=DB::table('users')->where('voice_workspace_id',$w)->pluck('name','id');foreach($agents as &$agent)$agent['name']=$names[$agent['user_id']]??'Atendente';unset($agent);
  $list=clone $base;switch($d['outcome']??null){case 'answered':$list->whereNotNull('c.answered_at');break;case 'active':$list->whereNull('c.answered_at')->whereNull('c.capacity_released_at');break;case 'unavailable':$list->whereNull('c.answered_at')->whereNotNull('c.capacity_released_at')->where('c.status','unavailable');break;case 'abandoned':$list->whereNull('c.answered_at')->whereNotNull('c.capacity_released_at')->where('c.status','!=','unavailable');break;}
  $rows=$list->leftJoin('users as u','u.id','=','c.user_id')->leftJoin('voice_live_queues as q','q.id','=','c.queue_id')->orderByDesc('c.created_at')->orderBy('c.id')->paginate(25,['c.id','c.from_number','c.to_number','c.status','c.created_at','c.answered_at','c.ended_at','c.capacity_released_at','c.bill_seconds','c.disposition_code','u.name as agent_name','q.name as queue_name']);$rows->getCollection()->transform(function($c){$c->outcome=$this->outcome($c);return $c;});
  return response()->json(['counts'=>$counts,'answer_rate'=>$counts['total']?round(100*$counts['answered']/$counts['total'],1):null,'average_wait_seconds'=>$waits?round(array_sum($waits)/count($waits),1):null,'days'=>array_values($days),'agents'=>array_values($agents),'rows'=>$rows,'queues'=>DB::table('voice_live_queues')->where('workspace_id',$w)->get(['id','name']),'users'=>DB::table('users')->where('voice_workspace_id',$w)->get(['id','name']),'timezone'=>self::ZONE,'scope'=>'Chamadas admitidas e registradas pelo MA. Recusas anteriores à admissão não entram nestes totais. Atendidas inclui conversas em andamento.'])->header('Cache-Control','no-store, private');
 }
 public function show(Request $r,string $id){$w=$this->workspace($r);$c=DB::table('voice_inbound_calls')->where('workspace_id',$w)->where('id',$id)->firstOrFail(['id','queue_id','user_id','from_number','to_number','status','answered_at','ended_at','capacity_released_at','bill_seconds','disposition_code','notes','created_at']);$c->outcome=$this->outcome($c);return response()->json(['call'=>$c,'offers'=>DB::table('voice_inbound_offers as o')->join('users as u','u.id','=','o.user_id')->where('o.call_id',$id)->orderBy('o.created_at')->get(['o.id','o.status','o.answered_at','o.ended_at','o.created_at','u.name as agent_name']),'events'=>DB::table('voice_audit')->where('workspace_id',$w)->where('subject_id',$id)->where('event','like','inbound.%')->orderBy('id')->get(['event','created_at'])])->header('Cache-Control','no-store, private');}
}
