<?php
namespace App\Http\Controllers;
use App\Services\{InboundVoice,VoiceLab,VoiceAgentCapacity,TwilioVoiceConnection};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class InboundVoiceController extends Controller {
 private function workspace(Request $r,bool $manage=false):int {abort_unless($r->user()->voice_workspace_id===1,403);if($manage)abort_unless(in_array($r->user()->voice_role,['admin','supervisor'],true),403);return 1;}
 public function index(Request $r){$w=$this->workspace($r);$manage=in_array($r->user()->voice_role,['admin','supervisor'],true);$u=$r->user()->id;
  $queues=DB::table('voice_live_queues')->where('workspace_id',$w)->get(['id','name','agent_ids'])->map(function($q){$q->agent_ids=json_decode($q->agent_ids,true);return $q;});if(!$manage)$queues=$queues->filter(fn($q)=>in_array($u,$q->agent_ids,true))->values();
  $calls=DB::table('voice_inbound_calls')->where('workspace_id',$w)->when(!$manage,fn($q)=>$q->where('user_id',$u)->orWhere(function($b)use($w,$u){$b->where('workspace_id',$w)->whereIn('id',DB::table('voice_inbound_offers')->where('user_id',$u)->select('call_id'));}))->orderByDesc('created_at')->limit(100)->get(['id','queue_id','from_number','to_number','status','user_id','answered_at','ended_at','capacity_released_at','bill_seconds','disposition_code','notes','revision','created_at']);
  $agents=DB::table('users')->where('voice_workspace_id',$w)->where('voice_enabled',true)->whereIn('id',$queues->flatMap(fn($q)=>$q->agent_ids)->unique())->get(['id','name']);
  $current=$calls->first(fn($c)=>$c->user_id===$u&&(!$c->capacity_released_at||$c->status==='tabulation'));
  $cfg=app(TwilioVoiceConnection::class)->read();return response()->json(['can_manage'=>$manage,'user_id'=>$u,'queues'=>$queues,'calls'=>$calls,'agents'=>$agents,'current'=>$current,'routes'=>$manage?DB::table('voice_inbound_routes')->where('workspace_id',$w)->get():[],'configured_number'=>$manage?($cfg['caller_id']??null):null,'voice_url'=>InboundVoice::BASE,'status_url'=>InboundVoice::BASE.'/status'])->header('Cache-Control','no-store, private');
 }
 public function route(Request $r,?int $id=null){$w=$this->workspace($r,true);$d=$r->validate(['number'=>['required','regex:/^\+[1-9][0-9]{7,14}$/D'],'queue_id'=>'required|integer','enabled'=>'required|boolean','ring_seconds'=>'required|integer|between:5,60','wait_seconds'=>'required|integer|between:10,600','revision'=>$id?'required|integer':'nullable|integer']);
  return DB::transaction(function()use($w,$r,$d,$id){DB::table('voice_runtime')->where('id',1)->lockForUpdate()->firstOrFail();DB::table('voice_live_queues')->where('workspace_id',$w)->where('id',$d['queue_id'])->firstOrFail();$cfg=app(TwilioVoiceConnection::class)->read();abort_unless($cfg && $cfg['caller_id']===$d['number'],422,'Use o número da conexão Twilio configurada.');
   $old=$id?DB::table('voice_inbound_routes')->where('workspace_id',$w)->where('id',$id)->firstOrFail():null;abort_if($old&&($old->revision!==$d['revision']||$old->number!==$d['number']),409,'Atualize a rota antes de salvar.');abort_if(!$old&&DB::table('voice_inbound_routes')->where('number',$d['number'])->exists(),409,'Este número já possui uma rota.');
   abort_if($id&&DB::table('voice_inbound_calls')->where('route_id',$id)->whereNull('capacity_released_at')->exists(),409,'Aguarde o encerramento das chamadas desta rota.');unset($d['revision']);$d+=['revision'=>$old?$old->revision+1:1,'updated_at'=>now()];if($id)DB::table('voice_inbound_routes')->where('id',$id)->update($d);else $id=DB::table('voice_inbound_routes')->insertGetId($d+['workspace_id'=>$w,'created_at'=>now()]);app(VoiceLab::class)->audit($w,$r->user()->id,'inbound.route_saved',$id);return ['id'=>$id];});
 }
 public function publish(Request $r,int $id){return app(InboundVoice::class)->publishRoute($this->workspace($r,true),$r->user()->id,$id);}
 public function token(Request $r){$d=$r->validate(['session_id'=>'required|uuid']);return response()->json(app(InboundVoice::class)->token($this->workspace($r),$r->user()->id,$d['session_id']))->header('Cache-Control','no-store, private');}
 public function device(Request $r){$d=$r->validate(['session_id'=>'required|uuid','ready'=>'required|boolean']);app(InboundVoice::class)->device($this->workspace($r),$r->user()->id,$d['session_id'],$d['ready']);return ['ok'=>true];}
 public function transfer(Request $r,string $id){$d=$r->validate(['user_id'=>'required|integer']);return app(InboundVoice::class)->transfer($this->workspace($r),$r->user()->id,$id,$d['user_id']);}
 public function reconcile(Request $r,string $id){$w=$this->workspace($r);$c=DB::table('voice_inbound_calls')->where('workspace_id',$w)->where('id',$id)->firstOrFail();abort_unless($c->user_id===$r->user()->id||in_array($r->user()->voice_role,['admin','supervisor'],true),403);return app(InboundVoice::class)->reconcile($c);}
 public function disposition(Request $r,string $id){$w=$this->workspace($r);$d=$r->validate(['code'=>'required|string|max:40','notes'=>'nullable|string|max:2000','revision'=>'required|integer']);return DB::transaction(function()use($w,$r,$id,$d){DB::table('voice_runtime')->where('id',1)->lockForUpdate()->firstOrFail();$c=DB::table('voice_inbound_calls')->where('workspace_id',$w)->where('id',$id)->firstOrFail();abort_unless($c->user_id===$r->user()->id||in_array($r->user()->voice_role,['admin','supervisor'],true),403);abort_unless($c->capacity_released_at&&$c->revision===$d['revision'],409);$code=DB::table('voice_disposition_codes')->where('workspace_id',$w)->where('code',$d['code'])->where('active',true)->firstOrFail();DB::table('voice_inbound_calls')->where('id',$id)->update(['status'=>$c->answered_at?'completed':$c->status,'disposition_code'=>$d['code'],'notes'=>$d['notes']??null,'revision'=>$c->revision+1,'updated_at'=>now()]);$q=DB::table('voice_live_queues')->find($c->queue_id);DB::table('voice_agent_presence')->where('user_id',$c->user_id)->update(['available_after'=>now()->addSeconds($q->wrapup_seconds),'updated_at'=>now()]);app(VoiceLab::class)->audit($w,$r->user()->id,'inbound.disposition',$id,$d);return ['ok'=>true];});}
 public function callback(Request $r,string $kind='receive',?string $id=null){$suffix='/inbound'.($kind==='receive'?'':'/'.$kind.($id?'/'.$id:''));app(TwilioVoiceWebhookController::class)->verify($r,$suffix);$s=app(InboundVoice::class);$d=$r->validate(['CallSid'=>['required','regex:/^CA[0-9a-fA-F]{32}$/D'],'AccountSid'=>'required|string','To'=>'sometimes|string|max:80','From'=>'sometimes|string|max:80','CallStatus'=>'sometimes|in:queued,initiated,ringing,in-progress,completed,busy,failed,no-answer,canceled','ParentCallSid'=>['sometimes','regex:/^CA[0-9a-fA-F]{32}$/D'],'DialCallSid'=>['nullable','regex:/^CA[0-9a-fA-F]{32}$/D'],'DialCallStatus'=>'sometimes|in:completed,busy,failed,no-answer,canceled','CallDuration'=>'nullable|integer|between:0,86400']);
  if($kind==='receive'){$r->validate(['To'=>'required','From'=>'required']);$xml=$s->receive($d);}elseif($kind==='status'){$r->validate(['CallStatus'=>'required']);$s->ended($d);return response('',204);}elseif($kind==='offer'){$r->validate(['ParentCallSid'=>'required','CallStatus'=>'required']);$s->offerStatus($id,$d);return response('',204);}elseif($kind==='finish'){$r->validate(['DialCallStatus'=>'required']);$xml=$s->finish($id,$d);}elseif($kind==='wait')$xml=$s->dispatch($id,$d['CallSid']);else $xml=$s->transferDial($id,$d);
  return response($xml)->header('Content-Type','application/xml')->header('Cache-Control','no-store');
 }
}
