<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{DB,Crypt};
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use App\Services\{IntegrationEvents,VoiceLab};
class IntegrationController extends Controller {
 public const SCOPES=['lists:read','lists:write','calls:read','reports:read','events:read','voice:embed','leads:write'];
 private function workspace(Request $r):int{abort_unless($r->user()->voice_workspace_id===1&&$r->user()->voice_role==='admin',403,'Integrações externas são administradas pelo administrador.');return 1;}
 public function index(Request $r){$w=$this->workspace($r);return response()->json(['integrations'=>DB::table('ma_integrations')->where('workspace_id',$w)->get(['id','name','scopes','list_keys','agent_ids','embed_origin','webhook_url','active','last_used_at','created_at']),'scopes'=>self::SCOPES,'agents'=>DB::table('users')->where('voice_workspace_id',$w)->where('voice_enabled',true)->where('voice_role','agent')->get(['id','name']),'lists'=>collect(DB::table('audiences')->get(['id','name']))->map(fn($v)=>['key'=>'automation:'.$v->id,'name'=>$v->name])->concat(DB::table('voice_lists')->where('workspace_id',$w)->get(['id','name'])->map(fn($v)=>['key'=>'voice:'.$v->id,'name'=>$v->name])),'deliveries'=>DB::table('ma_event_deliveries')->whereIn('integration_id',DB::table('ma_integrations')->where('workspace_id',$w)->select('id'))->orderByDesc('created_at')->limit(100)->get(['id','integration_id','event_sequence','status','attempts','http_status','next_at'])])->header('Cache-Control','no-store, private');}
 public function create(Request $r){$w=$this->workspace($r);$d=$r->validate(['name'=>'required|string|max:160','scopes'=>'required|array|min:1|max:7','scopes.*'=>['required','distinct',Rule::in(self::SCOPES)],'list_keys'=>'present|array|max:100','list_keys.*'=>['required','distinct','regex:/^(automation|voice):[1-9][0-9]*$/D'],'agent_ids'=>'present|array|max:100','agent_ids.*'=>'integer|distinct','embed_origin'=>'nullable|url:https|max:255','webhook_url'=>'nullable|url:https|max:1000']);
  foreach($d['list_keys'] as $key){[$kind,$id]=explode(':',$key);app(\App\Services\ListContacts::class)->list($w,$kind,(int)$id);}abort_unless(DB::table('users')->where('voice_workspace_id',$w)->where('voice_enabled',true)->where('voice_role','agent')->whereIn('id',$d['agent_ids'])->count()===count($d['agent_ids']),422,'Selecione atendentes ativos deste workspace.');
  if(!empty($d['embed_origin'])){abort_unless(preg_match('~^https://(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$~D',$d['embed_origin']),422,'Informe uma origem HTTPS pública, sem caminho.');$p=parse_url($d['embed_origin']);abort_unless(($p['scheme']??'')==='https'&&isset($p['host'])&&!isset($p['user'])&&!isset($p['pass'])&&!isset($p['query'])&&!isset($p['fragment'])&&empty($p['path'])&&!isset($p['port']),422,'Informe somente a origem HTTPS, sem caminho ou barra final.');}
  abort_if(in_array('voice:embed',$d['scopes'],true)&&(empty($d['embed_origin'])||!$d['agent_ids']),422,'O discador incorporável exige origem e atendentes permitidos.');if(!empty($d['webhook_url'])){abort_unless(in_array('events:read',$d['scopes'],true),422);app(IntegrationEvents::class)->destination($d['webhook_url']);}
  $token='mai_'.bin2hex(random_bytes(32));$secret=bin2hex(random_bytes(32));$id=(string)Str::uuid();DB::table('ma_integrations')->insert(['id'=>$id,'workspace_id'=>$w,'created_by'=>$r->user()->id,'name'=>$d['name'],'token_hash'=>hash('sha256',$token),'scopes'=>json_encode($d['scopes']),'list_keys'=>json_encode($d['list_keys']),'agent_ids'=>json_encode($d['agent_ids']),'embed_origin'=>$d['embed_origin']??null,'webhook_url'=>$d['webhook_url']??null,'webhook_secret'=>Crypt::encryptString($secret),'active'=>true,'created_at'=>now(),'updated_at'=>now()]);app(VoiceLab::class)->audit($w,$r->user()->id,'integration.created',$id);return response()->json(['id'=>$id,'token'=>$token,'webhook_secret'=>$secret,'message'=>'Guarde os segredos no servidor integrador; não serão exibidos novamente.'],201)->header('Cache-Control','no-store, private');
 }
 public function referenceSession(Request $r,string $id){$w=$this->workspace($r);$i=DB::table('ma_integrations')->where('workspace_id',$w)->where('id',$id)->where('active',true)->firstOrFail();abort_unless($i->embed_origin===$r->getSchemeAndHttpHost()&&in_array('voice:embed',json_decode($i->scopes,true),true),403);$r->attributes->set('integration',$i);return response()->json(app(PublicApiController::class)->session($r))->header('Cache-Control','no-store, private');}
 public function revoke(Request $r,string $id){$w=$this->workspace($r);DB::table('ma_integrations')->where('workspace_id',$w)->where('id',$id)->firstOrFail();DB::table('ma_integrations')->where('id',$id)->update(['active'=>false,'updated_at'=>now()]);app(VoiceLab::class)->audit($w,$r->user()->id,'integration.revoked',$id);return ['ok'=>true];}
 public function retry(Request $r,string $id){$w=$this->workspace($r);$d=DB::table('ma_event_deliveries')->where('id',$id)->whereIn('integration_id',DB::table('ma_integrations')->where('workspace_id',$w)->where('active',true)->select('id'))->firstOrFail();abort_unless(in_array($d->status,['dead','retry'],true),409);DB::table('ma_event_deliveries')->where('id',$id)->update(['status'=>'pending','attempts'=>0,'next_at'=>now(),'updated_at'=>now()]);return ['ok'=>true];}
}
