<?php
namespace App\Http\Controllers;
use App\Models\{Journey,JourneyNode,JourneyEdge,JourneyVersion,Contact,Audience,JourneyNodeLog,JourneyToken,InboundEvent,CrmRecord};
use App\Services\{NodeCatalog,GraphValidator,JourneyExecutionEngine};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{Auth,DB};
class MarketingController extends Controller {
 public function login(Request $r){$d=$r->validate(['email'=>'required|email','password'=>'required|string']);if(!Auth::attempt($d+['voice_enabled'=>true]))return response()->json(['message'=>'E-mail ou senha inválidos.'],422);$r->session()->regenerate();$r->session()->put('voice_auth_version',(int)Auth::user()->voice_auth_version);return ['user'=>Auth::user()->only('name','email')];}
 public function logout(Request $r){Auth::logout();$r->session()->invalidate();$r->session()->regenerateToken();return ['ok'=>true];}
 public function bootstrap(){
  $user=Auth::user()->only('id','name','email','voice_role','voice_workspace_id','voice_enabled');
  if(Auth::user()->voice_workspace_id&&!in_array(Auth::user()->voice_role,['admin','supervisor']))return ['user'=>$user,'catalog'=>[],'journeys'=>[],'audiences'=>[],'contacts'=>[],'crm_records'=>[]];
  return ['user'=>$user,'catalog'=>array_values(NodeCatalog::all()),'journeys'=>Journey::with('audiences')->withCount('subscribers')->latest()->get(),'audiences'=>Audience::withCount('contacts')->get(),'contacts'=>Contact::with('audiences')->latest()->limit(500)->get(),'crm_records'=>CrmRecord::latest()->limit(100)->get(),'integration_ready'=>(bool)config('marketing.gateway_url'),'crm_catalog'=>['contract_version'=>1,'kinds'=>CrmCatalogController::KINDS,'synced'=>\App\Models\CrmResource::where('origin','crm')->exists()]];}
 public function create(Request $r){$d=$r->validate(['title'=>'required|string|max:160','description'=>'nullable|string|max:3000','audience_ids'=>'required|array|min:1','audience_ids.*'=>'integer|exists:audiences,id','start_date'=>'required|date','end_date'=>'nullable|required_if:is_indefinite,false|date|after:start_date','is_indefinite'=>'required|boolean']);$j=DB::transaction(function()use($d){$ids=$d['audience_ids'];unset($d['audience_ids']);if($d['is_indefinite'])$d['end_date']=null;$j=Journey::create($d+['graph'=>['nodes'=>[],'edges'=>[]]]);$j->audiences()->sync($ids);return $j;});return $j->load('audiences');}
 public function show(Journey $journey,Request $r){$d=$r->validate(['from'=>'nullable|date','to'=>'nullable|date|after_or_equal:from']);$logs=JourneyNodeLog::where('journey_id',$journey->id);if(!empty($d['from']))$logs->where('executed_at','>=',$d['from']);if(!empty($d['to']))$logs->where('executed_at','<=',\Carbon\Carbon::parse($d['to'])->endOfDay());return ['journey'=>$journey->load('audiences'),'metrics'=>(clone $logs)->selectRaw('node_uuid, status, count(*) as total')->groupBy('node_uuid','status')->get(),'logs'=>(clone $logs)->latest('executed_at')->limit(100)->get(),'subscribers'=>$journey->subscribers()->with('contact','tokens')->latest()->limit(500)->get()];}
 public function save(Journey $journey,Request $r,GraphValidator $validator){$d=$r->validate(['revision'=>'required|integer|min:0','graph'=>'required|array:nodes,edges','graph.nodes'=>'present|array|max:150','graph.nodes.*.id'=>'required|string|max:100','graph.nodes.*.position.x'=>'required|numeric','graph.nodes.*.position.y'=>'required|numeric','graph.nodes.*.data.key'=>'required|string','graph.nodes.*.data.settings'=>'present|array','graph.edges'=>'present|array|max:300']);$validator->validate($d['graph']);return DB::transaction(function()use($journey,$d){$j=Journey::lockForUpdate()->findOrFail($journey->id);abort_if($j->revision!==$d['revision'],409,'A jornada mudou em outra sessão. Reabra antes de salvar.');$j->update(['graph'=>$d['graph'],'revision'=>$j->revision+1]);$j->nodes()->delete();$j->edges()->delete();foreach($d['graph']['nodes'] as $n){$meta=NodeCatalog::all()[$n['data']['key']];$j->nodes()->create(['node_uuid'=>$n['id'],'type'=>$meta['type'],'category_key'=>$meta['key'],'label'=>$meta['label'],'position_x'=>$n['position']['x'],'position_y'=>$n['position']['y'],'settings'=>$n['data']['settings']]);}foreach($d['graph']['edges']as $e)$j->edges()->create(['source_node_uuid'=>$e['source'],'target_node_uuid'=>$e['target'],'source_handle'=>$e['sourceHandle']??'success']);return $j;});}
 public function publish(Journey $journey,GraphValidator $v){return DB::transaction(function()use($journey,$v){$j=Journey::lockForUpdate()->findOrFail($journey->id);$v->validate($j->graph??[],true);abort_if($j->end_date&&$j->end_date->isPast(),422,'A vigência já terminou.');$version=($j->published_version??0)+1;JourneyVersion::create(['journey_id'=>$j->id,'version'=>$version,'graph'=>$j->graph]);$j->update(['status'=>'active','published_version'=>$version]);return $j;});}
 public function pause(Journey $journey){$journey->update(['status'=>'paused']);return $journey;}
 public function resume(Journey $journey){abort_unless($journey->published_version,422,'Publique primeiro.');$journey->update(['status'=>'active']);return $journey;}
 public function destroy(Journey $journey){abort_if($journey->subscribers()->exists(),422,'Jornada com histórico não pode ser excluída. Pause a jornada.');$journey->delete();return ['ok'=>true];}
 public function audience(Request $r){$d=$r->validate(['name'=>'required|string|max:160']);return Audience::create($d);}
 public function contact(Request $r,JourneyExecutionEngine $engine){$d=$r->validate(['name'=>'required|string|max:160','email'=>'nullable|email|max:200','phone'=>'nullable|string|max:40','subscribed'=>'required|boolean','audience_ids'=>'array','audience_ids.*'=>'integer|exists:audiences,id']);return DB::transaction(function()use($d,$engine){$ids=$d['audience_ids']??[];unset($d['audience_ids']);$c=Contact::create($d);$c->audiences()->sync($ids);foreach(Journey::where('status','active')->whereHas('audiences',fn($q)=>$q->whereIn('audiences.id',$ids))->get()as $j)$engine->enroll($j,$c,'contact-created:'.$c->id,'list_added',['audience_ids'=>$ids]);return $c;});}
 public function enroll(Journey $journey,Request $r,JourneyExecutionEngine $engine){$d=$r->validate(['contact_id'=>'required|integer|exists:contacts,id','event_key'=>'required|string|max:100']);$c=Contact::findOrFail($d['contact_id']);abort_unless($c->audiences()->whereIn('audiences.id',$journey->audiences()->pluck('audiences.id'))->exists(),422,'Contato fora do público da jornada.');$sub=$engine->enroll($journey,$c,$d['event_key']);abort_unless($sub,422,'Jornada precisa estar vigente, ativa e ter gatilho por API.');return $sub;}
 public function event(Request $r,JourneyExecutionEngine $engine){
  $secret=config('marketing.webhook_secret');$stamp=$r->header('X-MA-Timestamp','');$signature=$r->header('X-MA-Signature','');abort_unless($secret&&ctype_digit($stamp)&&abs(time()-(int)$stamp)<300&&hash_equals(hash_hmac('sha256',$stamp.'.'.$r->getContent(),$secret),$signature),401);
  $d=$r->validate(['event_key'=>'required|string|max:150','contact_id'=>'required|integer|exists:contacts,id','type'=>'required|string|max:80','token_id'=>'nullable|integer|exists:journey_tokens,id','status'=>'nullable|string|max:100','attributes'=>'sometimes|array:segment_id,campaign_id,event,button_key,form_id,goal_id,url,tag,stage,event_name,store_id,order_status,list_id,audience_ids','attributes.*'=>'nullable','attributes.audience_ids'=>'sometimes|array|max:100','attributes.audience_ids.*'=>'integer']);
  foreach($d['attributes']??[] as $key=>$value)if($key!=='audience_ids'&&(!is_string($value)||mb_strlen($value)>2000))throw \Illuminate\Validation\ValidationException::withMessages(['attributes.'.$key=>'Informe um texto de até 2000 caracteres.']);
  return DB::transaction(function()use($d,$engine){
   if(!DB::table('inbound_events')->insertOrIgnore(['event_key'=>$d['event_key'],'payload'=>json_encode($d),'created_at'=>now(),'updated_at'=>now()]))return ['duplicate'=>true];
   $c=Contact::findOrFail($d['contact_id']);
   if(!empty($d['token_id'])){
    $token=JourneyToken::lockForUpdate()->findOrFail($d['token_id']);abort_unless($token->subscriber->contact_id===$c->id,422);$sub=$token->subscriber;$graph=JourneyVersion::where('journey_id',$sub->journey_id)->where('version',$sub->version)->firstOrFail()->graph;
    $node=collect($graph['nodes'])->firstWhere('id',$token->node_uuid);
    if($token->status==='waiting'&&$node['data']['key']==='check_activity'&&(empty($node['data']['settings']['campaign_id'])||$node['data']['settings']['campaign_id']===($d['attributes']['campaign_id']??null))){if(($d['status']??null)!==($node['data']['settings']['event']??null))return ['accepted'=>true];$token->update(['context'=>array_merge($token->context??[],['activity'=>$d['status']??'']),'resume_at'=>now()]);\App\Jobs\ExecuteJourneyNodeJob::dispatch($token->id)->afterCommit();}
    if($node['data']['key']==='send_whatsapp'&&$token->status==='completed'&&$sub->journey->status==='active')foreach($graph['edges']as $e)if($e['source']===$node['id']&&($e['sourceHandle']??'')===($d['status']??'')){$engine->token($sub,$e['target'],$token->id.':'.$e['target'].':'.$d['status']);$sub->update(['status'=>'active']);}
   }else foreach(Journey::where('status','active')->whereHas('audiences',fn($q)=>$q->whereIn('audiences.id',$c->audiences()->pluck('audiences.id')))->get()as $j)$engine->enroll($j,$c,$d['event_key'],$d['type'],$d['attributes']??[]);
   return ['accepted'=>true];
  });
 }
}
