<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Services\{OperationPolicy,VoiceCallingConfig,VoiceAgentCapacity,VoiceLab,TwilioVoiceCalling,InboundVoice};
class OperationsHealthController extends Controller {
 private function workspace(Request $r,bool $admin=false):int{abort_unless($r->user()->voice_workspace_id===1&&in_array($r->user()->voice_role,$admin?['admin']:['admin','supervisor'],true),403);return 1;}
 public function index(Request $r){$w=$this->workspace($r);$day=now()->startOfDay();$policy=app(OperationPolicy::class)->get($w);$voice=app(VoiceCallingConfig::class)->read();$outbound=DB::table('voice_outbound_calls')->where('workspace_id',$w);$inbound=DB::table('voice_inbound_calls')->where('workspace_id',$w);$messages=DB::table('wa_messages')->where('workspace_id',$w)->where('direction','outbound');
  $costs=collect(app(\App\Services\ChannelCosts::class)->report($w,$day->toDateString(),$day->toDateString(),'',1,'UTC')['known'])->map(fn($v)=>(object)$v);
  $knownUsd=(float)($costs->firstWhere('currency','USD')?->amount??$costs->firstWhere('currency','usd')?->amount??0);
  $unknown=(clone $outbound)->where('created_at','>=',$day)->whereNotIn('id',DB::table('voice_call_costs')->whereNotNull('amount')->select('call_id'))->count();
  $team=DB::table('users as u')->leftJoin('voice_agent_presence as p','p.user_id','=','u.id')->where('u.voice_workspace_id',$w)->get(['u.id','u.name','u.voice_enabled','p.status','p.last_seen_at','p.available_after']);foreach($team as $u){$u->online=$u->voice_enabled&&$u->last_seen_at&&$u->last_seen_at>now()->subSeconds(90)->toDateTimeString();$u->busy=app(VoiceAgentCapacity::class)->busy($w,$u->id);}
  return response()->json(['policy'=>$policy,'can_manage'=>$r->user()->voice_role==='admin','day_utc'=>$day->toDateString(),'limits'=>['voice_daily'=>min($policy['voice_daily_limit'],$voice['daily_limit']??50),'whatsapp_daily'=>$policy['whatsapp_daily_limit'],'external_concurrency'=>1,'note'=>'Limites privados por canal também se aplicam. Concorrência mantida em 1 até homologação.'],'counts'=>['calls_today'=>(clone $outbound)->where('created_at','>=',$day)->count()+(clone $inbound)->where('created_at','>=',$day)->count(),'messages_today'=>(clone $messages)->where('created_at','>=',$day)->count(),'active_calls'=>(clone $outbound)->whereNull('capacity_released_at')->count()+(clone $inbound)->whereNull('capacity_released_at')->count(),'messages_unknown'=>(clone $messages)->whereIn('status',['unknown','sending'])->count(),'webhooks_dead'=>DB::table('ma_event_deliveries')->whereIn('integration_id',DB::table('ma_integrations')->where('workspace_id',$w)->select('id'))->where('status','dead')->count()],'costs'=>['known'=>$costs,'calls_without_cost'=>$unknown,'alert'=>$policy['cost_alert_usd']!==null&&$knownUsd>=(float)$policy['cost_alert_usd'],'scope'=>\App\Services\ChannelCosts::SCOPE.' Período: dia UTC. Alerta não é teto de cobrança.'],'team'=>$team,'pending_calls'=>(clone $outbound)->whereNull('capacity_released_at')->orderBy('created_at')->limit(100)->get(['id','user_id','destination','method','status','created_at','deadline_at']),'pending_inbound'=>(clone $inbound)->whereNull('capacity_released_at')->orderBy('created_at')->limit(100)->get(['id','from_number','status','created_at']),'pending_messages'=>(clone $messages)->whereIn('status',['sending','unknown'])->orderBy('created_at')->limit(100)->get(['id','provider','to_number','status','created_at'])])->header('Cache-Control','no-store, private');
 }
 public function policy(Request $r){$w=$this->workspace($r,true);$d=$r->validate(['revision'=>'required|integer|min:0','paused'=>'required|boolean','voice_daily_limit'=>'required|integer|between:1,50','whatsapp_daily_limit'=>'required|integer|between:1,100','cost_alert_usd'=>'nullable|numeric|min:0.01|max:100000']);return DB::transaction(function()use($w,$r,$d){DB::table('voice_runtime')->where('id',1)->lockForUpdate()->firstOrFail();$old=app(OperationPolicy::class)->get($w);abort_unless($old['revision']===$d['revision'],409,'Os limites mudaram. Atualize antes de salvar.');$d['revision']++;DB::table('ma_operation_policy')->updateOrInsert(['workspace_id'=>$w],$d+['created_at'=>now(),'updated_at'=>now()]);app(VoiceLab::class)->audit($w,$r->user()->id,'operation.policy',$w,$d);return ['ok'=>true];});}
 public function reconcile(Request $r,string $id){$w=$this->workspace($r);$c=DB::table('voice_outbound_calls')->where('workspace_id',$w)->where('id',$id)->firstOrFail();abort_unless($c->method==='programmable_voice',422,'A chamada SIP exige a conferência do PBX pelo procedimento operacional.');return app(TwilioVoiceCalling::class)->reconcile($w,$c->user_id,$id);}
}
