<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class OperationDiagnosticsController extends Controller {
 public function index(Request $r){abort_unless($r->user()->voice_workspace_id===1&&in_array($r->user()->voice_role,['admin','supervisor'],true),403);$d=$r->validate(['retention_days'=>'nullable|integer|between:30,3650']);$days=$d['retention_days']??90;$cutoff=now()->subDays($days);$integrations=DB::table('ma_integrations')->where('workspace_id',1)->select('id');$audio=DB::table('voice_audio_sessions')->whereNull('archived_at')->where('workspace_id',1);$sessions=(clone $audio)->leftJoin('users as u','u.id','=','voice_audio_sessions.user_id')->orderByDesc('voice_audio_sessions.created_at')->limit(20)->get(['voice_audio_sessions.id','voice_audio_sessions.status','voice_audio_sessions.created_at','voice_audio_sessions.duration','voice_audio_sessions.client_metrics','u.name as agent_name']);foreach($sessions as $s){$m=json_decode($s->client_metrics??'{}',true);$s->quality=$m['quality']??null;unset($s->client_metrics);}
 return response()->json(['sessions'=>$sessions,'retention'=>['days'=>$days,'cutoff_utc'=>$cutoff->toIso8601String(),'preview_only'=>true,'ended_audio_sessions'=>(clone $audio)->whereIn('status',['ended','cancelled','expired','failed'])->where('updated_at','<',$cutoff)->count(),'expired_embed_sessions'=>DB::table('ma_embed_sessions')->whereIn('integration_id',$integrations)->where('expires_at','<',$cutoff)->count(),'finished_event_deliveries'=>DB::table('ma_event_deliveries')->whereIn('integration_id',$integrations)->whereIn('status',['delivered','cancelled'])->where('updated_at','<',$cutoff)->count()],'scope'=>'Diagnósticos internos navegador–PBX, informados pelo navegador. Não representam a qualidade do trecho da operadora.'])->header('Cache-Control','no-store, private');
 }
}
