<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Services\{ListContacts,JourneyReports,IntegrationEvents,VoiceLab};
class PublicApiController extends Controller {
 private function integration(Request $r):object{return $r->attributes->get('integration');}
 private function idempotent(Request $r,callable $fn):array{$i=$this->integration($r);$key=$r->header('Idempotency-Key');abort_unless(is_string($key)&&Str::isUuid($key),422,'Envie Idempotency-Key UUID.');$hash=hash('sha256',$r->method().'|'.$r->path().'|'.$r->getContent());return DB::transaction(function()use($i,$key,$hash,$fn){DB::table('voice_runtime')->where('id',1)->lockForUpdate()->firstOrFail();$old=DB::table('ma_integration_requests')->where('integration_id',$i->id)->where('key',$key)->first();if($old){abort_unless(hash_equals($old->request_hash,$hash),409,'Chave utilizada com outro conteúdo.');return json_decode($old->response,true);}$response=$fn($i);DB::table('ma_integration_requests')->insert(['integration_id'=>$i->id,'key'=>$key,'request_hash'=>$hash,'response'=>json_encode($response),'created_at'=>now(),'updated_at'=>now()]);return $response;});}
 public function entry(Request $r,int $id){$d=$r->validate(['contact_id'=>'required|integer|min:1','event_key'=>'required|string|max:160|regex:/^[A-Za-z0-9_.:\-]+$/D']);return $this->idempotent($r,function($i)use($id,$d){$p=DB::table('voice_campaign_policies')->where('campaign_id',$id)->first();$key=$p?->audience_id?'automation:'.$p->audience_id:($p?->list_id?'voice:'.$p->list_id:null);abort_unless($key&&in_array($key,json_decode($i->list_keys,true),true),403,'A integração não tem acesso ao segmento desta cadência.');return app(\App\Services\CadenceReentry::class)->event($i->workspace_id,$id,$d['contact_id'],$d['event_key']);});}
 public function lists(Request $r){$i=$this->integration($r);$s=app(ListContacts::class);$rows=[];foreach(json_decode($i->list_keys,true) as $key){[$kind,$id]=explode(':',$key);$list=$s->list($i->workspace_id,$kind,(int)$id);$rows[]=['kind'=>$kind,'id'=>$list->id,'name'=>$list->name,'fields'=>$s->settings($i->workspace_id,$kind,(int)$id)['fields']];}return ['data'=>$rows];}
 public function import(Request $r){$d=$r->validate(['kind'=>'required|in:automation,voice','list_id'=>'required|integer|min:1','contacts'=>'required|array|min:1|max:100','contacts.*'=>'required|array:name,email,phone,source,crm_contact_id,consent,consent_evidence,fields']);return $this->idempotent($r,function($i)use($d){abort_unless(in_array($d['kind'].':'.$d['list_id'],json_decode($i->list_keys,true),true),403,'Lista não autorizada para esta integração.');$s=app(ListContacts::class);$s->list($i->workspace_id,$d['kind'],$d['list_id']);$schema=$s->settings($i->workspace_id,$d['kind'],$d['list_id'])['fields'];$results=[];foreach($d['contacts'] as $c)$results[]=$s->ingest($i->workspace_id,$d['kind'],$d['list_id'],$s->normalize($d['kind'],$schema,$c));$id=(string)Str::uuid();app(IntegrationEvents::class)->emit($i->workspace_id,'contacts.imported',$id,'import:'.$id,['kind'=>$d['kind'],'list_id'=>$d['list_id'],'count'=>count($results)]);return ['id'=>$id,'results'=>$results];});}
 public function calls(Request $r){$i=$this->integration($r);$d=$r->validate(['page'=>'nullable|integer|between:1,100000','campaign_id'=>'nullable|integer|min:1','run_id'=>'nullable|uuid']);return DB::table('voice_outbound_calls')->where('workspace_id',$i->workspace_id)->when($d['campaign_id']??null,fn($q)=>$q->where('campaign_id',$d['campaign_id']))->when($d['run_id']??null,fn($q)=>$q->where('run_id',$d['run_id']))->orderByDesc('created_at')->paginate(50,['id','run_id','campaign_id','contact_id','user_id','destination','caller_id','status','disposition_code','started_at','answered_at','ended_at','bill_seconds']);}
 public function reports(Request $r){$i=$this->integration($r);$d=$r->validate(['from'=>'required|date_format:Y-m-d','to'=>'required|date_format:Y-m-d|after_or_equal:from','campaign_id'=>'nullable|integer|min:1','run_id'=>'nullable|uuid']);abort_unless(\Carbon\CarbonImmutable::parse($d['from'])->diffInDays(\Carbon\CarbonImmutable::parse($d['to']))<=365,422);if(isset($d['campaign_id']))DB::table('voice_campaigns')->where('workspace_id',$i->workspace_id)->where('id',$d['campaign_id'])->firstOrFail();return app(JourneyReports::class)->dashboard($i->workspace_id,$d);}
 public function events(Request $r){$i=$this->integration($r);$d=$r->validate(['after'=>'nullable|integer|min:0']);$rows=DB::table('ma_public_events')->where('workspace_id',$i->workspace_id)->where('sequence','>',$d['after']??0)->orderBy('sequence')->limit(100)->get();return ['data'=>$rows->map(fn($e)=>['sequence'=>$e->sequence]+json_decode($e->payload,true)),'next_cursor'=>$rows->last()?->sequence??($d['after']??0)];}
 public function session(Request $r){$i=$this->integration($r);$d=$r->validate(['user_id'=>'required|integer']);abort_unless(in_array($d['user_id'],json_decode($i->agent_ids,true),true)&&$i->embed_origin,403);$u=DB::table('users')->where('voice_workspace_id',$i->workspace_id)->where('voice_enabled',true)->where('voice_role','agent')->where('id',$d['user_id'])->firstOrFail();$token='mae_'.bin2hex(random_bytes(32));DB::table('ma_embed_sessions')->insert(['id'=>(string)Str::uuid(),'integration_id'=>$i->id,'user_id'=>$u->id,'auth_version'=>$u->voice_auth_version,'token_hash'=>hash('sha256',$token),'expires_at'=>now()->addMinutes(10),'created_at'=>now(),'updated_at'=>now()]);return ['access_token'=>$token,'expires_in'=>600,'origin'=>$i->embed_origin,'iframe_url'=>url('/embed').'?origin='.rawurlencode($i->embed_origin)];}
 public function lead(Request $r){$d=$r->validate(['source'=>'required|in:facebook,instagram,crm','external_id'=>'required|string|max:150','name'=>'nullable|string|max:160','phone'=>['nullable','regex:/^\+[1-9][0-9]{7,14}$/D'],'email'=>'nullable|email|max:200','consent'=>'required|boolean','consent_evidence'=>'nullable|required_if:consent,true|string|min:5|max:1000','attribution'=>'present|array:ad_id,campaign_id,form_id,lead_id,source_url','attribution.*'=>'nullable|string|max:500']);return $this->idempotent($r,function($i)use($d){$old=DB::table('social_leads')->where('workspace_id',$i->workspace_id)->where('source',$d['source'])->where('external_id',$d['external_id'])->first();if($old)return ['id'=>$old->id,'duplicate'=>true];$contact=null;
  if(!empty($d['phone'])){$contact=DB::table('voice_contacts')->where('workspace_id',$i->workspace_id)->where('phone',$d['phone'])->value('id');if(!$contact)$contact=DB::table('voice_contacts')->insertGetId(['workspace_id'=>$i->workspace_id,'name'=>($d['name']??null)?:'Lead a identificar','phone'=>$d['phone'],'original_phone'=>$d['phone'],'source'=>$d['source'],'consent'=>$d['consent'],'consent_evidence'=>$d['consent']?$d['consent_evidence']:null,'consented_at'=>$d['consent']?now():null,'created_at'=>now(),'updated_at'=>now()]);}
  $id=(string)Str::uuid();DB::table('social_leads')->insert(array_replace($d,['id'=>$id,'workspace_id'=>$i->workspace_id,'contact_id'=>$contact,'status'=>'awaiting_review','attribution'=>json_encode($d['attribution']),'created_at'=>now(),'updated_at'=>now()]));app(IntegrationEvents::class)->emit($i->workspace_id,'lead.received',$id,'lead:'.$id,['source'=>$d['source'],'contact_id'=>$contact,'status'=>'awaiting_review']);return ['id'=>$id,'duplicate'=>false,'status'=>'awaiting_review'];});}
}
