<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Services\{VoiceLab,IntegrationEvents};
class SocialLeadController extends Controller {
 private function workspace(Request $r):int {abort_unless($r->user()->voice_workspace_id===1&&in_array($r->user()->voice_role,['admin','supervisor'],true),403);return 1;}
 public function index(Request $r){$w=$this->workspace($r);$d=$r->validate(['status'=>'nullable|in:awaiting_review,qualified,discarded','search'=>'nullable|string|max:80','page'=>'nullable|integer|between:1,10000']);$query=DB::table('social_leads as l')->leftJoin('voice_contacts as c',function($j){$j->on('c.id','=','l.contact_id')->on('c.workspace_id','=','l.workspace_id');})->where('l.workspace_id',$w);
  $query->when($d['status']??null,fn($q)=>$q->where('l.status',$d['status']))->when($d['search']??null,function($q)use($d){$term='%'.strtolower($d['search']).'%';$q->where(fn($q)=>$q->whereRaw('lower(l.name) like ?',[$term])->orWhere('l.phone','like',$term)->orWhere('l.external_id','like',$term));});
  return response()->json(['rows'=>$query->orderBy('l.created_at')->orderBy('l.id')->paginate(20,['l.*','c.suppressed_at','c.consent as contact_consent']),'agents'=>DB::table('users')->where('voice_workspace_id',$w)->where('voice_enabled',true)->get(['id','name']),'counts'=>DB::table('social_leads')->where('workspace_id',$w)->selectRaw('status,count(*) as total')->groupBy('status')->pluck('total','status')])->header('Cache-Control','no-store, private');
 }
 public function update(Request $r,string $id){$w=$this->workspace($r);$d=$r->validate(['revision'=>'required|integer|min:1','status'=>'required|in:awaiting_review,qualified,discarded','assigned_user_id'=>'nullable|integer','review_notes'=>'nullable|string|max:2000']);return DB::transaction(function()use($w,$r,$id,$d){DB::table('voice_runtime')->where('id',1)->lockForUpdate()->firstOrFail();$lead=DB::table('social_leads')->where('workspace_id',$w)->where('id',$id)->firstOrFail();abort_unless($lead->revision===$d['revision'],409,'Este lead foi atualizado. Atualize a lista antes de salvar.');if(isset($d['assigned_user_id']))DB::table('users')->where('voice_workspace_id',$w)->where('voice_enabled',true)->where('id',$d['assigned_user_id'])->firstOrFail();abort_if($d['status']==='discarded'&&!trim($d['review_notes']??''),422,'Informe o motivo do descarte nas observações.');$next=['status'=>$d['status'],'assigned_user_id'=>$d['assigned_user_id']??null,'review_notes'=>$d['review_notes']??null,'revision'=>$lead->revision+1,'reviewed_by'=>$r->user()->id,'reviewed_at'=>now(),'updated_at'=>now()];DB::table('social_leads')->where('id',$id)->update($next);app(VoiceLab::class)->audit($w,$r->user()->id,'lead.reviewed',$id,['status'=>$next['status'],'assigned_user_id'=>$next['assigned_user_id'],'revision'=>$next['revision']]);app(IntegrationEvents::class)->emit($w,'lead.reviewed',$id,'lead:'.$id.':revision:'.$next['revision'],['status'=>$next['status'],'assigned_user_id'=>$next['assigned_user_id'],'revision'=>$next['revision']]);return ['ok'=>true,'revision'=>$next['revision']];});}
}
