<?php
namespace Tests\Feature;
use App\Models\User;
use App\Services\{AgentAvailability,InboundVoice,ConversationInbox,TwilioVoiceCalling,TwilioVoiceConnection};
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Http};
use Illuminate\Support\Str;
use Tests\TestCase;
class AgentAvailabilityTest extends TestCase {
 use RefreshDatabase;private User $admin;private User $agent;private int $contact;private int $campaign;private int $a;private int $b;private string $session;
 protected function setUp():void {parent::setUp();Http::preventStrayRequests();$this->travelTo(now()->setDate(2026,10,5)->setTime(12,0));$this->admin=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'admin']);$this->agent=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'agent']);$this->session=(string)Str::uuid();$this->actingAs($this->agent);
  $this->contact=DB::table('voice_contacts')->insertGetId(['workspace_id'=>1,'name'=>'Pessoa QA','phone'=>'+5511999990001','original_phone'=>'+5511999990001','source'=>'QA','consent'=>true,'consent_evidence'=>'Autorização QA registrada']);
  $settings=['mode'=>'preview','business_number'=>'+12025550123','timezone'=>'UTC','days'=>[1,2,3,4,5,6,7],'start_time'=>'00:00','end_time'=>'23:59','max_attempts'=>5,'retry_minutes'=>1,'concurrency'=>1,'whatsapp_enabled'=>false,'whatsapp_delivery'=>'simulation'];$this->campaign=DB::table('voice_campaigns')->insertGetId(['workspace_id'=>1,'name'=>'Campanha QA','status'=>'testing','settings'=>json_encode($settings)]);DB::table('voice_members')->insert(['campaign_id'=>$this->campaign,'contact_id'=>$this->contact]);
  $this->a=$this->queue('mixed',$this->campaign);$this->b=$this->queue('outbound');
  config(['voice_calling_test'=>['allowed_recipients'=>['+5511999990001'],'daily_limit'=>20,'max_seconds'=>30,'ring_seconds'=>10,'caller_id_confirmed'=>true,'sip_username'=>'qa','sip_password'=>'fixture','event_secret'=>str_repeat('b',64)],'twilio_voice_test'=>['account_sid'=>'AC'.str_repeat('1',32),'api_key'=>'SK'.str_repeat('2',32),'api_secret'=>'fixture-api-secret','auth_token'=>'fixture-auth-token','application_sid'=>'AP'.str_repeat('3',32),'caller_id'=>'+12025550123','edge'=>'ashburn','enabled'=>true]]);
 }
 private function queue(string $direction,?int $campaign=null):int{return DB::table('voice_live_queues')->insertGetId(['workspace_id'=>1,'name'=>'Fila QA','direction'=>$direction,'campaign_id'=>$campaign,'agent_ids'=>json_encode([$this->agent->id]),'status'=>'running','mode'=>'preview','inbound_enabled'=>true,'manual_enabled'=>true]);}
 private function online(?array $ids=null){return $this->postJson('/api/voice/queues/presence',['status'=>'available','session_id'=>$this->session,'all_queues'=>$ids===null]+($ids===null?[]:['queue_ids'=>$ids]));}
 private function manual(array $d=[]){return $this->postJson('/api/voice/operations/manual-reservations',$d+['queue_id'=>$this->a,'number'=>'(11) 99999-0001','idempotency_key'=>(string)Str::uuid()]);}
 private function grant(array $r,array $extra=[]){return $this->postJson('/api/voice/calling/calls',$extra+['queue_reservation_id'=>$r['id'],'method'=>'programmable_voice','campaign_id'=>null,'contact_id'=>$this->contact,'idempotency_key'=>(string)Str::uuid(),'consent_confirmed'=>true,'consent_evidence'=>'Ligação manual autorizada']);}
 private function dial(array $g):string {return app(TwilioVoiceCalling::class)->dial($g['params']+['From'=>'client:'.TwilioVoiceConnection::identity($g['id']),'CallSid'=>'CA'.str_repeat('7',32)],config('twilio_voice_test'));}
 public function test_online_all_subset_and_pause_are_enforced_for_outbound_claims():void {
  $this->online()->assertNoContent();$this->assertTrue(AgentAvailability::available(1,$this->agent->id,$this->a));$this->assertTrue(AgentAvailability::available(1,$this->agent->id,$this->b));
  $this->online([$this->b])->assertNoContent();$this->postJson('/api/voice/operations/queues/'.$this->a.'/claim',['idempotency_key'=>(string)Str::uuid()])->assertConflict();$this->assertFalse(AgentAvailability::available(1,$this->agent->id,$this->a));
  $this->online()->assertNoContent();$this->postJson('/api/voice/operations/queues/'.$this->a.'/claim',['idempotency_key'=>(string)Str::uuid()])->assertOk()->assertJsonPath('reservation.campaign_id',$this->campaign);$this->postJson('/api/voice/queues/presence',['status'=>'paused','pause_reason'=>'Pausa QA','session_id'=>$this->session])->assertNoContent();$this->assertFalse(AgentAvailability::available(1,$this->agent->id,$this->a));Http::assertNothingSent();
 }
 public function test_cannot_select_unassigned_foreign_or_duplicate_queues():void {$foreign=$this->queue('inbound');DB::table('voice_live_queues')->where('id',$foreign)->update(['agent_ids'=>'[]']);$this->online([$foreign])->assertForbidden();$this->online([999999])->assertForbidden();$this->online([$this->a,$this->a])->assertUnprocessable();$this->assertDatabaseCount('voice_agent_presence',0);}
 public function test_other_tab_cannot_heartbeat_or_offline_the_owning_session():void {
  $this->online()->assertNoContent();$other=(string)Str::uuid();$this->postJson('/api/voice/queues/heartbeat',['session_id'=>$other])->assertConflict();$this->postJson('/api/voice/queues/presence',['status'=>'offline','session_id'=>$other])->assertConflict();$this->postJson('/api/voice/queues/heartbeat')->assertConflict();$this->postJson('/api/voice/queues/heartbeat',['session_id'=>$this->session])->assertNoContent();$this->assertDatabaseHas('voice_agent_presence',['user_id'=>$this->agent->id,'session_id'=>$this->session,'status'=>'available']);
  $this->travel(91)->seconds();$this->postJson('/api/voice/queues/heartbeat',['session_id'=>$other])->assertConflict();$this->postJson('/api/voice/queues/presence',['status'=>'available','session_id'=>$other,'all_queues'=>true])->assertNoContent();$this->postJson('/api/voice/queues/presence',['status'=>'offline','session_id'=>$this->session])->assertConflict();
 }
 public function test_manual_call_is_idempotent_and_never_becomes_a_campaign_attempt_or_whatsapp_followup():void {
  DB::table('voice_contacts')->where('id',$this->contact)->update(['replied_at'=>now()]);$reply=DB::table('voice_contacts')->find($this->contact)->replied_at;$this->online()->assertNoContent();$key=(string)Str::uuid();$r=$this->manual(['idempotency_key'=>$key])->assertOk()->json('reservation');$this->manual(['idempotency_key'=>$key])->assertJsonPath('reservation.id',$r['id']);$this->assertSame('manual',$r['kind']);$this->assertNull($r['campaign_id']);$this->getJson('/api/voice/operations/queues')->assertJsonPath('current.campaign_id',null)->assertJsonPath('current.kind','manual');
  $g=$this->grant($r)->assertOk()->json();$this->assertDatabaseHas('voice_outbound_calls',['id'=>$g['id'],'manual'=>true,'campaign_id'=>null,'queue_id'=>$this->a]);$this->assertStringContainsString('<Dial',$this->dial($g));app(TwilioVoiceCalling::class)->apply($g['id'],config('twilio_voice_test.account_sid'),'CA'.str_repeat('7',32),'CA'.str_repeat('8',32),'no-answer',0);$this->assertDatabaseCount('voice_followups',0);$this->assertDatabaseCount('wa_messages',0);$this->assertDatabaseHas('voice_contacts',['id'=>$this->contact,'replied_at'=>$reply]);$this->assertDatabaseHas('voice_live_reservations',['id'=>$r['id'],'status'=>'completed']);Http::assertNothingSent();
 }
 public function test_manual_dial_cannot_bypass_queue_permission_presence_pause_or_allowlist():void {
  $this->online([$this->b])->assertNoContent();$this->manual()->assertConflict();$this->online()->assertNoContent();DB::table('voice_live_queues')->where('id',$this->a)->update(['manual_enabled'=>false]);$this->manual()->assertForbidden();DB::table('voice_live_queues')->where('id',$this->a)->update(['manual_enabled'=>true,'status'=>'paused']);DB::table('voice_live_queues')->where('id',$this->a)->update(['status'=>'running']);$this->manual(['number'=>'+5511888880000'])->assertUnprocessable();$this->assertDatabaseCount('voice_live_reservations',0);Http::assertNothingSent();
 }
 public function test_manual_contact_requires_consent_and_optout_still_blocks():void {$this->online()->assertNoContent();DB::table('voice_contacts')->where('id',$this->contact)->update(['suppressed_at'=>now()]);$this->manual()->assertUnprocessable();DB::table('voice_contacts')->where('id',$this->contact)->update(['suppressed_at'=>null,'consent'=>false]);$this->manual()->assertUnprocessable();$this->assertDatabaseCount('voice_outbound_calls',0);}
 public function test_manual_reservation_cannot_be_repurposed_for_campaign_or_different_method():void {$this->online()->assertNoContent();$r=$this->manual()->assertOk()->json('reservation');$this->grant($r,['campaign_id'=>$this->campaign])->assertConflict();$this->grant($r,['method'=>'sip_trunk'])->assertStatus(503);$this->assertDatabaseCount('voice_outbound_calls',0);}
 public function test_pausing_queue_selection_after_grant_blocks_manual_provider_dial():void {$this->online()->assertNoContent();$r=$this->manual()->assertOk()->json('reservation');$g=$this->grant($r)->assertOk()->json();$this->online([$this->b])->assertNoContent();$this->assertStringNotContainsString('<Dial',$this->dial($g));$this->assertDatabaseHas('voice_outbound_calls',['id'=>$g['id'],'status'=>'pending']);Http::assertNothingSent();}
 public function test_manual_reservation_blocks_campaign_claim_and_second_manual_call():void {$this->online()->assertNoContent();$this->manual()->assertOk();$this->manual()->assertConflict();$this->postJson('/api/voice/operations/queues/'.$this->a.'/claim',['idempotency_key'=>(string)Str::uuid()])->assertConflict();$this->assertDatabaseCount('voice_live_reservations',1);}
 public function test_selected_queues_control_inbound_offers_and_whatsapp_distribution():void {
  $this->online([$this->b])->assertNoContent();DB::table('voice_inbound_routes')->insert(['workspace_id'=>1,'number'=>'+12025550123','queue_id'=>$this->a,'enabled'=>true,'ring_seconds'=>20,'wait_seconds'=>120]);DB::table('voice_inbound_devices')->insert(['user_id'=>$this->agent->id,'workspace_id'=>1,'session_id'=>$this->session,'identity'=>'qa-agent','ready'=>true,'last_seen_at'=>now()]);$d=['AccountSid'=>config('twilio_voice_test.account_sid'),'CallSid'=>'CA'.str_repeat('a',32),'From'=>'+5511999990001','To'=>'+12025550123'];$this->assertStringNotContainsString('<Client',app(InboundVoice::class)->receive($d));$this->assertDatabaseCount('voice_inbound_offers',0);
  $sender=DB::table('wa_senders')->insertGetId(['workspace_id'=>1,'provider'=>'qr','label'=>'QA','number'=>'+5511000000000','ownership'=>'external']);DB::table('wa_inbox_routes')->insert(['workspace_id'=>1,'sender_id'=>$sender,'queue_id'=>$this->a,'enabled'=>true,'max_open'=>5]);$c=(string)Str::uuid();DB::table('wa_conversations')->insert(['id'=>$c,'workspace_id'=>1,'sender_id'=>$sender,'queue_id'=>$this->a,'phone'=>'+5511999990001','status'=>'open']);app(ConversationInbox::class)->distribute($c);$this->assertDatabaseHas('wa_conversations',['id'=>$c,'assigned_user_id'=>null]);$this->online()->assertNoContent();app(ConversationInbox::class)->distribute($c);$this->assertDatabaseHas('wa_conversations',['id'=>$c,'assigned_user_id'=>$this->agent->id]);$call=DB::table('voice_inbound_calls')->first();$this->assertStringContainsString('<Client',app(InboundVoice::class)->dispatch($call->id,$d['CallSid']));Http::assertNothingSent();
 }

 public function test_manual_can_run_with_cadences_paused_without_activating_them():void {$this->online()->assertNoContent();DB::table('voice_live_queues')->where('id',$this->a)->update(['status'=>'paused']);$r=$this->manual()->assertOk()->json('reservation');$g=$this->grant($r)->assertOk()->json();$this->assertStringContainsString('<Dial',$this->dial($g));$this->assertDatabaseHas('voice_live_queues',['id'=>$this->a,'status'=>'paused']);Http::assertNothingSent();}
 public function test_queue_destination_permissions_apply_to_manual_progressive_and_provider_recheck():void {
 $this->online()->assertNoContent();DB::table('voice_live_queues')->where('id',$this->a)->update(['allow_mobile'=>false]);$this->manual()->assertUnprocessable();$this->postJson('/api/voice/operations/queues/'.$this->a.'/claim',['idempotency_key'=>(string)Str::uuid()])->assertOk()->assertJsonPath('reservation',null);
 DB::table('voice_live_queues')->where('id',$this->a)->update(['allow_mobile'=>true]);$r=$this->manual()->assertOk()->json('reservation');$g=$this->grant($r)->assertOk()->json();DB::table('voice_live_queues')->where('id',$this->a)->update(['allow_mobile'=>false]);$this->assertStringNotContainsString('<Dial',$this->dial($g));Http::assertNothingSent();
 }
 public function test_landline_classification_and_queue_admin_permissions():void {
 $q=(object)['allow_mobile'=>false,'allow_landline'=>true];$this->assertNull(\App\Services\QueueDestinations::reason($q,'+551132345678'));$this->assertNotNull(\App\Services\QueueDestinations::reason($q,'+5511999990001'));$q->allow_landline=false;$this->assertNotNull(\App\Services\QueueDestinations::reason($q,'+551332345678'));$this->assertNotNull(\App\Services\QueueDestinations::reason($q,'+551188888888'));$this->assertNull(\App\Services\QueueDestinations::reason($q,'+12025550123'));
 $this->actingAs($this->admin);DB::table('voice_live_queues')->where('id',$this->a)->update(['status'=>'paused']);$this->putJson('/api/voice/operations/queues/'.$this->a,['name'=>'QA','direction'=>'mixed','campaign_ids'=>[$this->campaign],'agent_ids'=>[$this->agent->id],'mode'=>'preview','strategy'=>'fifo','wrapup_seconds'=>0,'revision'=>0,'allow_mobile'=>false,'allow_landline'=>true])->assertOk();$this->assertDatabaseHas('voice_live_queues',['id'=>$this->a,'allow_mobile'=>false,'allow_landline'=>true]);
 }
}
