<?php
namespace Tests\Feature;
use App\Models\User;
use App\Services\{CadenceReentry,VoiceEligibility,VoiceFollowups,VoiceCalling,ListContacts};
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Http,Queue};
use Illuminate\Support\Str;
use Tests\TestCase;
class CadenceReentryTest extends TestCase {
 use RefreshDatabase;
 private User $user;private int $campaign;private int $contact;private int $list;private array $s;
 protected function setUp():void {parent::setUp();Http::preventStrayRequests();Queue::fake();$this->travelTo(now()->setDate(2026,10,6)->setTime(12,0));$this->user=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'admin']);$this->actingAs($this->user);$p=app(\App\Services\VoiceJourneyPreset::class)->create(1,$this->user->id,'+12025550123');$this->campaign=$p['campaign_id'];$this->list=$p['list_id'];$this->contact=app(ListContacts::class)->ingest(1,'voice',$this->list,['name'=>'Ana','phone'=>'+5511999990001','source'=>'QA','consent'=>true,'consent_evidence'=>'Teste interno autorizado','fields'=>[]])['contact_id'];$this->s=json_decode($this->c()->settings,true);$this->s=array_replace($this->s,['whatsapp_enabled'=>false,'max_attempts'=>1,'timezone'=>'UTC','days'=>[1,2,3,4,5,6,7],'start_time'=>'00:00','end_time'=>'23:59']);$this->configure();}
 private function c():object {return DB::table('voice_campaigns')->find($this->campaign);}
 private function service():CadenceReentry{return app(CadenceReentry::class);}
 private function configure(string $mode='once',array $extra=[]):void {$this->s['reentry']=array_replace(CadenceReentry::DEFAULTS,['mode'=>$mode,'interval_days'=>1],$extra);DB::table('voice_campaigns')->where('id',$this->campaign)->update(['settings'=>json_encode($this->s),'status'=>'testing']);}
 private function tick():void {$this->service()->tick();}
 private function activeRun():?object{return $this->service()->current($this->campaign,$this->contact);}
 private function close(string $reason='attempts_exhausted'):object{$r=$this->activeRun();$this->service()->finish($r,$reason);return $r;}
 private function recordCall(?string $run,string $status='no_answer'):string {$id=(string)Str::uuid();DB::table('voice_outbound_calls')->insert(['id'=>$id,'run_id'=>$run,'workspace_id'=>1,'campaign_id'=>$this->campaign,'campaign_revision'=>$this->c()->followup_revision,'contact_id'=>$this->contact,'user_id'=>$this->user->id,'idempotency_key'=>(string)Str::uuid(),'request_hash'=>'qa','grant_hash'=>hash('sha256',$id),'configuration_hash'=>'qa','destination'=>'+5511999990001','caller_id'=>'+12025550123','status'=>$status,'max_seconds'=>30,'ring_seconds'=>10,'consent_evidence'=>'QA autorizado','grant_expires_at'=>now(),'deadline_at'=>now(),'started_at'=>now()->subMinutes(3),'ended_at'=>now(),'capacity_released_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);return $id;}
 public function test_once_preserves_segment_and_never_restarts():void {$this->tick();$r=$this->activeRun();$this->assertSame(1,$r->number);$this->recordCall($r->id,'completed');$this->tick();$this->tick();$this->assertNull($this->activeRun());$this->assertDatabaseCount('voice_cadence_runs',1);$this->assertDatabaseHas('voice_cadence_runs',['id'=>$r->id,'exit_reason'=>'answered']);$this->assertDatabaseHas('voice_list_members',['list_id'=>$this->list,'contact_id'=>$this->contact,'status'=>'active']);Http::assertNothingSent();Queue::assertNothingPushed();}
 public function test_interval_resets_only_execution_attempts_and_honors_total_participations():void {$this->configure('interval',['max_participations'=>2]);$this->tick();$first=$this->activeRun();$this->recordCall($first->id);$this->tick();$this->assertNull($this->activeRun());$this->travel(23)->hours();$this->tick();$this->assertNull($this->activeRun());$this->travel(2)->hours();$this->tick();$next=$this->activeRun();$this->assertSame(2,$next->number);$this->assertNotSame($first->id,$next->id);$reason=app(VoiceEligibility::class)->reason(1,$this->c(),DB::table('voice_contacts')->find($this->contact));$this->assertNull($reason);$this->recordCall($next->id);$this->tick();$this->travel(2)->days();$this->tick();$this->assertDatabaseCount('voice_cadence_runs',2);$this->assertDatabaseCount('voice_outbound_calls',2);}
 public function test_return_requires_real_membership_edge_even_between_scheduler_ticks():void {$this->configure('segment_return');$this->tick();$this->close();$this->tick();$this->assertDatabaseCount('voice_cadence_runs',1);$member=DB::table('voice_list_members')->where('list_id',$this->list)->where('contact_id',$this->contact)->value('id');app(\App\Services\VoiceLists::class)->member(1,$this->user->id,$member,'removed','QA');app(\App\Services\VoiceLists::class)->member(1,$this->user->id,$member,'active','QA');$this->tick();$this->assertSame(2,$this->activeRun()->number);$this->tick();$this->assertDatabaseCount('voice_cadence_runs',2);}
 public function test_source_departure_ends_run_but_does_not_delete_history():void {$this->configure('segment_return');$this->tick();$r=$this->activeRun();app(ListContacts::class)->remove(1,'voice',$this->list,$this->contact);$this->assertDatabaseHas('voice_cadence_runs',['id'=>$r->id,'exit_reason'=>'source_left','status'=>'completed']);$this->tick();$this->assertNull($this->activeRun());}
 public function test_event_deduplication_busy_event_is_not_queued_and_preview_has_no_writes():void {$this->configure('event');$preview=$this->service()->event(1,$this->campaign,$this->contact,'order:1',true);$this->assertTrue($preview['eligible']);$this->assertDatabaseCount('voice_cadence_runs',0);$this->assertDatabaseCount('voice_cadence_membership',0);$this->assertDatabaseCount('voice_cadence_events',0);$a=$this->service()->event(1,$this->campaign,$this->contact,'order:1');$this->assertTrue($a['eligible']);$b=$this->service()->event(1,$this->campaign,$this->contact,'order:1');$this->assertTrue($b['duplicate']);$this->assertSame($a['run_id'],$b['run_id']);$busy=$this->service()->event(1,$this->campaign,$this->contact,'order:2');$this->assertFalse($busy['eligible']);$this->close();$again=$this->service()->event(1,$this->campaign,$this->contact,'order:2');$this->assertFalse($again['eligible']);$this->assertTrue($again['duplicate']);$this->assertTrue($this->service()->event(1,$this->campaign,$this->contact,'order:3')['eligible']);$this->assertDatabaseCount('voice_cadence_runs',2);Http::assertNothingSent();}
 public function test_policy_limits_consent_and_exit_reason_are_enforced():void {$this->configure('interval');$this->tick();$this->close('answered');$this->travel(10)->days();$this->tick();$this->assertNull($this->activeRun());$this->configure('interval',['exit_reasons'=>['answered']]);DB::table('voice_contacts')->where('id',$this->contact)->update(['suppressed_at'=>now()]);$this->tick();$this->assertNull($this->activeRun());$this->assertDatabaseCount('voice_cadence_runs',1);}
 public function test_reply_baseline_does_not_erase_global_reply_and_new_reply_blocks_cycle():void {$this->configure('event',['exit_reasons'=>['replied']]);$a=$this->service()->event(1,$this->campaign,$this->contact,'first');DB::table('voice_contacts')->where('id',$this->contact)->update(['replied_at'=>now()]);$this->tick();$this->assertNull($this->activeRun());$this->travel(1)->hours();$b=$this->service()->event(1,$this->campaign,$this->contact,'second');$this->assertTrue($b['eligible']);$person=DB::table('voice_contacts')->find($this->contact);$this->assertNotNull($person->replied_at);$this->assertFalse($this->service()->replyBlocks($person,$b['run_id']));$this->assertTrue($this->service()->replyBlocks($person,null));app(VoiceCalling::class)->contact(1,$this->contact,false,$b['run_id']);$this->travel(1)->seconds();DB::table('voice_contacts')->where('id',$this->contact)->update(['replied_at'=>now()]);$this->tick();$this->assertNull($this->activeRun());}
 public function test_historical_adoption_keeps_answered_and_attempts_in_first_cycle():void {$this->configure('segment_return',['exit_reasons'=>['answered']]);$call=$this->recordCall(null,'completed');$this->tick();$this->assertDatabaseCount('voice_cadence_runs',1);$r=DB::table('voice_cadence_runs')->first();$this->assertSame('legacy',$r->trigger);$this->assertSame('answered',$r->exit_reason);$this->assertDatabaseHas('voice_outbound_calls',['id'=>$call,'run_id'=>$r->id]);$this->assertNull($this->activeRun());$this->tick();$this->assertDatabaseCount('voice_cadence_runs',1);}
 public function test_paused_campaign_never_enrolls_and_event_respects_workspace():void {$this->configure('event');DB::table('voice_campaigns')->where('id',$this->campaign)->update(['status'=>'paused']);$this->assertFalse($this->service()->event(1,$this->campaign,$this->contact,'paused')['eligible']);$this->tick();$this->assertDatabaseCount('voice_cadence_runs',0);DB::table('voice_workspaces')->insert(['id'=>2,'name'=>'Other']);$this->user->forceFill(['voice_workspace_id'=>2])->save();$this->getJson('/api/voice/journeys/'.$this->campaign.'/executions')->assertNotFound();}
 public function test_agent_cannot_manage_or_preview_reentry():void {$this->user->forceFill(['voice_role'=>'agent'])->save();$this->getJson('/api/voice/journeys/'.$this->campaign.'/executions')->assertForbidden();$this->postJson('/api/voice/journeys/'.$this->campaign.'/entries/preview',['contact_id'=>$this->contact,'event_key'=>'test'])->assertForbidden();}
 public function test_unknown_call_prevents_completion_and_another_cycle():void {$this->configure('interval');$this->tick();$r=$this->activeRun();$this->recordCall($r->id,'unknown');$this->travel(40)->days();$this->tick();$this->assertSame($r->id,$this->activeRun()->id);$this->assertDatabaseCount('voice_cadence_runs',1);}
 public function test_followup_uniqueness_and_threshold_are_per_cycle():void {$sender=DB::table('wa_senders')->insertGetId(['workspace_id'=>1,'label'=>'QR QA','number'=>'+5511999990000','ownership'=>'external','provider'=>'qr']);$this->s=array_replace($this->s,['whatsapp_enabled'=>true,'whatsapp_delivery'=>'automatic','whatsapp_after'=>1,'whatsapp_delay'=>0,'whatsapp_sender_id'=>$sender,'number_mode'=>'separate','whatsapp_number'=>'+5511999990000','whatsapp_text'=>'Oi {nome}']);$this->configure('event',['exit_reasons'=>['no_response']]);$a=$this->service()->event(1,$this->campaign,$this->contact,'one');$call=$this->recordCall($a['run_id']);app(VoiceFollowups::class)->observe($call);app(VoiceFollowups::class)->observe($call);$this->assertDatabaseCount('voice_followups',1);$f=DB::table('voice_followups')->first();$this->assertSame($a['run_id'],$f->run_id);$this->close('no_response');$b=$this->service()->event(1,$this->campaign,$this->contact,'two');$call=$this->recordCall($b['run_id']);app(VoiceFollowups::class)->observe($call);$this->assertDatabaseCount('voice_followups',2);$this->assertDatabaseHas('voice_followups',['run_id'=>$b['run_id'],'status'=>'pending']);Http::assertNothingSent();}
 public function test_global_attempt_limit_is_not_reset_by_reentry():void {$this->configure('interval');DB::table('voice_campaign_policies')->where('campaign_id',$this->campaign)->update(['global_total'=>1]);$this->tick();$this->recordCall($this->activeRun()->id);$this->tick();$this->travel(2)->days();$this->tick();$this->assertNotNull($this->activeRun());$this->assertStringContainsString('Limite acumulado',app(VoiceEligibility::class)->reason(1,$this->c(),DB::table('voice_contacts')->find($this->contact)));}
 public function test_invalid_reentry_settings_are_rejected():void {$this->expectException(\Illuminate\Validation\ValidationException::class);$this->service()->validate(array_replace(CadenceReentry::DEFAULTS,['mode'=>'anything','interval_days'=>0,'max_participations'=>0]));}

 public function test_entry_card_saves_validated_policy_and_preserves_it_in_other_editors():void {
  DB::table('voice_campaigns')->where('id',$this->campaign)->update(['status'=>'paused']);$p=array_replace(CadenceReentry::DEFAULTS,['mode'=>'interval','interval_days'=>7]);
  $this->putJson('/api/voice/journeys/'.$this->campaign.'/nodes/entry',['revision'=>$this->c()->revision,'config'=>['list_kind'=>'voice','list_id'=>$this->list,'reentry'=>$p]])->assertOk()->assertJsonPath('journey.settings.reentry.interval_days',7);
  $this->assertDatabaseCount('voice_cadence_runs',0);
  $this->putJson('/api/voice/journeys/'.$this->campaign.'/nodes/entry',['revision'=>$this->c()->revision,'config'=>['list_id'=>null,'reentry'=>array_replace($p,['mode'=>'segment_return'])]])->assertUnprocessable();
  $this->postJson('/api/voice/journeys/'.$this->campaign.'/entries/preview',['contact_id'=>$this->contact,'event_key'=>'qa'])->assertOk()->assertJsonPath('eligible',false);
 }
 public function test_sent_message_waits_for_response_but_unknown_never_auto_reenters():void {
  $this->configure('interval',['reply_wait_hours'=>2]);$this->tick();$r=$this->activeRun();$call=$this->recordCall($r->id);$sender=DB::table('wa_senders')->insertGetId(['workspace_id'=>1,'label'=>'QA','number'=>'+5511999990000','ownership'=>'external','provider'=>'qr']);$mid=(string)Str::uuid();
  DB::table('wa_messages')->insert(['id'=>$mid,'run_id'=>$r->id,'workspace_id'=>1,'sender_id'=>$sender,'contact_id'=>$this->contact,'campaign_id'=>$this->campaign,'direction'=>'outbound','idempotency_key'=>'qa','request_hash'=>'qa','account_sid'=>'QR','from_number'=>'+5511999990000','to_number'=>'+5511999990001','status'=>'unknown','created_at'=>now(),'updated_at'=>now()]);
  DB::table('voice_followups')->insert(['id'=>(string)Str::uuid(),'run_id'=>$r->id,'cycle_key'=>$r->id,'workspace_id'=>1,'campaign_id'=>$this->campaign,'contact_id'=>$this->contact,'user_id'=>$this->user->id,'call_id'=>$call,'campaign_revision'=>0,'settings'=>json_encode($this->s),'destination'=>'+5511999990001','status'=>'unknown','message_id'=>$mid,'due_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);
  $this->travel(5)->hours();$this->tick();$this->assertSame($r->id,$this->activeRun()->id);
  DB::table('wa_messages')->where('id',$mid)->update(['status'=>'sent']);DB::table('voice_followups')->where('run_id',$r->id)->update(['status'=>'sent']);$this->tick();$this->assertSame('waiting',$this->activeRun()->status);$this->travel(1)->hours();$this->tick();$this->assertNotNull($this->activeRun());$this->travel(2)->hours();$this->tick();$this->assertNull($this->activeRun());$this->assertDatabaseHas('voice_cadence_runs',['id'=>$r->id,'exit_reason'=>'no_response']);Http::assertNothingSent();
 }
 public function test_open_whatsapp_conversation_blocks_reentry_after_reply():void {
  $this->configure('event',['exit_reasons'=>['replied']]);$this->service()->event(1,$this->campaign,$this->contact,'first');DB::table('voice_contacts')->where('id',$this->contact)->update(['replied_at'=>now()]);$this->tick();
  $sender=DB::table('wa_senders')->insertGetId(['workspace_id'=>1,'label'=>'QA','number'=>'+5511999990000','ownership'=>'external','provider'=>'qr']);DB::table('wa_conversations')->insert(['id'=>(string)Str::uuid(),'workspace_id'=>1,'sender_id'=>$sender,'contact_id'=>$this->contact,'phone'=>'+5511999990001','status'=>'open','last_inbound_at'=>now()]);
  $this->assertFalse($this->service()->event(1,$this->campaign,$this->contact,'second')['eligible']);DB::table('wa_conversations')->update(['status'=>'closed']);$this->assertTrue($this->service()->event(1,$this->campaign,$this->contact,'third')['eligible']);
 }
 public function test_public_event_requires_scope_and_segment_access_and_is_idempotent():void {
  $this->configure('event');$token='mai_'.str_repeat('a',64);$id=(string)Str::uuid();DB::table('ma_integrations')->insert(['id'=>$id,'workspace_id'=>1,'created_by'=>$this->user->id,'name'=>'QA','token_hash'=>hash('sha256',$token),'webhook_secret'=>'qa-encrypted-unused','scopes'=>'["lists:write"]','list_keys'=>'[]','agent_ids'=>'[]','active'=>true]);$headers=['Authorization'=>'Bearer '.$token,'Idempotency-Key'=>(string)Str::uuid()];$url='/api/v1/journeys/'.$this->campaign.'/entries';$d=['contact_id'=>$this->contact,'event_key'=>'order:1'];
  $this->postJson($url,$d,$headers)->assertForbidden();DB::table('ma_integrations')->where('id',$id)->update(['scopes'=>'["journeys:write"]']);$this->postJson($url,$d,$headers)->assertForbidden();DB::table('ma_integrations')->where('id',$id)->update(['list_keys'=>json_encode(['voice:'.$this->list])]);$this->postJson($url,$d,$headers)->assertOk()->assertJsonPath('eligible',true);$this->postJson($url,$d,$headers)->assertOk()->assertJsonPath('participation',1);$this->assertDatabaseCount('voice_cadence_runs',1);$this->postJson($url,array_replace($d,['event_key'=>'different']),$headers)->assertConflict();Http::assertNothingSent();
 }
 public function test_reply_attribution_is_execution_specific_and_ambiguous_text_is_not_misattributed():void {
  $this->configure('event');$a=$this->service()->event(1,$this->campaign,$this->contact,'one');$this->close();$b=$this->service()->event(1,$this->campaign,$this->contact,'two');$sender=DB::table('wa_senders')->insertGetId(['workspace_id'=>1,'label'=>'QA','number'=>'+5511999990000','ownership'=>'external','provider'=>'qr']);
  foreach([$a['run_id'],$b['run_id']]as $index=>$run)DB::table('wa_messages')->insert(['id'=>(string)Str::uuid(),'run_id'=>$run,'workspace_id'=>1,'sender_id'=>$sender,'contact_id'=>$this->contact,'campaign_id'=>$this->campaign,'provider'=>'qr','direction'=>'outbound','idempotency_key'=>'out'.$index,'request_hash'=>'qa','account_sid'=>'QR','provider_reference'=>'reference'.$index,'from_number'=>'+5511999990000','to_number'=>'+5511999990001','status'=>'read','created_at'=>now()->subMinute()]);
  $mid=(string)Str::uuid();DB::table('wa_messages')->insert(['id'=>$mid,'workspace_id'=>1,'sender_id'=>$sender,'contact_id'=>$this->contact,'provider'=>'qr','direction'=>'inbound','idempotency_key'=>'in','request_hash'=>'qa','account_sid'=>'QR','from_number'=>'+5511999990001','to_number'=>'+5511999990000','status'=>'received','created_at'=>now()]);app(\App\Services\JourneyReplyAttribution::class)->record($mid);$this->assertDatabaseHas('wa_messages',['id'=>$mid,'reply_attribution'=>'unattributed','run_id'=>null]);DB::table('wa_messages')->where('id',$mid)->update(['reply_attribution'=>null,'interactive'=>json_encode(['context_id'=>'reference0'])]);app(\App\Services\JourneyReplyAttribution::class)->record($mid);$this->assertDatabaseHas('wa_messages',['id'=>$mid,'run_id'=>$a['run_id']]);
 }
}
