<?php
namespace Tests\Feature;
use App\Models\User;
use App\Services\ConversationInbox;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Http};
use Illuminate\Support\Str;
use Tests\TestCase;
class ConversationInboxTest extends TestCase {
 use RefreshDatabase;private User $user;private int $sender;private int $contact;
 protected function setUp():void{parent::setUp();Http::preventStrayRequests();$this->user=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'admin']);$this->actingAs($this->user);$this->sender=DB::table('wa_senders')->insertGetId(['workspace_id'=>1,'provider'=>'qr','label'=>'QA','number'=>'+5511000000000','ownership'=>'external']);$this->contact=DB::table('voice_contacts')->insertGetId(['workspace_id'=>1,'name'=>'Pessoa QA','phone'=>'+5511999990000','original_phone'=>'+5511999990000','source'=>'QA','consent'=>true,'consent_evidence'=>'Authorized test','replied_at'=>now()]);config(['whatsapp_qr_test'=>['token'=>str_repeat('a',32),'url'=>'http://qr.test','allowed_recipients'=>['+5511999990000'],'daily_limit'=>10]]);}
 private function inbound():string{$id=(string)Str::uuid();DB::table('wa_messages')->insert(['id'=>$id,'workspace_id'=>1,'sender_id'=>$this->sender,'contact_id'=>$this->contact,'direction'=>'inbound','provider'=>'qr','idempotency_key'=>$id,'request_hash'=>hash('sha256',$id),'account_sid'=>'qr:'.$this->sender,'from_number'=>'+5511999990000','to_number'=>'+5511000000000','status'=>'received','body'=>'Olá','created_at'=>now(),'updated_at'=>now()]);return $id;}
 private function conversation():string{$id=app(ConversationInbox::class)->record($this->inbound());DB::table('wa_conversations')->where('id',$id)->update(['assigned_user_id'=>$this->user->id]);return $id;}
 public function test_inbound_is_idempotent_and_manual_reply_does_not_reset_cadence_stop():void{$m=$this->inbound();$id=app(ConversationInbox::class)->record($m);$this->assertSame($id,app(ConversationInbox::class)->record($m));$this->assertDatabaseCount('wa_conversations',1);DB::table('wa_conversations')->where('id',$id)->update(['assigned_user_id'=>$this->user->id]);Http::fake(['http://qr.test/sessions/*/messages'=>Http::response(['status'=>'sent','reference'=>'qa-message']), 'http://qr.test/sessions/*'=>Http::response(['status'=>'connected','number'=>'+5511000000000','capabilities'=>['experimental_buttons'=>true]])]);$d=['idempotency_key'=>(string)Str::uuid(),'body'=>'Como podemos ajudar?'];$this->postJson('/api/voice/conversations/'.$id.'/send',$d)->assertOk()->assertJsonPath('status','sent');$this->postJson('/api/voice/conversations/'.$id.'/send',$d)->assertOk();Http::assertSentCount(2);$this->assertNotNull(DB::table('voice_contacts')->find($this->contact)->replied_at);$this->assertDatabaseCount('wa_messages',2);}
 public function test_optout_expired_window_and_other_assignee_cannot_send():void{$id=$this->conversation();$d=['idempotency_key'=>(string)Str::uuid(),'body'=>'Teste'];DB::table('voice_contacts')->where('id',$this->contact)->update(['suppressed_at'=>now()]);$this->postJson('/api/voice/conversations/'.$id.'/send',$d)->assertUnprocessable();DB::table('voice_contacts')->where('id',$this->contact)->update(['suppressed_at'=>null]);$this->travel(25)->hours();$this->postJson('/api/voice/conversations/'.$id.'/send',$d)->assertUnprocessable();DB::table('wa_conversations')->where('id',$id)->update(['last_inbound_at'=>now(),'assigned_user_id'=>null]);$this->postJson('/api/voice/conversations/'.$id.'/send',$d)->assertConflict();Http::assertNothingSent();}
 public function test_agent_visibility_and_assignment_race():void{$id=$this->conversation();$agent=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'agent']);$this->actingAs($agent)->getJson('/api/voice/conversations/'.$id)->assertNotFound();$this->getJson('/api/voice/conversations')->assertOk()->assertJsonPath('rows.total',0);$this->postJson('/api/voice/conversations/routes',[])->assertForbidden();$this->actingAs($this->user)->postJson('/api/voice/conversations/'.$id.'/assign',['user_id'=>$this->user->id,'queue_id'=>null,'status'=>'closed','revision'=>1])->assertOk();$this->postJson('/api/voice/conversations/'.$id.'/assign',['user_id'=>$this->user->id,'queue_id'=>null,'status'=>'open','revision'=>1])->assertConflict();}
 public function test_automatic_distribution_requires_available_member_and_obeys_open_limit():void{$c=DB::table('voice_campaigns')->insertGetId(['workspace_id'=>1,'name'=>'QA','settings'=>'{}']);$q=DB::table('voice_live_queues')->insertGetId(['workspace_id'=>1,'campaign_id'=>$c,'name'=>'QA','agent_ids'=>json_encode([$this->user->id])]);DB::table('wa_inbox_routes')->insert(['workspace_id'=>1,'sender_id'=>$this->sender,'queue_id'=>$q,'enabled'=>true,'max_open'=>1]);$id=app(ConversationInbox::class)->record($this->inbound());$this->assertDatabaseHas('wa_conversations',['id'=>$id,'assigned_user_id'=>null]);DB::table('voice_agent_presence')->insert(['workspace_id'=>1,'user_id'=>$this->user->id,'status'=>'available','last_seen_at'=>now()]);app(ConversationInbox::class)->distribute($id);$this->assertDatabaseHas('wa_conversations',['id'=>$id,'assigned_user_id'=>$this->user->id]);}
}
