<?php
namespace Tests\Feature;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Http};
use Illuminate\Support\Str;
use Tests\TestCase;
class NextMilestonesTest extends TestCase {
 use RefreshDatabase;
 private User $admin;
 protected function setUp():void {parent::setUp();Http::preventStrayRequests();$this->admin=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'admin']);$this->actingAs($this->admin);}
 private function lead(array $d=[]):string{$id=(string)Str::uuid();DB::table('social_leads')->insert($d+['id'=>$id,'workspace_id'=>1,'source'=>'form','attribution'=>'{}','external_id'=>$id,'name'=>'Ana','consent'=>false,'created_at'=>now(),'updated_at'=>now()]);return $id;}
 public function test_review_preserves_opt_out_and_emits_one_versioned_event_without_contacting_anyone():void {$contact=DB::table('voice_contacts')->insertGetId(['workspace_id'=>1,'name'=>'Ana','phone'=>'+5511999991111','original_phone'=>'+5511999991111','source'=>'QA','consent'=>false,'suppressed_at'=>now()]);$id=$this->lead(['contact_id'=>$contact]);$before=DB::table('voice_contacts')->where('id',$contact)->first();$data=['revision'=>1,'status'=>'qualified','assigned_user_id'=>$this->admin->id,'review_notes'=>'Revisar origem'];$this->putJson('/api/voice/leads/'.$id,$data)->assertOk()->assertJsonPath('revision',2);$this->putJson('/api/voice/leads/'.$id,$data)->assertConflict();$this->assertEquals($before,DB::table('voice_contacts')->where('id',$contact)->first());$this->assertDatabaseCount('ma_public_events',1);$this->assertDatabaseCount('wa_messages',0);$this->assertDatabaseCount('voice_outbound_calls',0);$this->getJson('/api/voice/leads?status=qualified&search=Ana')->assertOk()->assertJsonPath('rows.total',1)->assertJsonPath('rows.data.0.revision',2);Http::assertNothingSent();}
 public function test_review_requires_reason_and_cannot_assign_outside_workspace_or_disabled_user():void {$id=$this->lead();$this->putJson('/api/voice/leads/'.$id,['revision'=>1,'status'=>'discarded'])->assertUnprocessable();$u=User::factory()->create(['voice_workspace_id'=>1,'voice_enabled'=>false]);$this->putJson('/api/voice/leads/'.$id,['revision'=>1,'status'=>'qualified','assigned_user_id'=>$u->id])->assertNotFound();$this->putJson('/api/voice/leads/'.$id,['revision'=>1,'status'=>'discarded','review_notes'=>'Cadastro duplicado'])->assertOk();$this->assertDatabaseHas('social_leads',['id'=>$id,'status'=>'discarded']);}
 public function test_supervisor_can_review_but_agent_cannot_see_leads_or_reports():void {$id=$this->lead();$this->admin->forceFill(['voice_role'=>'supervisor'])->save();$this->getJson('/api/voice/leads')->assertOk();$this->putJson('/api/voice/leads/'.$id,['revision'=>1,'status'=>'qualified'])->assertOk();$this->admin->forceFill(['voice_role'=>'agent'])->save();foreach(['/api/voice/leads','/api/voice/health/diagnostics','/api/voice/inbound/reports?from=2026-10-01&to=2026-10-05']as $url)$this->getJson($url)->assertForbidden();$this->putJson('/api/voice/leads/'.$id,['revision'=>2,'status'=>'qualified'])->assertForbidden();}
 private function inbound(array $d=[]):string{$campaign=DB::table('voice_campaigns')->insertGetId(['workspace_id'=>1,'name'=>'QA','settings'=>'{}']);$queue=DB::table('voice_live_queues')->insertGetId(['workspace_id'=>1,'campaign_id'=>$campaign,'name'=>'QA','agent_ids'=>'[]']);$route=DB::table('voice_inbound_routes')->insertGetId(['workspace_id'=>1,'queue_id'=>$queue,'number'=>'+1689'.random_int(1000000,9999999)]);$id=(string)Str::uuid();DB::table('voice_inbound_calls')->insert($d+['id'=>$id,'workspace_id'=>1,'queue_id'=>$queue,'route_id'=>$route,'account_sid'=>'AC'.str_repeat('a',32),'call_sid'=>'CA'.bin2hex(random_bytes(16)),'from_number'=>'+5511999991111','to_number'=>'+16890000000','created_at'=>'2026-10-05 12:00:00','updated_at'=>now()]);return $id;}
 public function test_report_has_exclusive_outcomes_local_dates_and_transfer_does_not_double_count():void {$id=$this->inbound(['answered_at'=>'2026-10-05 12:00:10','status'=>'tabulation','capacity_released_at'=>'2026-10-05 12:02:00','user_id'=>$this->admin->id]);foreach(range(1,2)as $i)DB::table('voice_inbound_offers')->insert(['id'=>(string)Str::uuid(),'call_id'=>$id,'user_id'=>$this->admin->id,'identity'=>'private','status'=>'transferred','created_at'=>now()]);$this->inbound(['status'=>'waiting']);$this->inbound(['status'=>'unavailable','capacity_released_at'=>now()]);$this->inbound(['status'=>'abandoned','capacity_released_at'=>now()]);$this->inbound(['created_at'=>'2026-10-05 02:59:59']);$r=$this->getJson('/api/voice/inbound/reports?from=2026-10-05&to=2026-10-05')->assertOk()->assertJsonPath('counts.total',4)->assertJsonPath('counts.answered',1)->assertJsonPath('counts.active',1)->assertJsonPath('counts.abandoned',1)->assertJsonPath('counts.unavailable',1)->assertJsonPath('counts.transferred',1)->assertJsonPath('counts.tabulation_pending',1);$this->assertEquals(10,$r->json('average_wait_seconds'));$this->assertEquals(25,$r->json('answer_rate'));$this->getJson('/api/voice/inbound/reports?from=2026-10-05&to=2026-10-05&outcome=answered')->assertJsonPath('rows.total',1)->assertJsonPath('counts.total',4);$this->getJson('/api/voice/inbound/reports/'.$id)->assertOk()->assertJsonCount(2,'offers')->assertJsonMissingPath('offers.0.identity')->assertJsonMissingPath('call.account_sid');Http::assertNothingSent();}
 public function test_reports_reject_long_range_and_cross_workspace_and_do_not_invent_zero_averages():void {$this->getJson('/api/voice/inbound/reports?from=2026-01-01&to=2026-10-05')->assertUnprocessable();$this->getJson('/api/voice/inbound/reports?from=2020-01-01&to=2020-01-02')->assertOk()->assertJsonPath('average_wait_seconds',null)->assertJsonPath('answer_rate',null);$id=$this->inbound();$w=DB::table('voice_workspaces')->insertGetId(['name'=>'Other']);DB::table('voice_inbound_calls')->where('id',$id)->update(['workspace_id'=>$w]);$this->getJson('/api/voice/inbound/reports/'.$id)->assertNotFound();$lead=$this->lead(['workspace_id'=>$w]);$this->getJson('/api/voice/leads')->assertJsonPath('rows.total',0);$this->putJson('/api/voice/leads/'.$lead,['revision'=>1,'status'=>'qualified'])->assertNotFound();}
 private function audio(array $d=[]):string {$id=(string)Str::uuid();DB::table('voice_audio_sessions')->insert($d+['id'=>$id,'workspace_id'=>1,'user_id'=>$this->admin->id,'idempotency_key'=>(string)Str::uuid(),'grant_expires_at'=>now(),'grant_hash'=>hash('sha256',$id),'status'=>'ended','expires_at'=>now()->subDays(100),'created_at'=>now()->subDays(100),'updated_at'=>now()->subDays(100)]);return $id;}
 public function test_quality_retains_unknown_values_and_rejects_addresses_and_foreign_sessions():void {$id=$this->audio();$q=['source'=>'browser_webrtc','observed_seconds'=>20,'sample_count'=>1,'packets_sent'=>100,'packets_received'=>99,'audio_energy'=>0.2,'codec'=>'audio/PCMU','rtt_p95_ms'=>null,'jitter_p95_ms'=>3,'loss_percent'=>0,'timeline'=>[['seconds'=>20,'rtt_ms'=>null,'jitter_ms'=>3]]];$d=['packets_sent'=>100,'packets_received'=>99,'audio_energy'=>0.2,'quality'=>$q];$url='/api/voice/audio/sessions/'.$id.'/metrics';$this->postJson($url,$d)->assertOk();$saved=json_decode(DB::table('voice_audio_sessions')->where('id',$id)->value('client_metrics'),true);$this->assertNull($saved['quality']['rtt_p95_ms']);$d['quality']['remote_address']='private';$this->postJson($url,$d)->assertUnprocessable();unset($d['quality']['remote_address']);$u=User::factory()->create(['voice_workspace_id'=>1]);$this->actingAs($u)->postJson($url,$d)->assertNotFound();$this->assertDatabaseHas('voice_audio_sessions',['id'=>$id,'status'=>'ended']);}
 public function test_retention_is_a_read_only_preview_excluding_active_diagnostics():void {$this->audio();$this->audio(['status'=>'active']);$before=DB::table('voice_audio_sessions')->orderBy('id')->get()->toJson();$this->getJson('/api/voice/health/diagnostics?retention_days=90')->assertOk()->assertJsonPath('retention.preview_only',true)->assertJsonPath('retention.ended_audio_sessions',1)->assertJsonCount(2,'sessions')->assertJsonPath('sessions.0.quality',null)->assertJsonMissingPath('sessions.0.client_metrics');$this->assertSame($before,DB::table('voice_audio_sessions')->orderBy('id')->get()->toJson());$this->getJson('/api/voice/health/diagnostics?retention_days=1')->assertUnprocessable();Http::assertNothingSent();}
}
