<?php
namespace Tests\Feature;
use App\Models\User;
use App\Services\{ChannelCosts,IntegrationEvents,TechnicalRetention};
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Http};
use Illuminate\Support\Str;
use Tests\TestCase;
class OperationalControlsTest extends TestCase {
 use RefreshDatabase;private User $admin;
 protected function setUp():void{parent::setUp();Http::preventStrayRequests();$this->admin=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'admin']);$this->actingAs($this->admin);$this->travelTo(now()->setDate(2026,10,5)->setTime(12,0));config(['twilio_voice_test'=>['account_sid'=>'AC'.str_repeat('a',32),'api_key'=>'SK'.str_repeat('b',32),'api_secret'=>str_repeat('c',32)],'whatsapp_test_connection'=>['account_sid'=>'AC'.str_repeat('a',32),'api_key'=>'SK'.str_repeat('b',32),'api_secret'=>str_repeat('c',32)]]);}
 private function integration():array{return $this->postJson('/api/voice/integrations',['name'=>'QA','scopes'=>['events:read'],'list_keys'=>[],'agent_ids'=>[]])->assertCreated()->json();}
 private function delivery():array{$i=$this->integration();DB::table('ma_integrations')->where('id',$i['id'])->update(['webhook_url'=>'https://hooks.example.com/events']);$s=\Mockery::mock(IntegrationEvents::class)->makePartial();$s->shouldReceive('destination')->andReturn(['host'=>'hooks.example.com','ip'=>'93.184.216.34']);app()->instance(IntegrationEvents::class,$s);$s->emit(1,'test','subject',(string)Str::uuid());return [$s,DB::table('ma_event_deliveries')->orderByDesc('created_at')->first()];}
 private function inbound(array $d=[]):string{$campaign=DB::table('voice_campaigns')->insertGetId(['workspace_id'=>1,'name'=>'QA','settings'=>'{}']);$q=DB::table('voice_live_queues')->insertGetId(['workspace_id'=>1,'campaign_id'=>$campaign,'name'=>'QA','agent_ids'=>'[]']);$route=DB::table('voice_inbound_routes')->insertGetId(['workspace_id'=>1,'queue_id'=>$q,'number'=>'+1202'.random_int(1000000,9999999)]);$id=(string)Str::uuid();DB::table('voice_inbound_calls')->insert($d+['id'=>$id,'workspace_id'=>1,'queue_id'=>$q,'route_id'=>$route,'account_sid'=>'AC'.str_repeat('a',32),'call_sid'=>'CA'.str_repeat('1',32),'from_number'=>'+5511999991234','to_number'=>'+12025550123','status'=>'completed','capacity_released_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);return $id;}
 private function message(string $provider='twilio'):string{$sender=DB::table('wa_senders')->where('workspace_id',1)->value('id')??DB::table('wa_senders')->insertGetId(['workspace_id'=>1,'label'=>'QA','number'=>'+12025550123','ownership'=>'external']);$id=(string)Str::uuid();DB::table('wa_messages')->insert(['id'=>$id,'workspace_id'=>1,'sender_id'=>$sender,'direction'=>'outbound','idempotency_key'=>$id,'request_hash'=>hash('sha256',$id),'account_sid'=>'AC'.str_repeat('a',32),'provider_sid'=>$provider==='twilio'?'SM'.str_repeat('3',32):null,'provider'=>$provider,'from_number'=>'+12025550123','to_number'=>'+5511999991234','status'=>'delivered','created_at'=>now(),'updated_at'=>now()]);return $id;}
 private function audio(array $d=[]):string{$id=(string)Str::uuid();DB::table('voice_audio_sessions')->insert($d+['id'=>$id,'workspace_id'=>1,'user_id'=>$this->admin->id,'idempotency_key'=>$id,'grant_expires_at'=>now()->subDays(100),'grant_hash'=>hash('sha256',$id),'status'=>'ended','expires_at'=>now()->subDays(100),'created_at'=>now()->subDays(100),'updated_at'=>now()->subDays(100)]);return $id;}
 public function test_costs_keep_currencies_separate_and_qr_is_not_free():void{$id=$this->inbound();$m=$this->message();$this->message('qr');foreach([['voice_inbound',$id,'CA'.str_repeat('1',32),'USD','0.012345'],['whatsapp_api',$m,'SM'.str_repeat('3',32),'BRL','0.100000']]as [$c,$ref,$sid,$unit,$amount])DB::table('ma_channel_costs')->insert(['workspace_id'=>1,'channel'=>$c,'reference_id'=>$ref,'provider_sid'=>$sid,'leg'=>'message','amount'=>$amount,'currency'=>$unit,'synced_at'=>now()]);$r=$this->getJson('/api/voice/health/costs?from=2026-10-05&to=2026-10-05')->assertOk()->assertJsonCount(2,'known')->assertJsonPath('channels.3.unknown',1)->assertJsonPath('channels.3.known',[])->assertJsonPath('rows.total',3);$this->assertEquals('0.012345',collect($r->json('known'))->firstWhere('currency','USD')['amount']);$this->getJson('/api/voice/health/costs?from=2026-10-05&to=2026-10-05&channel=whatsapp_qr')->assertJsonPath('rows.data.0.cost_status','unavailable');Http::assertNothingSent();}
 public function test_whatsapp_cost_sync_is_get_only_idempotent_and_preserves_known_value():void{$id=$this->message();$base=['sid'=>'SM'.str_repeat('3',32),'account_sid'=>'AC'.str_repeat('a',32),'from'=>'whatsapp:+12025550123','to'=>'whatsapp:+5511999991234','price_unit'=>'usd'];Http::fake(['api.twilio.com/*'=>Http::sequence()->push($base+['price'=>'-0.025'])->push($base+['price'=>null])]);$url='/api/voice/health/costs/whatsapp_api/'.$id.'/sync';$this->postJson($url)->assertOk()->assertJsonPath('pending',0);$this->postJson($url)->assertOk()->assertJsonPath('pending',1);$this->assertDatabaseCount('ma_channel_costs',1);$this->assertDatabaseHas('ma_channel_costs',['reference_id'=>$id,'amount'=>0.025,'currency'=>'USD']);Http::assertSentCount(2);Http::assertNotSent(fn($r)=>$r->method()!=='GET');$this->assertDatabaseCount('wa_messages',1);}
 public function test_cost_sync_rejects_foreign_message_and_unfinished_calls():void{$id=$this->message();Http::fake(['api.twilio.com/*'=>Http::response(['sid'=>'SM'.str_repeat('3',32),'account_sid'=>'AC'.str_repeat('a',32),'from'=>'whatsapp:+12025550123','to'=>'whatsapp:+5511888888888','price'=>'-0.01','price_unit'=>'usd'])]);$this->postJson('/api/voice/health/costs/whatsapp_api/'.$id.'/sync')->assertStatus(502);$this->assertDatabaseCount('ma_channel_costs',0);$c=$this->inbound(['capacity_released_at'=>null]);$this->postJson('/api/voice/health/costs/voice_inbound/'.$c.'/sync')->assertConflict();$this->postJson('/api/voice/health/costs/whatsapp_qr/'.$id.'/sync')->assertUnprocessable();Http::assertSentCount(1);}
 public function test_inbound_costs_validate_all_legs_before_writing():void{$id=$this->inbound();DB::table('voice_inbound_offers')->insert(['id'=>(string)Str::uuid(),'call_id'=>$id,'user_id'=>$this->admin->id,'identity'=>'qa-agent','child_sid'=>'CA'.str_repeat('2',32),'answered_at'=>now(),'created_at'=>now()]);$parent=['sid'=>'CA'.str_repeat('1',32),'account_sid'=>'AC'.str_repeat('a',32),'from'=>'+5511999991234','to'=>'+12025550123','price'=>'0','price_unit'=>'usd'];$child=['sid'=>'CA'.str_repeat('2',32),'account_sid'=>'AC'.str_repeat('a',32),'parent_call_sid'=>$parent['sid'],'to'=>'client:qa-agent','price'=>'-0.003','price_unit'=>'usd'];Http::fake(['api.twilio.com/*'=>Http::sequence()->push($parent)->push(array_replace($child,['parent_call_sid'=>'CA'.str_repeat('f',32)]))->push($parent)->push($child)]);$url='/api/voice/health/costs/voice_inbound/'.$id.'/sync';$this->postJson($url)->assertStatus(502);$this->assertDatabaseCount('ma_channel_costs',0);$this->postJson($url)->assertOk();$this->assertDatabaseCount('ma_channel_costs',2);$this->getJson('/api/voice/health/costs?from=2026-10-05&to=2026-10-05')->assertJsonPath('rows.data.0.cost_status','complete')->assertJsonPath('known.0.amount','0.003000');Http::assertNotSent(fn($r)=>$r->method()!=='GET');}
 public function test_cost_access_and_date_validation():void{$this->getJson('/api/voice/health/costs?from=2026-01-01&to=2026-10-05')->assertUnprocessable();$this->admin->forceFill(['voice_role'=>'supervisor'])->save();$this->getJson('/api/voice/health/costs?from=2026-10-05&to=2026-10-05')->assertOk()->assertJsonPath('can_manage',false);$this->postJson('/api/voice/health/costs/voice_inbound/'.Str::uuid().'/sync')->assertForbidden();$this->putJson('/api/voice/health/retention',[])->assertForbidden();$this->admin->forceFill(['voice_role'=>'agent'])->save();foreach(['/costs?from=2026-10-05&to=2026-10-05','/recovery','/retention']as $p)$this->getJson('/api/voice/health'.$p)->assertForbidden();Http::assertNothingSent();}
 public function test_retry_requires_current_revision_and_preserves_attempt_history_and_event_id():void{[$s,$d]=$this->delivery();Http::fake(['hooks.example.com/*'=>Http::response(['secret'=>'must-not-persist'],503)]);$s->deliver($d->id);$d=DB::table('ma_event_deliveries')->where('id',$d->id)->first();$this->getJson('/api/voice/health/recovery/'.$d->id.'/attempts')->assertOk()->assertJsonPath('attempts.0.error','http_error')->assertDontSee('must-not-persist');$url='/api/voice/integrations/deliveries/'.$d->id.'/retry';$this->postJson($url,['revision'=>$d->revision])->assertOk();$this->postJson($url,['revision'=>$d->revision])->assertConflict();$this->assertDatabaseHas('ma_event_deliveries',['id'=>$d->id,'status'=>'pending','attempts'=>0,'event_sequence'=>$d->event_sequence]);$this->assertDatabaseCount('ma_delivery_attempts',1);$this->assertDatabaseCount('ma_public_events',1);Http::assertSentCount(1);}
 public function test_expired_sixth_lease_is_dead_without_seventh_request():void{[$s,$d]=$this->delivery();$token=(string)Str::uuid();DB::table('ma_event_deliveries')->where('id',$d->id)->update(['status'=>'delivering','attempts'=>6,'lease_token'=>$token,'locked_until'=>now()->subMinute()]);DB::table('ma_delivery_attempts')->insert(['id'=>$token,'delivery_id'=>$d->id,'attempt'=>6,'status'=>'running','started_at'=>now()->subMinutes(2)]);$s->deliver($d->id);$this->assertDatabaseHas('ma_event_deliveries',['id'=>$d->id,'status'=>'dead','attempts'=>6,'lease_token'=>null]);$this->assertDatabaseHas('ma_delivery_attempts',['id'=>$token,'status'=>'abandoned']);Http::assertNothingSent();}
 public function test_late_completion_cannot_overwrite_new_lease_result():void{[$s,$d]=$this->delivery();$n=0;Http::fake(function()use(&$n,$s,$d){$n++;if($n===1){$this->travel(61)->seconds();$s->deliver($d->id);return Http::response([],503);}return Http::response([],204);});$s->deliver($d->id);$this->assertDatabaseHas('ma_event_deliveries',['id'=>$d->id,'status'=>'delivered','attempts'=>2,'http_status'=>204,'lease_token'=>null]);$this->assertDatabaseHas('ma_delivery_attempts',['delivery_id'=>$d->id,'attempt'=>1,'status'=>'abandoned']);$this->assertDatabaseHas('ma_delivery_attempts',['delivery_id'=>$d->id,'attempt'=>2,'status'=>'delivered']);Http::assertSentCount(2);}
 public function test_revoked_integration_and_active_lease_cannot_be_requeued():void{[$s,$d]=$this->delivery();DB::table('ma_event_deliveries')->where('id',$d->id)->update(['status'=>'retry','locked_until'=>now()->addMinute()]);$url='/api/voice/integrations/deliveries/'.$d->id.'/retry';$this->postJson($url,['revision'=>1])->assertConflict();$s->deliver($d->id);DB::table('ma_integrations')->where('id',$d->integration_id)->update(['active'=>false]);DB::table('ma_event_deliveries')->where('id',$d->id)->update(['locked_until'=>null]);$this->postJson($url,['revision'=>1])->assertConflict();$s->deliver($d->id);$this->assertDatabaseHas('ma_event_deliveries',['id'=>$d->id,'status'=>'cancelled']);Http::assertNothingSent();}
 public function test_retention_is_disabled_by_default_and_policy_updates_are_versioned():void{$this->audio();$this->artisan('ma:retention-archive')->assertSuccessful();$this->assertDatabaseCount('ma_retention_runs',0);$this->getJson('/api/voice/health/retention')->assertOk()->assertJsonPath('policy.automatic',false)->assertJsonPath('eligible.audio',1);$d=['revision'=>0,'audio_days'=>120,'session_days'=>30,'delivery_days'=>90,'automatic'=>false];$this->putJson('/api/voice/health/retention',$d)->assertOk()->assertJsonPath('policy.revision',1);$this->putJson('/api/voice/health/retention',$d)->assertConflict();$this->getJson('/api/voice/health/retention')->assertJsonPath('eligible.audio',0);Http::assertNothingSent();}
 public function test_archive_is_reversible_idempotent_and_excludes_active_failed_and_recent_records():void{$old=$this->audio();$this->audio(['status'=>'active']);$this->audio(['updated_at'=>now()]);[$s,$d]=$this->delivery();DB::table('ma_event_deliveries')->where('id',$d->id)->update(['status'=>'delivered','updated_at'=>now()->subDays(100)]);$i=$this->integration();$session=(string)Str::uuid();DB::table('ma_embed_sessions')->insert(['id'=>$session,'integration_id'=>$i['id'],'user_id'=>$this->admin->id,'token_hash'=>hash('sha256',$session),'expires_at'=>now()->subDays(100)]);$request=['revision'=>0,'idempotency_key'=>(string)Str::uuid(),'confirm'=>true];$r=$this->postJson('/api/voice/health/retention/archive',$request)->assertOk()->assertJsonPath('counts.audio',1)->assertJsonPath('counts.session',1)->assertJsonPath('counts.delivery',1);$this->postJson('/api/voice/health/retention/archive',$request)->assertJsonPath('duplicate',true)->assertJsonPath('id',$r->json('id'));$this->assertDatabaseCount('voice_audio_sessions',3);$this->assertDatabaseCount('ma_event_deliveries',1);$this->assertDatabaseCount('ma_retention_runs',1);$this->getJson('/api/voice/health/diagnostics')->assertJsonCount(2,'sessions');$this->getJson('/api/voice/health/recovery')->assertJsonPath('rows.total',0);$s->deliver($d->id);$url='/api/voice/health/retention/'.$r->json('id').'/restore';$this->postJson($url,['confirm'=>true])->assertOk();$this->postJson($url,['confirm'=>true])->assertJsonPath('duplicate',true);$this->assertDatabaseHas('voice_audio_sessions',['id'=>$old,'archived_at'=>null]);$this->assertDatabaseHas('ma_event_deliveries',['id'=>$d->id,'status'=>'delivered','archived_at'=>null]);$s->deliver($d->id);Http::assertNothingSent();}
 public function test_retention_never_archives_retry_dead_locked_or_other_workspace():void{[$s,$d]=$this->delivery();DB::table('ma_event_deliveries')->where('id',$d->id)->update(['status'=>'dead','updated_at'=>now()->subDays(200)]);$a=$this->audio();$w=DB::table('voice_workspaces')->insertGetId(['name'=>'Other']);DB::table('voice_audio_sessions')->where('id',$a)->update(['workspace_id'=>$w]);$p=app(TechnicalRetention::class);$run=$p->archive(1,$this->admin->id,(string)Str::uuid(),0);$this->assertSame(['audio'=>0,'session'=>0,'delivery'=>0],$run['counts']);DB::table('ma_event_deliveries')->where('id',$d->id)->update(['status'=>'delivered','locked_until'=>now()->addMinute()]);$this->assertSame(0,$p->preview(1)['eligible']['delivery']);$this->assertDatabaseCount('ma_public_events',1);Http::assertNothingSent();}
}
