<?php
namespace Tests\Feature;
use App\Models\User;
use App\Services\{IntegrationEvents,ListContacts};
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Http};
use Illuminate\Support\Str;
use Tests\TestCase;
class PublicIntegrationsTest extends TestCase {
 use RefreshDatabase;private User $admin;
 protected function setUp():void{parent::setUp();Http::preventStrayRequests();$this->admin=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'admin']);$this->actingAs($this->admin);}
 private function integration(array $extra=[]):array{return $this->postJson('/api/voice/integrations',array_replace(['name'=>'CRM QA','scopes'=>['lists:read','lists:write','leads:write','events:read'],'list_keys'=>[],'agent_ids'=>[],'embed_origin'=>null,'webhook_url'=>null],$extra))->assertCreated()->json();}
 public function test_token_is_stored_hashed_scopes_and_revocation_are_enforced():void{$i=$this->integration();$this->assertDatabaseHas('ma_integrations',['id'=>$i['id'],'token_hash'=>hash('sha256',$i['token'])]);$this->getJson('/api/voice/integrations')->assertOk()->assertDontSee($i['token'])->assertDontSee($i['webhook_secret']);$this->getJson('/api/v1/lists')->assertUnauthorized();$this->withToken($i['token'])->getJson('/api/v1/lists')->assertOk();$this->getJson('/api/v1/calls')->assertForbidden();$this->postJson('/api/voice/integrations/'.$i['id'].'/revoke')->assertOk();$this->getJson('/api/v1/lists')->assertUnauthorized();}
 public function test_atomic_import_idempotency_and_removed_membership_are_preserved():void{$list=DB::table('voice_lists')->insertGetId(['workspace_id'=>1,'name'=>'API QA','source'=>'QA']);$i=$this->integration(['list_keys'=>['voice:'.$list]]);$d=['kind'=>'voice','list_id'=>$list,'contacts'=>[['name'=>'Pessoa QA','phone'=>'+5511999991234','consent'=>false]]];$key=(string)Str::uuid();$this->withToken($i['token'])->withHeader('Idempotency-Key',$key);$id=$this->postJson('/api/v1/contacts/import',$d)->assertOk()->json('results.0.contact_id');$this->postJson('/api/v1/contacts/import',$d)->assertOk();$this->assertDatabaseCount('voice_contacts',1);$this->postJson('/api/v1/contacts/import',array_replace($d,['contacts'=>[['name'=>'Outro','phone'=>'+5511999991234','consent'=>false]]]))->assertConflict();app(ListContacts::class)->remove(1,'voice',$list,$id);$this->withHeader('Idempotency-Key',(string)Str::uuid())->postJson('/api/v1/contacts/import',$d)->assertOk()->assertJsonPath('results.0.membership_removed',true);$this->assertDatabaseHas('voice_list_members',['list_id'=>$list,'contact_id'=>$id,'status'=>'removed']);$this->withHeader('Idempotency-Key',(string)Str::uuid())->postJson('/api/v1/contacts/import',array_replace($d,['list_id'=>$list+1]))->assertForbidden();Http::assertNothingSent();}
 public function test_social_lead_dedup_does_not_create_inbound_message_or_grant_marketing_consent():void{$i=$this->integration();$d=['source'=>'facebook','external_id'=>'lead-qa','name'=>'Lead QA','phone'=>'+5511999991234','consent'=>false,'attribution'=>['form_id'=>'form-1']];$this->withToken($i['token'])->withHeader('Idempotency-Key',(string)Str::uuid())->postJson('/api/v1/leads',$d)->assertOk()->assertJsonPath('duplicate',false);$this->withHeader('Idempotency-Key',(string)Str::uuid())->postJson('/api/v1/leads',$d)->assertOk()->assertJsonPath('duplicate',true);$this->assertDatabaseCount('social_leads',1);$this->assertDatabaseCount('wa_messages',0);$this->assertDatabaseHas('voice_contacts',['phone'=>$d['phone'],'consent'=>false]);$this->getJson('/api/v1/events')->assertOk()->assertJsonPath('data.0.type','lead.received');}
 public function test_embed_is_limited_to_allowed_agent_and_api_method_revokes_immediately():void{$agent=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'agent']);$i=$this->integration(['scopes'=>['voice:embed'],'agent_ids'=>[$agent->id],'embed_origin'=>'https://crm.example.com']);$this->withToken($i['token'])->postJson('/api/v1/embed-sessions',['user_id'=>$this->admin->id])->assertForbidden();$s=$this->postJson('/api/v1/embed-sessions',['user_id'=>$agent->id])->assertOk()->json();$this->withToken($s['access_token'])->getJson('/embed/api/voice/operations/catalog')->assertOk()->assertJsonPath('user_id',$agent->id)->assertJsonPath('can_manage',false);$this->postJson('/embed/api/voice/calling/calls',['method'=>'sip_trunk'])->assertUnprocessable();$this->getJson('/embed/api/voice/team')->assertNotFound();DB::table('ma_integrations')->where('id',$i['id'])->update(['active'=>false]);$this->getJson('/embed/api/voice/operations/catalog')->assertUnauthorized();}
 public function test_embedded_frame_origin_and_expired_session_are_rejected():void{$agent=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'agent']);$i=$this->integration(['scopes'=>['voice:embed'],'agent_ids'=>[$agent->id],'embed_origin'=>'https://crm.example.com']);$this->get('/embed?origin=https://evil.example.com')->assertForbidden();$this->get('/embed?origin=https://crm.example.com')->assertOk()->assertHeader('Content-Security-Policy','frame-ancestors https://crm.example.com');$s=$this->withToken($i['token'])->postJson('/api/v1/embed-sessions',['user_id'=>$agent->id])->json();$this->travel(11)->minutes();$this->withToken($s['access_token'])->getJson('/embed/api/voice/operations/catalog')->assertUnauthorized();}
 public function test_event_dedup_and_internal_webhook_destination_are_rejected():void{$i=$this->integration();app(IntegrationEvents::class)->emit(1,'test','subject','same',['status'=>'completed']);app(IntegrationEvents::class)->emit(1,'test','subject','same',['status'=>'completed']);$this->assertDatabaseCount('ma_public_events',1);foreach(['http://example.com','https://127.0.0.1/a','https://localhost/a','https://user:pass@example.com/a'] as $url)$this->postJson('/api/voice/integrations',['name'=>'Bad URL','scopes'=>['events:read'],'list_keys'=>[],'agent_ids'=>[],'webhook_url'=>$url])->assertUnprocessable();Http::assertNothingSent();}
 public function test_webhook_signature_retry_and_lease_preserve_event_identity():void {
  $i=$this->integration();DB::table('ma_integrations')->where('id',$i['id'])->update(['webhook_url'=>'https://hooks.example.com/events']);
  $service=\Mockery::mock(IntegrationEvents::class)->makePartial();$service->shouldReceive('destination')->andReturn(['host'=>'hooks.example.com','ip'=>'93.184.216.34']);app()->instance(IntegrationEvents::class,$service);
  $service->emit(1,'call.completed','call-qa','call-qa:completed',['status'=>'completed']);$delivery=DB::table('ma_event_deliveries')->first();
  Http::fake(['https://hooks.example.com/events'=>Http::sequence()->push([],503)->push([],204)]);$service->deliver($delivery->id);$this->assertDatabaseHas('ma_event_deliveries',['id'=>$delivery->id,'status'=>'retry','attempts'=>1]);$service->deliver($delivery->id);Http::assertSentCount(1);$this->travel(31)->seconds();$service->deliver($delivery->id);$this->assertDatabaseHas('ma_event_deliveries',['id'=>$delivery->id,'status'=>'delivered','attempts'=>2]);
  $events=[];Http::assertSent(function($request)use($i,&$events){$events[]=$request->header('X-MA-Event-Id')[0];$expected=hash_hmac('sha256',$request->header('X-MA-Timestamp')[0].'.'.$request->body(),$i['webhook_secret']);return hash_equals($expected,$request->header('X-MA-Signature')[0]);});$service->deliver($delivery->id);Http::assertSentCount(2);
 }
}
