<?php
namespace Tests\Feature;
use App\Models\User;
use App\Services\{VoiceJourneyPreset,QueueRouting,QueueChannels};
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Http};
use Tests\TestCase;
class QueueChannelsTest extends TestCase {
 use RefreshDatabase;private User $user;private array $preset;private int $sender;
 protected function setUp():void {parent::setUp();Http::preventStrayRequests();$this->user=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'admin']);$this->actingAs($this->user);config(['twilio_voice_test'=>['account_sid'=>'AC'.str_repeat('a',32),'caller_id'=>'+12025550123','enabled'=>true,'api_key'=>'SK'.str_repeat('b',32),'api_secret'=>str_repeat('c',32),'edge'=>'ashburn']]);$this->preset=app(VoiceJourneyPreset::class)->create(1,$this->user->id,'+12025550123');$this->sender=DB::table('wa_senders')->insertGetId(['workspace_id'=>1,'number'=>'+5511999990001','provider'=>'qr','ownership'=>'external','label'=>'QR QA']);}
 private function data(array $extra=[]):array{return $extra+['name'=>'Fila comercial','direction'=>'outbound','mode'=>'progressive','calling_method'=>'programmable_voice','strategy'=>'fifo','wrapup_seconds'=>30,'agent_ids'=>[$this->user->id],'voice_number'=>'+12025550123','whatsapp_sender_id'=>$this->sender,'number_mode'=>'separate'];}
 private function create(array $extra=[]):int{return $this->postJson('/api/voice/operations/queues',$this->data($extra))->assertOk()->json('id');}
 private function bind(?int $q,int $rev=0){return $this->putJson('/api/voice/journeys/'.$this->preset['campaign_id'].'/nodes/voice',['revision'=>$rev,'config'=>['queue_id'=>$q]]);}
 public function test_cadence_selects_queue_and_inherits_numbers_without_activating_it():void {$q=$this->create();$this->bind($q)->assertOk()->assertJsonPath('journey.queue.id',$q)->assertJsonPath('journey.settings.whatsapp_sender_id',$this->sender)->assertJsonPath('journey.settings.business_number','+12025550123');$this->assertSame([$this->preset['campaign_id']],QueueRouting::campaigns(DB::table('voice_live_queues')->find($q)));$this->assertSame([],QueueRouting::campaigns(DB::table('voice_live_queues')->find($this->preset['queue_id'])));$this->assertDatabaseHas('voice_live_queues',['id'=>$q,'status'=>'paused']);$this->assertDatabaseCount('voice_outbound_calls',0);Http::assertNothingSent();}
 public function test_queue_edits_preserve_bindings_and_propagate_sender_and_revision():void {$q=$this->create();$this->bind($q)->assertOk();$row=DB::table('voice_live_queues')->find($q);$this->putJson('/api/voice/operations/queues/'.$q,$this->data(['revision'=>$row->revision,'whatsapp_sender_id'=>$this->preset['sender_id'],'number_mode'=>'single']))->assertOk();$this->assertSame([$this->preset['campaign_id']],QueueRouting::campaigns(DB::table('voice_live_queues')->find($q)));$c=DB::table('voice_campaigns')->find($this->preset['campaign_id']);$this->assertEquals($this->preset['sender_id'],json_decode($c->settings,true)['whatsapp_sender_id']);$this->assertSame(2,$c->revision);$this->bind($q,1)->assertConflict();}
 public function test_cannot_override_inherited_sender_from_message_card():void {$q=$this->create();$this->bind($q)->assertOk();$this->putJson('/api/voice/journeys/'.$this->preset['campaign_id'].'/nodes/message',['revision'=>1,'config'=>['whatsapp_sender_id'=>$this->preset['sender_id'],'number_mode'=>'single','whatsapp_number'=>'+12025550123']])->assertOk()->assertJsonPath('journey.settings.whatsapp_sender_id',$this->sender)->assertJsonPath('journey.settings.number_mode','separate');}
 public function test_queue_rejects_unverified_origin_and_mismatched_single_number():void {$this->postJson('/api/voice/operations/queues',$this->data(['voice_number'=>'+12025550999']))->assertUnprocessable();$this->postJson('/api/voice/operations/queues',$this->data(['number_mode'=>'single']))->assertUnprocessable();$this->assertDatabaseCount('voice_live_queues',1);}
 public function test_binding_to_running_or_foreign_or_inbound_queue_is_rejected_atomically():void {$q=$this->create();DB::table('voice_live_queues')->where('id',$q)->update(['status'=>'running']);$this->bind($q)->assertConflict();$this->assertDatabaseHas('voice_campaigns',['id'=>$this->preset['campaign_id'],'revision'=>0]);DB::table('voice_live_queues')->where('id',$q)->update(['status'=>'paused','direction'=>'inbound']);$this->bind($q)->assertNotFound();DB::table('voice_workspaces')->insert(['id'=>2,'name'=>'Outro workspace']);DB::table('voice_live_queues')->where('id',$q)->update(['workspace_id'=>2,'direction'=>'outbound']);$this->bind($q)->assertNotFound();}
 public function test_agent_cannot_edit_channels_or_cadence_binding():void {$q=$this->create();$agent=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'agent']);$this->actingAs($agent);$this->bind($q)->assertForbidden();$this->putJson('/api/voice/operations/queues/'.$q,$this->data(['revision'=>0]))->assertForbidden();$this->getJson('/api/voice/operations/catalog')->assertOk()->assertJsonMissingPath('queue_channels');}
 public function test_active_cadence_blocks_channel_change_and_rolls_back_queue():void {$q=$this->create();$this->bind($q)->assertOk();DB::table('voice_campaigns')->where('id',$this->preset['campaign_id'])->update(['status'=>'testing']);$row=DB::table('voice_live_queues')->find($q);$this->putJson('/api/voice/operations/queues/'.$q,$this->data(['revision'=>$row->revision,'whatsapp_sender_id'=>$this->preset['sender_id'],'number_mode'=>'single']))->assertConflict();$this->assertDatabaseHas('voice_live_queues',['id'=>$q,'whatsapp_sender_id'=>$this->sender,'revision'=>$row->revision]);Http::assertNothingSent();}
 public function test_binding_more_than_one_cadence_does_not_remove_other_links():void {$q=$this->create();$this->bind($q)->assertOk();$c=DB::table('voice_campaigns')->find($this->preset['campaign_id']);$id=DB::table('voice_campaigns')->insertGetId(['workspace_id'=>1,'name'=>'Segunda cadência','settings'=>$c->settings,'status'=>'paused']);$this->putJson('/api/voice/journeys/'.$id.'/nodes/voice',['revision'=>0,'config'=>['queue_id'=>$q]])->assertOk();$this->assertCount(2,QueueRouting::campaigns(DB::table('voice_live_queues')->find($q)));$new=$this->create();$this->bind($new,1)->assertOk();$this->assertSame([$id],QueueRouting::campaigns(DB::table('voice_live_queues')->find($q)));}
 public function test_inbound_number_can_be_linked_from_queue_without_enabling_route():void {$q=$this->create(['direction'=>'mixed','incoming_number'=>'+12025550123']);$this->assertDatabaseHas('voice_inbound_routes',['queue_id'=>$q,'number'=>'+12025550123','enabled'=>false]);$this->postJson('/api/voice/operations/queues',$this->data(['direction'=>'mixed','incoming_number'=>'+12025550123']))->assertConflict();$this->assertDatabaseCount('voice_inbound_routes',1);Http::assertNothingSent();}
 public function test_channel_change_cancels_pending_message_without_erasing_call_history():void {
  $q=$this->create();$this->bind($q)->assertOk();$campaign=DB::table('voice_campaigns')->find($this->preset['campaign_id']);$contact=DB::table('voice_contacts')->insertGetId(['workspace_id'=>1,'name'=>'Pessoa QA','phone'=>'+5511999990002','original_phone'=>'+5511999990002','source'=>'QA']);$call=(string)\Illuminate\Support\Str::uuid();$followup=(string)\Illuminate\Support\Str::uuid();
  DB::table('voice_outbound_calls')->insert(['id'=>$call,'workspace_id'=>1,'user_id'=>$this->user->id,'contact_id'=>$contact,'campaign_id'=>$campaign->id,'idempotency_key'=>(string)\Illuminate\Support\Str::uuid(),'request_hash'=>str_repeat('a',64),'grant_hash'=>str_repeat('b',64),'configuration_hash'=>str_repeat('c',64),'destination'=>'+5511999990002','caller_id'=>'+12025550123','status'=>'no_answer','max_seconds'=>30,'ring_seconds'=>10,'consent_evidence'=>'QA','grant_expires_at'=>now(),'deadline_at'=>now(),'capacity_released_at'=>now()]);
  DB::table('voice_followups')->insert(['id'=>$followup,'workspace_id'=>1,'campaign_id'=>$campaign->id,'contact_id'=>$contact,'user_id'=>$this->user->id,'call_id'=>$call,'campaign_revision'=>$campaign->followup_revision,'settings'=>$campaign->settings,'destination'=>'+5511999990002','due_at'=>now(),'status'=>'pending']);
  $row=DB::table('voice_live_queues')->find($q);$this->putJson('/api/voice/operations/queues/'.$q,$this->data(['revision'=>$row->revision,'whatsapp_sender_id'=>$this->preset['sender_id'],'number_mode'=>'single']))->assertOk();$this->assertDatabaseHas('voice_followups',['id'=>$followup,'status'=>'cancelled']);$this->assertDatabaseHas('voice_outbound_calls',['id'=>$call,'status'=>'no_answer','caller_id'=>'+12025550123']);Http::assertNothingSent();
 }
}
