<?php
namespace Tests\Feature;
use App\Models\User;
use App\Services\{InboundVoice,QueueRouting,VoiceLiveQueue};
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Http};
use Illuminate\Support\Str;
use Tests\TestCase;
class QueueRoutingTest extends TestCase {
 use RefreshDatabase;private User $admin;private User $agent;
 protected function setUp():void{parent::setUp();Http::preventStrayRequests();$this->travelTo(now()->setDate(2026,10,5)->setTime(12,0));$this->admin=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'admin']);$this->agent=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'agent']);$this->actingAs($this->admin);config(['twilio_voice_test'=>['account_sid'=>'AC'.str_repeat('a',32),'caller_id'=>'+12025550123','enabled'=>true,'api_key'=>'SK'.str_repeat('b',32),'api_secret'=>str_repeat('c',32),'edge'=>'ashburn'],'voice_calling_test'=>['allowed_recipients'=>['+5511999990001','+5511999990002'],'daily_limit'=>20,'max_seconds'=>30,'ring_seconds'=>10,'caller_id_confirmed'=>true,'sip_username'=>'qa','sip_password'=>'fixture','event_secret'=>str_repeat('b',64)]]);}
 private function campaign(string $phone='+5511999990001'):int{$settings=['mode'=>'preview','business_number'=>'+12025550123','number_mode'=>'separate','timezone'=>'UTC','days'=>[1,2,3,4,5,6,7],'start_time'=>'00:00','end_time'=>'23:59','max_attempts'=>5,'retry_minutes'=>1,'concurrency'=>1,'whatsapp_enabled'=>false,'whatsapp_delivery'=>'simulation'];$id=DB::table('voice_campaigns')->insertGetId(['workspace_id'=>1,'name'=>'Campanha '.$phone,'status'=>'testing','settings'=>json_encode($settings),'created_at'=>now()]);$c=DB::table('voice_contacts')->insertGetId(['workspace_id'=>1,'name'=>'Pessoa QA','phone'=>$phone,'original_phone'=>$phone,'source'=>'QA','consent'=>true,'consent_evidence'=>'Autorização QA']);DB::table('voice_members')->insert(['campaign_id'=>$id,'contact_id'=>$c]);return $id;}
 private function data(string $direction='outbound',array $campaigns=[]):array{return ['name'=>'Equipe de atendimento','direction'=>$direction,'campaign_ids'=>$campaigns,'mode'=>'preview','calling_method'=>'programmable_voice','strategy'=>'fifo','wrapup_seconds'=>30,'agent_ids'=>[$this->agent->id]];}
 private function queue(string $direction='outbound',array $campaigns=[]):array{return $this->postJson('/api/voice/operations/queues',$this->data($direction,$campaigns))->assertOk()->json();}
 private function route(int $q,array $extra=[]){return $this->postJson('/api/voice/inbound/routes',$extra+['number'=>'+12025550123','queue_id'=>$q,'enabled'=>true,'ring_seconds'=>20,'wait_seconds'=>120]);}
 public function test_inbound_queue_needs_no_campaign_and_outbound_cannot_own_inbound_route():void{$q=$this->queue('inbound');$this->assertNull($q['campaign_id']);$this->route($q['id'])->assertOk();$this->postJson('/api/voice/operations/queues/'.$q['id'].'/status',['channel'=>'inbound','status'=>'running'])->assertOk();$this->postJson('/api/voice/operations/queues/'.$q['id'].'/status',['channel'=>'outbound','status'=>'running'])->assertUnprocessable();$this->actingAs($this->agent)->postJson('/api/voice/operations/queues/'.$q['id'].'/claim',['idempotency_key'=>(string)Str::uuid()])->assertUnprocessable();$this->actingAs($this->admin);$out=$this->queue();$this->route($out['id'])->assertNotFound();$this->assertDatabaseCount('voice_campaigns',0);Http::assertNothingSent();}
 public function test_one_queue_alternates_campaigns_and_reservation_keeps_campaign_identity():void{$a=$this->campaign();$b=$this->campaign('+5511999990002');$q=$this->queue('outbound',[$a,$b]);$this->postJson('/api/voice/operations/queues/'.$q['id'].'/status',['status'=>'running'])->assertOk();$this->actingAs($this->agent)->postJson('/api/voice/queues/presence',['status'=>'available'])->assertNoContent();$key=(string)Str::uuid();$url='/api/voice/operations/queues/'.$q['id'].'/claim';$r=$this->postJson($url,['idempotency_key'=>$key])->assertOk()->json('reservation');$this->assertSame($a,$r['campaign_id']);$this->postJson($url,['idempotency_key'=>$key])->assertJsonPath('reservation.id',$r['id']);$this->postJson('/api/voice/operations/reservations/'.$r['id'].'/cancel')->assertOk();$this->travel(1)->seconds();$r2=$this->postJson($url,['idempotency_key'=>(string)Str::uuid()])->assertOk()->json('reservation');$this->assertSame($b,$r2['campaign_id']);$this->getJson('/api/voice/operations/queues')->assertJsonPath('current.campaign.id',$b)->assertJsonCount(2,'queues.0.campaigns');$this->getJson('/api/voice/operations/catalog')->assertJsonCount(2,'campaigns');$this->getJson('/api/voice/calling')->assertJsonCount(2,'campaigns');$this->assertDatabaseCount('voice_outbound_calls',0);Http::assertNothingSent();}
 public function test_campaign_binding_cannot_be_stolen_and_agent_cannot_configure():void{$a=$this->campaign();$q=$this->queue('outbound',[$a]);$this->postJson('/api/voice/operations/queues',$this->data('outbound',[$a]))->assertConflict();$this->postJson('/api/voice/operations/queues',$this->data('inbound',[$a]))->assertUnprocessable();$this->actingAs($this->agent)->postJson('/api/voice/operations/queues',$this->data())->assertForbidden();$this->postJson('/api/voice/operations/queues/'.$q['id'].'/status',['status'=>'running'])->assertForbidden();$this->route($q['id'])->assertForbidden();Http::assertNothingSent();}
 public function test_edit_preserves_closed_reservation_campaign_and_refuses_active_reservation():void{$a=$this->campaign();$b=$this->campaign('+5511999990002');$q=$this->queue('outbound',[$a]);$contact=DB::table('voice_members')->where('campaign_id',$a)->value('contact_id');$rid=(string)Str::uuid();DB::table('voice_live_reservations')->insert(['id'=>$rid,'workspace_id'=>1,'queue_id'=>$q['id'],'campaign_id'=>$a,'contact_id'=>$contact,'user_id'=>$this->agent->id,'idempotency_key'=>(string)Str::uuid(),'expires_at'=>now()->addMinutes(2),'created_at'=>now(),'status'=>'reserved']);$d=$this->data('outbound',[$b])+['revision'=>$q['revision']];$this->putJson('/api/voice/operations/queues/'.$q['id'],$d)->assertConflict();DB::table('voice_live_reservations')->where('id',$rid)->update(['status'=>'cancelled']);$this->putJson('/api/voice/operations/queues/'.$q['id'],$d)->assertOk();$this->assertDatabaseHas('voice_live_reservations',['id'=>$rid,'campaign_id'=>$a]);$this->assertSame([$b],QueueRouting::campaigns(DB::table('voice_live_queues')->find($q['id'])));$this->putJson('/api/voice/operations/queues/'.$q['id'],$d)->assertConflict();}
 public function test_inbound_distribution_obeys_queue_switch_and_preserves_outbound_pause():void{$q=$this->queue('mixed');$this->route($q['id'])->assertOk();DB::table('voice_agent_presence')->insert(['workspace_id'=>1,'user_id'=>$this->agent->id,'status'=>'available','last_seen_at'=>now()]);DB::table('voice_inbound_devices')->insert(['user_id'=>$this->agent->id,'workspace_id'=>1,'session_id'=>(string)Str::uuid(),'identity'=>'qa-agent','ready'=>true,'last_seen_at'=>now()]);$d=['AccountSid'=>'AC'.str_repeat('a',32),'CallSid'=>'CA'.str_repeat('1',32),'From'=>'+5511999990001','To'=>'+12025550123'];$this->assertStringContainsString('<Reject',app(InboundVoice::class)->receive($d));$this->assertDatabaseCount('voice_inbound_calls',0);$this->postJson('/api/voice/operations/queues/'.$q['id'].'/status',['channel'=>'inbound','status'=>'running'])->assertOk();$this->assertStringContainsString('<Client',app(InboundVoice::class)->receive($d));$this->assertDatabaseHas('voice_live_queues',['id'=>$q['id'],'status'=>'paused','inbound_enabled'=>true]);$this->putJson('/api/voice/operations/queues/'.$q['id'],$this->data('mixed')+['revision'=>1])->assertConflict();Http::assertNothingSent();}
 public function test_number_catalog_excludes_verified_caller_ids_and_foreign_account():void{$q=$this->queue('inbound');foreach([['+12025550124','owned','a'],['+12025550125','verified','a'],['+12025550126','owned','f']]as [$number,$kind,$account])DB::table('voice_origins')->insert(['workspace_id'=>1,'number'=>$number,'kind'=>$kind,'account_sid'=>'AC'.str_repeat($account,32),'provider_sid'=>'PN'.bin2hex(random_bytes(16)),'verified_at'=>now()]);$this->route($q['id'],['number'=>'+12025550124'])->assertOk();$this->route($q['id'],['number'=>'+12025550125'])->assertUnprocessable();$this->route($q['id'],['number'=>'+12025550126'])->assertUnprocessable();$this->getJson('/api/voice/inbound')->assertJsonCount(2,'available_numbers');Http::assertNothingSent();}
 public function test_agent_only_sees_assigned_queues_and_cannot_get_inbound_token_without_membership():void{$q=$this->queue('inbound');$other=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'agent']);$this->actingAs($other)->getJson('/api/voice/operations/queues')->assertJsonCount(0,'queues');$this->postJson('/api/voice/inbound/token',['session_id'=>(string)Str::uuid()])->assertForbidden();$this->actingAs($this->agent)->getJson('/api/voice/inbound')->assertJsonCount(1,'queues');$this->postJson('/api/voice/inbound/token',['session_id'=>(string)Str::uuid()])->assertOk();$this->assertDatabaseMissing('voice_agent_presence',['user_id'=>$this->agent->id,'status'=>'available']);Http::assertNothingSent();}
}
