<?php
namespace Tests\Feature;
use App\Models\User;
use App\Services\{InboundVoice,QueueOperationSettings,QueueDestinations,VoiceQueue,VoiceRecordings};
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Http};
use Illuminate\Support\Str;
use Tests\TestCase;
class QueueOperationSettingsTest extends TestCase {
 use RefreshDatabase;
 private User $agent;private User $admin;private int $queue;private int $sequence=0;
 protected function setUp():void {parent::setUp();Http::preventStrayRequests();$this->agent=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'agent']);$this->admin=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'admin']);$this->queue=DB::table('voice_live_queues')->insertGetId(['workspace_id'=>1,'name'=>'QA configurações','direction'=>'inbound','status'=>'paused','inbound_enabled'=>true,'agent_ids'=>json_encode([$this->agent->id])]);DB::table('voice_inbound_routes')->insert(['workspace_id'=>1,'queue_id'=>$this->queue,'number'=>'+12025550123','enabled'=>true,'ring_seconds'=>20]);DB::table('voice_agent_presence')->insert(['workspace_id'=>1,'user_id'=>$this->agent->id,'status'=>'available','last_seen_at'=>now()]);DB::table('voice_inbound_devices')->insert(['workspace_id'=>1,'user_id'=>$this->agent->id,'identity'=>'qa','session_id'=>(string)Str::uuid(),'ready'=>true,'last_seen_at'=>now()]);config(['twilio_voice_test'=>['account_sid'=>'AC'.str_repeat('a',32),'api_key'=>'SK'.str_repeat('b',32),'api_secret'=>'test-secret','auth_token'=>'test-token','enabled'=>true]]);}
 private function set(array $v):void {DB::table('voice_live_queues')->where('id',$this->queue)->update($v);}
 private function incoming():array {$sid='CA'.str_pad((string)++$this->sequence,32,'0',STR_PAD_LEFT);$xml=app(InboundVoice::class)->receive(['AccountSid'=>'AC'.str_repeat('a',32),'CallSid'=>$sid,'To'=>'+12025550123','From'=>'+5511999990001']);return [$xml,DB::table('voice_inbound_calls')->where('call_sid',$sid)->first()];}
 private function payload(object $c,string $status='in-progress'):array{return ['AccountSid'=>$c->account_sid,'CallSid'=>$c->call_sid,'RecordingSid'=>'RE'.str_repeat('c',32),'RecordingStatus'=>$status,'RecordingDuration'=>'15'];}
 private function recorded():object {$this->set(['recording_enabled'=>true,'recording_agent_access'=>true,'recording_agent_pause'=>true]);[$xml,$c]=$this->incoming();$this->assertStringContainsString('record-from-answer-dual',$xml);app(VoiceRecordings::class)->callback('inbound',$c->id,$this->payload($c));return $c;}
 public function test_schedule_respects_timezone_overnight_and_end_boundary():void {$this->set(['schedule_enabled'=>true,'schedule_days'=>'[1]','schedule_timezone'=>'America/Sao_Paulo','schedule_start'=>'22:00','schedule_end'=>'02:00']);$q=DB::table('voice_live_queues')->find($this->queue);$this->travelTo(now()->parse('2026-10-06 04:59:00','UTC'));$this->assertTrue(QueueOperationSettings::open($q));$this->travelTo(now()->parse('2026-10-06 05:00:00','UTC'));$this->assertFalse(QueueOperationSettings::open($q));[$xml,$c]=$this->incoming();$this->assertStringContainsString('<Reject',$xml);$this->assertNull($c);Http::assertNothingSent();}
 public function test_queue_permissions_preserve_fixed_mobile_and_explicit_international_special():void {$this->assertSame('+558001234567',\App\Services\VoiceLab::phone('0800 123 4567'));$this->set(['allow_international'=>false,'allow_special'=>false]);$q=DB::table('voice_live_queues')->find($this->queue);$this->assertNotNull(QueueDestinations::reason($q,'+12025550123'));$this->assertNotNull(QueueDestinations::reason($q,'+558001234567'));$this->assertNull(QueueDestinations::reason($q,'+551130001234'));$this->assertNull(QueueDestinations::reason($q,'+5511999990001'));$q->allow_special=true;$this->assertNull(QueueDestinations::reason($q,'+558001234567'));$this->assertNotNull(QueueDestinations::reason($q,'+551100000000'));}
 public function test_agent_ring_timeout_and_missed_offer_pause_are_idempotent():void {$this->set(['agent_ring_seconds'=>7,'missed_offer_limit'=>1]);[$xml,$c]=$this->incoming();$this->assertStringContainsString('timeout="7"',$xml);$offer=DB::table('voice_inbound_offers')->where('call_id',$c->id)->first();$d=['AccountSid'=>$c->account_sid,'CallSid'=>$c->call_sid,'DialCallStatus'=>'no-answer'];app(InboundVoice::class)->finish($offer->id,$d);app(InboundVoice::class)->finish($offer->id,$d);$this->assertDatabaseHas('voice_agent_presence',['user_id'=>$this->agent->id,'status'=>'paused']);$this->assertDatabaseHas('voice_agent_queue_counters',['user_id'=>$this->agent->id,'missed_offers'=>1]);app(VoiceQueue::class)->presence(1,$this->agent->id,'available');$this->assertDatabaseHas('voice_agent_queue_counters',['user_id'=>$this->agent->id,'missed_offers'=>0]);Http::assertNothingSent();}
 public function test_disconnection_option_pauses_without_ending_active_call():void {$this->set(['pause_on_disconnect'=>true]);[$xml,$c]=$this->incoming();DB::table('voice_inbound_devices')->update(['last_seen_at'=>now()->subSeconds(61)]);app(QueueOperationSettings::class)->sweep();$this->assertDatabaseHas('voice_agent_presence',['user_id'=>$this->agent->id,'status'=>'paused']);$this->assertDatabaseHas('voice_inbound_calls',['id'=>$c->id,'capacity_released_at'=>null]);$this->assertStringContainsString('Conexão de voz',DB::table('voice_agent_presence')->value('pause_reason'));Http::assertNothingSent();}
 public function test_configuration_validates_and_preserves_defaults_without_calls():void {$this->actingAs($this->admin);$url='/api/voice/operations/queues/'.$this->queue;$d=['name'=>'QA','direction'=>'inbound','mode'=>'progressive','strategy'=>'fifo','wrapup_seconds'=>0,'agent_ids'=>[$this->agent->id],'revision'=>0,'schedule_enabled'=>true,'schedule_timezone'=>'UTC','schedule_days'=>[1,2],'schedule_start'=>'08:00','schedule_end'=>'18:00','missed_offer_limit'=>2,'allow_international'=>false];$this->putJson($url,$d+['agent_ring_seconds'=>0])->assertUnprocessable();$this->putJson($url,$d+['recording_enabled'=>true,'calling_method'=>'sip_trunk'])->assertUnprocessable();$this->putJson($url,$d)->assertOk();$this->assertDatabaseHas('voice_live_queues',['id'=>$this->queue,'schedule_enabled'=>true,'recording_enabled'=>false,'allow_international'=>false]);$this->assertDatabaseCount('voice_inbound_calls',0);Http::assertNothingSent();}
 public function test_recording_callback_uses_signed_parent_and_does_not_regress_or_extend_retention():void {$c=$this->recorded();$d=$this->payload($c,'completed');$url='/recordings/inbound/'.$c->id;$signature=(new \Twilio\Security\RequestValidator('test-token'))->computeSignature(\App\Services\TwilioVoiceConnection::BASE.$url,$d);$headers=['CONTENT_TYPE'=>'application/x-www-form-urlencoded','HTTP_ACCEPT'=>'application/json'];$this->call('POST','/callbacks/twilio/voice'.$url,$d,[],[],$headers+['HTTP_X_TWILIO_SIGNATURE'=>'bad'],http_build_query($d))->assertForbidden();$this->call('POST','/callbacks/twilio/voice'.$url,$d,[],[],$headers+['HTTP_X_TWILIO_SIGNATURE'=>$signature],http_build_query($d))->assertNoContent();$expires=DB::table('voice_recordings')->value('expires_at');$this->travel(1)->days();app(VoiceRecordings::class)->callback('inbound',$c->id,$this->payload($c));$this->assertDatabaseCount('voice_recordings',1);$this->assertDatabaseHas('voice_recordings',['status'=>'completed','expires_at'=>$expires]);Http::assertNothingSent();}
 public function test_recording_pause_resume_access_and_no_regression():void {$c=$this->recorded();$sid=$this->payload($c)['RecordingSid'];$api='https://api.twilio.com/2010-04-01/Accounts/'.$c->account_sid.'/Calls/'.$c->call_sid.'/Recordings/'.$sid.'.json';Http::fake([$api=>Http::sequence()->push(['sid'=>$sid,'account_sid'=>$c->account_sid,'call_sid'=>$c->call_sid,'status'=>'paused'])->push(['sid'=>$sid,'account_sid'=>$c->account_sid,'call_sid'=>$c->call_sid,'status'=>'in-progress'])]);$this->actingAs($this->agent)->postJson('/api/voice/recordings/'.$sid.'/control',['status'=>'paused'])->assertNoContent();app(VoiceRecordings::class)->callback('inbound',$c->id,$this->payload($c));$this->assertDatabaseHas('voice_recordings',['id'=>$sid,'status'=>'paused']);$this->postJson('/api/voice/recordings/'.$sid.'/control',['status'=>'in-progress'])->assertNoContent();$outsider=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'agent']);$this->actingAs($outsider)->getJson('/api/voice/recordings/calls/inbound/'.$c->id)->assertForbidden();$this->postJson('/api/voice/recordings/'.$sid.'/control',['status'=>'paused'])->assertForbidden();Http::assertSentCount(2);}
 public function test_retention_blocks_playback_and_retries_failed_provider_delete():void {$c=$this->recorded();$sid=$this->payload($c)['RecordingSid'];app(VoiceRecordings::class)->callback('inbound',$c->id,$this->payload($c,'completed'));DB::table('voice_recordings')->update(['expires_at'=>now()->subMinute(),'status'=>'paused']);$this->actingAs($this->agent)->get('/api/voice/recordings/'.$sid.'/audio')->assertStatus(410);Http::assertNothingSent();$api='https://api.twilio.com/2010-04-01/Accounts/'.$c->account_sid.'/Recordings/'.$sid.'.json';Http::fake([$api=>Http::sequence()->push([],503)->push([],204)]);$this->assertSame(0,app(VoiceRecordings::class)->purge());$this->assertDatabaseHas('voice_recordings',['id'=>$sid,'deleted_at'=>null]);$this->assertSame(1,app(VoiceRecordings::class)->purge());$this->assertSame(0,app(VoiceRecordings::class)->purge());Http::assertSentCount(2);}
 public function test_recording_off_remains_off_and_agent_cannot_change_queue():void {[$xml,$c]=$this->incoming();$this->assertStringContainsString('do-not-record',$xml);$this->assertNull($c->recording_policy);$this->actingAs($this->agent)->getJson('/api/voice/recordings/calls/inbound/'.$c->id)->assertOk()->assertJsonPath('enabled',false);$offer=DB::table('voice_inbound_offers')->where('call_id',$c->id)->first();app(InboundVoice::class)->finish($offer->id,['AccountSid'=>$c->account_sid,'CallSid'=>$c->call_sid,'DialCallStatus'=>'no-answer']);$this->assertDatabaseHas('voice_agent_queue_counters',['user_id'=>$this->agent->id,'missed_offers'=>0]);$this->putJson('/api/voice/operations/queues/'.$this->queue,[])->assertForbidden();Http::assertNothingSent();}
 public function test_audio_is_proxied_only_to_owner_and_never_uses_callback_url():void {$c=$this->recorded();$sid=$this->payload($c)['RecordingSid'];app(VoiceRecordings::class)->callback('inbound',$c->id,$this->payload($c,'completed')+['RecordingUrl'=>'http://127.0.0.1/private']);$api='https://api.twilio.com/2010-04-01/Accounts/'.$c->account_sid.'/Recordings/'.$sid.'.mp3';Http::fake([$api=>Http::response('synthetic-mp3',200,['Content-Type'=>'audio/mpeg'])]);$this->actingAs($this->agent)->get('/api/voice/recordings/'.$sid.'/audio')->assertOk()->assertContent('synthetic-mp3');$other=User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'agent']);$this->actingAs($other)->get('/api/voice/recordings/'.$sid.'/audio')->assertForbidden();Http::assertSentCount(1);}

}
