<?php
namespace App\Services;
use Carbon\CarbonImmutable;
use Illuminate\Support\Facades\{DB,Http};
class ChannelCosts {
 public const CHANNELS=['voice_outbound','voice_inbound','whatsapp_api','whatsapp_qr'];
 public const SCOPE='Valores informados pelos recursos da Twilio, separados por moeda. Não incluem mensalidades, impostos, infraestrutura QR ou serviços adicionais que não constam nesses recursos. Custos ausentes não são zero; este relatório não substitui a fatura.';
 public static function amount(mixed $price,mixed $unit):array {$unit=is_string($unit)?strtoupper($unit):'';if(!is_scalar($price)||!preg_match('/^-?\d{1,9}(?:\.\d{1,6})?$/D',(string)$price)||!preg_match('/^[A-Z]{3}$/D',$unit))return [null,null];return [number_format(abs((float)$price),6,'.',''),$unit];}
 private function get(array $c,string $resource,string $sid):array {abort_unless(preg_match('/^AC[a-fA-F0-9]{32}$/D',$c['account_sid']??'')&&preg_match($resource==='Calls'?'/^CA[a-fA-F0-9]{32}$/D':'/^(SM|MM)[a-fA-F0-9]{32}$/D',$sid),422,'Identificador de provedor inválido.');try{$r=Http::withBasicAuth($c['api_key'],$c['api_secret'])->acceptJson()->connectTimeout(3)->timeout(8)->withoutRedirecting()->get('https://api.twilio.com/2010-04-01/Accounts/'.$c['account_sid'].'/'.$resource.'/'.$sid.'.json');}catch(\Illuminate\Http\Client\ConnectionException){abort(502,'Provedor sem resposta. Nenhuma chamada ou mensagem foi criada.');}abort_unless($r->successful()&&$r->json('sid')===$sid&&$r->json('account_sid')===$c['account_sid'],502,'O provedor não confirmou a correlação do registro.');return $r->json();}
 public function sync(int $w,int $u,string $channel,string $id):array {
  abort_unless(in_array($channel,self::CHANNELS,true),422);abort_if($channel==='whatsapp_qr',422,'O QR não informa custos de provedor por mensagem.');
  if($channel==='voice_outbound'){$c=DB::table('voice_outbound_calls')->where('workspace_id',$w)->where('id',$id)->firstOrFail();abort_unless($c->capacity_released_at,409,'Aguarde o encerramento confirmado.');$r=app(VoiceProviderCatalog::class)->costs($w,$id);app(VoiceLab::class)->audit($w,$u,'costs.synced',$id,['channel'=>$channel]);return $r;}
  $saved=[];
  if($channel==='voice_inbound'){
   $row=DB::table('voice_inbound_calls')->where('workspace_id',$w)->where('id',$id)->firstOrFail();abort_unless($row->capacity_released_at,409,'Aguarde o encerramento confirmado.');$cfg=app(TwilioVoiceConnection::class)->read();abort_unless($cfg&&$cfg['account_sid']===$row->account_sid,409,'Credenciais da conta receptiva indisponíveis.');
   $n=$this->get($cfg,'Calls',$row->call_sid);abort_unless(($n['from']??'')===$row->from_number&&($n['to']??'')===$row->to_number,502,'Origem ou destino divergente.');$saved[]=[$row->call_sid,'incoming',$n];
   foreach(DB::table('voice_inbound_offers')->where('call_id',$id)->whereNotNull('child_sid')->get()as $offer){$n=$this->get($cfg,'Calls',$offer->child_sid);abort_unless(($n['parent_call_sid']??'')===$row->call_sid&&($n['to']??'')==='client:'.$offer->identity,502,'A perna do atendente não corresponde ao atendimento.');$saved[]=[$offer->child_sid,'agent',$n];}
  }else{
   $row=DB::table('wa_messages')->where('workspace_id',$w)->where('id',$id)->where('provider','twilio')->firstOrFail();$cfg=app(TwilioWhatsAppConnection::class)->require();abort_unless($cfg['account_sid']===$row->account_sid&&$row->provider_sid,409,'Mensagem sem identificador confirmado nesta conta.');$n=$this->get($cfg,'Messages',$row->provider_sid);abort_unless(($n['from']??'')==='whatsapp:'.$row->from_number&&($n['to']??'')==='whatsapp:'.$row->to_number,502,'A mensagem não corresponde aos números registrados.');$saved[]=[$row->provider_sid,'message',$n];
  }
  return DB::transaction(function()use($saved,$w,$u,$channel,$id){$pending=0;foreach($saved as [$sid,$leg,$n]){[$amount,$currency]=self::amount($n['price']??null,$n['price_unit']??null);$key=['workspace_id'=>$w,'channel'=>$channel,'provider_sid'=>$sid];$old=DB::table('ma_channel_costs')->where($key)->lockForUpdate()->first();abort_if($old&&$old->reference_id!==$id,409,'Custo já vinculado a outro registro.');if($amount===null){$pending++;if($old&&$old->amount!==null)continue;}DB::table('ma_channel_costs')->updateOrInsert($key,['reference_id'=>$id,'leg'=>$leg,'amount'=>$amount,'currency'=>$currency,'synced_at'=>now()]);}app(VoiceLab::class)->audit($w,$u,'costs.synced',$id,['channel'=>$channel,'components'=>count($saved)]);return ['legs'=>count($saved),'pending'=>$pending];});
 }
 public function report(int $w,string $from,string $to,string $channel='',int $page=1,string $zone='America/Sao_Paulo'):array {
  $start=CarbonImmutable::parse($from,$zone)->utc();$end=CarbonImmutable::parse($to,$zone)->addDay()->utc();$rows=[];
  $out=DB::table('voice_outbound_calls')->where('workspace_id',$w)->where('created_at','>=',$start)->where('created_at','<',$end)->get();$legacy=DB::table('voice_call_costs')->whereIn('call_id',$out->pluck('id'))->get()->groupBy('call_id');
  foreach($out as $c){$costs=$legacy->get($c->id,collect());$expected=array_filter([$c->channel_id,$c->provider_child_sid]);$complete=count($expected)>0&&$c->capacity_released_at&&count(array_diff($expected,$costs->filter(fn($x)=>$x->amount!==null&&$x->currency)->pluck('provider_sid')->all()))===0; if($c->answered_at&&!$c->provider_child_sid)$complete=false;$rows[]=$this->row($c,'voice_outbound',$c->destination,$c->method,$costs,$complete,$c->method==='programmable_voice'&&$c->channel_id&&$c->capacity_released_at);}
  $incoming=DB::table('voice_inbound_calls')->where('workspace_id',$w)->where('created_at','>=',$start)->where('created_at','<',$end)->get();$offers=DB::table('voice_inbound_offers')->whereIn('call_id',$incoming->pluck('id'))->get()->groupBy('call_id');$ledger=DB::table('ma_channel_costs')->where('workspace_id',$w)->where('channel','voice_inbound')->whereIn('reference_id',$incoming->pluck('id'))->get()->groupBy('reference_id');
  foreach($incoming as $c){$costs=$ledger->get($c->id,collect());$legs=$offers->get($c->id,collect());$expected=array_merge([$c->call_sid],$legs->pluck('child_sid')->filter()->all());$missing=$legs->contains(fn($o)=>$o->answered_at&&!$o->child_sid);$complete=$c->capacity_released_at&&!$missing&&count(array_diff($expected,$costs->filter(fn($x)=>$x->amount!==null&&$x->currency)->pluck('provider_sid')->all()))===0;$rows[]=$this->row($c,'voice_inbound',$c->from_number,'twilio',$costs,$complete,(bool)$c->capacity_released_at);}
  $messages=DB::table('wa_messages')->where('workspace_id',$w)->where('created_at','>=',$start)->where('created_at','<',$end)->get();$ledger=DB::table('ma_channel_costs')->where('workspace_id',$w)->where('channel','whatsapp_api')->whereIn('reference_id',$messages->pluck('id'))->get()->groupBy('reference_id');foreach($messages as $m){$qr=$m->provider==='qr';$costs=$qr?collect():$ledger->get($m->id,collect());$complete=$m->provider_sid&&$costs->contains(fn($x)=>$x->provider_sid===$m->provider_sid&&$x->amount!==null&&$x->currency);$rows[]=$this->row($m,$qr?'whatsapp_qr':'whatsapp_api',$m->direction==='inbound'?$m->from_number:$m->to_number,$m->provider,$costs,$complete,!$qr&&(bool)$m->provider_sid);}
  $all=collect($rows);$channels=[];$totals=[];foreach(self::CHANNELS as $key){$group=$all->where('channel',$key);$known=[];foreach($group as $row)foreach($row['components']as $cost)if($cost['amount']!==null&&$cost['currency']){$currency=strtoupper($cost['currency']);$micros=(int)round((float)$cost['amount']*1000000);$known[$currency]=($known[$currency]??0)+$micros;$totals[$currency]=($totals[$currency]??0)+$micros;}$channels[]=['channel'=>$key,'records'=>$group->count(),'complete'=>$group->where('cost_status','complete')->count(),'partial'=>$group->where('cost_status','partial')->count(),'unknown'=>$group->whereIn('cost_status',['pending','unavailable'])->count(),'known'=>array_map(fn($currency,$v)=>['currency'=>$currency,'amount'=>number_format($v/1000000,6,'.','')],array_keys($known),array_values($known))];}
  $filtered=$channel?$all->where('channel',$channel):$all;$filtered=$filtered->sortByDesc('created_at')->values();return ['channels'=>$channels,'known'=>array_map(fn($currency,$v)=>['currency'=>$currency,'amount'=>number_format($v/1000000,6,'.','')],array_keys($totals),array_values($totals)),'rows'=>['data'=>$filtered->slice(($page-1)*25,25)->values(),'total'=>$filtered->count(),'current_page'=>$page,'last_page'=>max(1,(int)ceil($filtered->count()/25))],'scope'=>self::SCOPE,'timezone'=>$zone];
 }
 private function row(object $r,string $channel,string $phone,string $provider,$costs,bool $complete,bool $sync):array {$known=$costs->filter(fn($c)=>$c->amount!==null&&$c->currency)->isNotEmpty();return ['id'=>$r->id,'channel'=>$channel,'phone'=>$phone,'provider'=>$provider,'status'=>$r->status,'direction'=>$r->direction??null,'created_at'=>$r->created_at,'can_sync'=>$sync,'cost_status'=>$channel==='whatsapp_qr'?'unavailable':($complete?'complete':($known?'partial':'pending')),'components'=>$costs->map(fn($c)=>['leg'=>$c->leg,'amount'=>$c->amount,'currency'=>$c->currency,'synced_at'=>$c->synced_at])->values()->all()];}
}
