<?php
namespace App\Services;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class TechnicalRetention {
 public const TABLES=['audio'=>'voice_audio_sessions','session'=>'ma_embed_sessions','delivery'=>'ma_event_deliveries'];
 public function policy(int $w):array {$p=DB::table('ma_retention_policies')->where('workspace_id',$w)->first();return $p?(array)$p:['workspace_id'=>$w,'audio_days'=>90,'session_days'=>30,'delivery_days'=>90,'automatic'=>false,'revision'=>0];}
 public function eligible(int $w,string $kind,array $p){$q=DB::table(self::TABLES[$kind])->whereNull('archived_at');$cutoff=now()->subDays($p[$kind.'_days']);if($kind==='audio')return $q->where('workspace_id',$w)->whereIn('status',['ended','cancelled','expired','failed'])->where('expires_at','<',now())->where('updated_at','<',$cutoff);$q->whereIn('integration_id',DB::table('ma_integrations')->where('workspace_id',$w)->select('id'));return $kind==='session'?$q->where('expires_at','<',$cutoff):$q->whereIn('status',['delivered','cancelled'])->whereNull('locked_until')->where('updated_at','<',$cutoff);}
 public function preview(int $w):array {$p=$this->policy($w);$counts=[];foreach(self::TABLES as $k=>$t)$counts[$k]=$this->eligible($w,$k,$p)->count();return ['policy'=>$p,'eligible'=>$counts,'runs'=>DB::table('ma_retention_runs')->where('workspace_id',$w)->orderByDesc('created_at')->limit(20)->get()];}
 public function save(int $w,int $u,array $d):array {return DB::transaction(function()use($w,$u,$d){DB::table('voice_runtime')->where('id',1)->lockForUpdate()->firstOrFail();$old=$this->policy($w);abort_unless($old['revision']===$d['revision'],409,'A política mudou. Atualize antes de salvar.');$d['revision']++;DB::table('ma_retention_policies')->updateOrInsert(['workspace_id'=>$w],$d+['created_at'=>$old['created_at']??now(),'updated_at'=>now()]);app(VoiceLab::class)->audit($w,$u,'retention.policy',$w,$d);return $this->policy($w);});}
 public function archive(int $w,?int $u,string $key,int $revision,int $limit=500,bool $scheduled=false):array {return DB::transaction(function()use($w,$u,$key,$revision,$limit,$scheduled){DB::table('voice_runtime')->where('id',1)->lockForUpdate()->firstOrFail();$old=DB::table('ma_retention_runs')->where('workspace_id',$w)->where('request_key',$key)->first();if($old)return ['id'=>$old->id,'counts'=>json_decode($old->counts,true),'duplicate'=>true];$p=$this->policy($w);abort_unless($p['revision']===$revision,409,'A política mudou. Recalcule a prévia.');abort_if($scheduled&&!$p['automatic'],409,'Arquivamento automático desativado.');$id=(string)Str::uuid();$counts=[];$limit=max(1,min(500,$limit));foreach(self::TABLES as $kind=>$table){$ids=$this->eligible($w,$kind,$p)->orderBy('id')->limit($limit)->lockForUpdate()->pluck('id');$counts[$kind]=$this->eligible($w,$kind,$p)->whereIn('id',$ids)->update(['archived_at'=>now(),'archive_batch_id'=>$id]);}DB::table('ma_retention_runs')->insert(['id'=>$id,'workspace_id'=>$w,'user_id'=>$u,'request_key'=>$key,'policy_revision'=>$revision,'counts'=>json_encode($counts),'created_at'=>now()]);app(VoiceLab::class)->audit($w,$u,'retention.archived',$id,$counts);return ['id'=>$id,'counts'=>$counts,'duplicate'=>false];});}
 public function restore(int $w,int $u,string $id):array{return DB::transaction(function()use($w,$u,$id){DB::table('voice_runtime')->where('id',1)->lockForUpdate()->firstOrFail();$run=DB::table('ma_retention_runs')->where('workspace_id',$w)->where('id',$id)->firstOrFail();if($run->restored_at)return ['restored'=>true,'duplicate'=>true];foreach(self::TABLES as $table)DB::table($table)->where('archive_batch_id',$id)->update(['archived_at'=>null,'archive_batch_id'=>null]);DB::table('ma_retention_runs')->where('id',$id)->update(['restored_at'=>now()]);app(VoiceLab::class)->audit($w,$u,'retention.restored',$id);return ['restored'=>true,'duplicate'=>false];});}
}
