<script setup>
import { ref,watch } from 'vue'
const props=defineProps({journeyId:Number,contacts:{type:Array,default:()=>[]},mode:String})
const open=ref(false),data=ref(null),detail=ref(null),error=ref(''),busy=ref(false),contact=ref(''),test=ref(null),page=ref(1)
const statuses={pending:'Pendente',dialing:'Discando',answered:'Atendida',completed:'Atendida e encerrada',no_answer:'Não atendeu',busy:'Ocupado',failed:'Falha',cancelled:'Cancelada',unknown:'A conferir',sent:'Enviada',delivered:'Entregue',read:'Lida',received:'Recebida',undelivered:'Não entregue',queued:'Na fila',sending:'Enviando'}
const reasons={answered:'Atendeu',replied:'Respondeu',attempts_exhausted:'Tentativas esgotadas',no_response:'Sem resposta',message_failed:'Falha na mensagem',source_left:'Saiu do segmento',cancelled:'Cancelada',opt_out:'Descadastro / sem autorização'}
async function api(path,body){const r=await fetch('/api/voice/journeys/'+props.journeyId+path,{method:body?'POST':'GET',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.message||'Não foi possível consultar.');return d}
async function run(fn){busy.value=true;error.value='';try{await fn()}catch(e){error.value=e.message}finally{busy.value=false}}
function load(){return run(async()=>{data.value=await api('/executions?page='+page.value);detail.value=null})}
function preview(){return run(async()=>{test.value=await api('/entries/preview',{contact_id:Number(contact.value),event_key:'teste:'+crypto.randomUUID()})})}
watch(()=>props.journeyId,()=>{data.value=null;detail.value=null;test.value=null;open.value=false;page.value=1})
</script>
<template><section class="executions"><button type="button" class="secondary" @click="open=!open;if(open)load()">{{open?'Ocultar participações':'Histórico de participações'}}</button><template v-if="open"><p v-if="error" role="alert">{{error}}</p><p v-if="data&&!data.configured">Salve a política no cartão Entrada para organizar o histórico em participações.</p><p v-if="data?.runs&&!data.runs.total">Nenhuma participação registrada.</p><article v-for="row in data?.runs.data||[]" :key="row.id"><button type="button" @click="run(async()=>detail=await api('/executions/'+row.id))"><strong>{{row.name}} · #{{row.number}}</strong><small>{{reasons[row.exit_reason]||(row.status==='waiting'?'Aguardando resposta':'Em andamento')}} · {{row.calls}} chamadas · {{row.messages}} mensagens</small></button></article><div v-if="data?.runs.last_page>1"><button type="button" :disabled="page===1||busy" @click="page--;load()">Anterior</button> {{page}} / {{data.runs.last_page}} <button type="button" :disabled="page===data.runs.last_page||busy" @click="page++;load()">Próxima</button></div><div v-if="detail" class="detail"><strong>Participação #{{detail.run.number}}</strong><small>{{detail.run.entered_at}} → {{detail.run.ended_at||'em andamento'}}</small><p v-for="c in detail.calls" :key="c.id">☎ {{c.destination}} · {{statuses[c.status]||c.status}} · {{c.started_at}}</p><p v-for="m in detail.messages" :key="m.id">{{m.direction==='inbound'?'Resposta':'Mensagem'}} · {{statuses[m.status]||m.status}}<br>{{m.body||m.button_label||'Template'}} · {{m.created_at}}</p></div><template v-if="mode==='event'"><h4>Testar elegibilidade do evento</h4><label>Contato<select v-model="contact"><option value="">Selecione</option><option v-for="c in contacts" :value="c.id">{{c.name}} · {{c.phone}}</option></select></label><button type="button" class="secondary" :disabled="!contact||busy" @click="preview">Testar sem inserir na jornada</button><p v-if="test">{{test.eligible?'Elegível para uma nova participação.':test.reason}} Nenhuma chamada, mensagem ou participação foi criada.</p></template></template></section></template>
<style scoped>
.executions{margin:20px 0;padding:16px;border:1px solid #e2e5d9;border-radius:12px;font-size:12px}.executions article{border-bottom:1px solid #e2e5d9;padding:13px 0}.executions article button{display:block;text-align:left}.executions small{display:block;font-size:10px;line-height:1.8;color:#818975}.executions p{font-size:11px;line-height:1.7;overflow-wrap:anywhere}.detail{padding:15px;background:#f7f5eb;margin:15px 0;border-radius:10px}.executions h4{margin:20px 0}
</style>
