<script setup>
import { computed, ref } from 'vue'
const props=defineProps({modelValue:Object,journeyId:Number,contacts:{type:Array,default:()=>[]}})
const emit=defineEmits(['update:modelValue'])
const policy=computed(()=>props.modelValue)
const choices=[['once','Uma única vez'],['segment_return','Ao sair e voltar ao segmento'],['interval','Após um intervalo'],['event','Por novo evento']]
const reasons={answered:'Atendeu à ligação',replied:'Respondeu ao WhatsApp',attempts_exhausted:'Esgotou as tentativas',no_response:'WhatsApp sem resposta',message_failed:'Mensagem com falha confirmada',source_left:'Saiu do segmento',cancelled:'Execução cancelada'}
const descriptions={once:'O contato participa uma vez. Permanecer no segmento não reinicia a jornada.',segment_return:'Uma nova participação exige uma saída e um retorno ao segmento. Alterar a configuração não conta como retorno.',interval:'O prazo começa no encerramento da participação anterior. O contato precisa continuar elegível no segmento.',event:'Cada evento autorizado pode iniciar uma participação. Eventos repetidos não duplicam entradas; eventos recebidos durante uma participação são recusados, sem ficarem aguardando.'}
function change(key,value){emit('update:modelValue',{...policy.value,[key]:value})}
function toggle(key,on){change('exit_reasons',on?[...policy.value.exit_reasons,key]:policy.value.exit_reasons.filter(x=>x!==key))}
</script>
<template><section class="reentry-settings"><span class="eyebrow">ENTRADA E REENTRADA</span><h4>Quando este contato pode participar?</h4><label>Regra de participação<select aria-label="Regra de participação" :value="policy.mode" @change="change('mode',$event.target.value)"><option v-for="[key,label] in choices" :value="key">{{label}}</option></select></label><p>{{descriptions[policy.mode]}}</p><template v-if="policy.mode!=='once'"><label v-if="policy.mode==='interval'">Dias após o encerramento<input type="number" min="1" max="3650" :value="policy.interval_days" @input="change('interval_days',Number($event.target.value))" required></label><label>Máximo de participações por contato<input type="number" min="1" max="100" :value="policy.max_participations" @input="change('max_participations',Number($event.target.value))" required><small>Inclui a primeira participação e o histórico anterior.</small></label><details><summary>Encerramentos que permitem voltar · {{policy.exit_reasons.length}} selecionados</summary><label v-for="(label,key) in reasons" class="reason"><input type="checkbox" :checked="policy.exit_reasons.includes(key)" @change="toggle(key,$event.target.checked)">{{label}}</label></details></template><label>Espera por resposta ao WhatsApp (horas)<input type="number" min="1" max="720" :value="policy.reply_wait_hours" @input="change('reply_wait_hours',Number($event.target.value))" required><small>Após o envio confirmado, define quando encerrar como sem resposta. Entrega incerta exige conferência.</small></label><p class="note">Cada participação tem suas tentativas e mensagens. O histórico, os limites globais e o descadastro são preservados. Nunca há duas participações simultâneas nesta jornada.</p><p v-if="policy.exit_reasons.includes('replied')&&policy.mode!=='once'" class="note">Quem respondeu só poderá voltar depois de encerrar a conversa na caixa de atendimento.</p><details v-if="policy.mode==='event'"><summary>Como enviar o evento</summary><p>Em Integrações, crie uma credencial com o escopo <b>journeys:write</b> e acesso ao segmento desta cadência. Use no servidor integrador.</p><code>POST /api/v1/journeys/{{journeyId}}/entries</code><pre>{ "contact_id": 123,
  "event_key": "pedido:456" }</pre><p>Envie Authorization: Bearer e Idempotency-Key (UUID). A resposta informa se entrou, o motivo de bloqueio ou se o evento já foi recebido. Um webhook de atualização cadastral, sozinho, não reinicia a jornada.</p></details></section></template>
<style scoped>
.reentry-settings{border:1px solid #e5dfcf;background:#fbfaf5;border-radius:14px;padding:18px;margin:20px 0}.reentry-settings h4{font-size:15px;margin:0 0 18px}.reentry-settings p,.reentry-settings small{font-size:11px;line-height:1.7;color:#767e6e}.reentry-settings label{margin:16px 0}.reentry-settings .reason{display:flex;flex-direction:row;align-items:center;gap:9px;font-size:12px}.reason input{width:16px}.reentry-settings summary{cursor:pointer;font-size:12px;margin:15px 0}.reentry-settings code,.reentry-settings pre{font-size:11px;white-space:pre-wrap;overflow-wrap:anywhere}.note{border-top:1px solid #e5dfcf;padding-top:12px}
</style>
