<script setup>
import {ref,watch} from 'vue'
import {Plus,Search,X,Link2,Pencil,ChevronRight} from 'lucide-vue-next'
const props=defineProps({initialKind:{type:String,default:'segment'},modal:Boolean})
const emit=defineEmits(['close'])
const kinds={segment:'Segmentos',campaign:'Campanhas',list:'Listas do CRM',template:'Templates',field:'Campos do contato',tag:'Tags',stage:'Estágios',user:'Responsáveis',form:'Formulários',goal:'Metas',pipeline:'Funis',store:'Lojas',sender:'Remetentes'}
const kind=ref(props.initialKind),q=ref(''),items=ref([]),page=ref(1),more=ref(false),loading=ref(false),error=ref(''),message=ref(''),form=ref(null),editing=ref(false),parameterNames=ref(''),buttonNames=ref('')
let serial=0
async function load(next=false){const seq=++serial;loading.value=true;try{const r=await fetch('/api/crm/catalog?'+new URLSearchParams({kind:kind.value,q:q.value,page:String(next?page.value+1:1)}),{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Não foi possível carregar o catálogo.');const d=await r.json();if(seq!==serial)return;items.value=next?[...items.value,...d.data]:d.data;page.value=d.page;more.value=d.has_more;error.value=''}catch(e){error.value=e.message}finally{if(seq===serial)loading.value=false}}
watch(kind,()=>{form.value=null;q.value='';load()},{immediate:true})
function start(item=null){editing.value=!!item;form.value=item?JSON.parse(JSON.stringify(item)):{kind:kind.value,external_id:'',name:'',channel:involvesChannel()?'email':null,active:true,metadata:{}};form.value.metadata ||= {};parameterNames.value=(form.value.metadata?.parameters||[]).join(', ');buttonNames.value=(form.value.metadata?.buttons||[]).join(', ');error.value='';message.value=''}
function involvesChannel(){return ['campaign','template','sender'].includes(kind.value)}
async function save(){loading.value=true;error.value='';try{const payload={kind:kind.value,external_id:form.value.external_id,name:form.value.name,channel:form.value.channel||null,active:form.value.active,metadata:{...form.value.metadata}};if(kind.value==='template'){payload.metadata.parameters=parameterNames.value.split(',').map(s=>s.trim()).filter(Boolean);payload.metadata.buttons=buttonNames.value.split(',').map(s=>s.trim()).filter(Boolean)}const r=await fetch('/api/crm/catalog',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.errors?Object.values(d.errors).flat().join(' · '):d.message);form.value=null;message.value='Referência salva. Ela já pode ser selecionada nos nós.';await load()}catch(e){error.value=e.message}finally{loading.value=false}}
</script>
<template>
 <section :class="['crm-catalog-panel',{embedded:modal}]">
  <div class="catalog-heading"><div><span class="eyebrow">PREPARAÇÃO PARA O CRM</span><h2>Referências do CRM</h2><p>Prepare os recursos que serão usados nas jornadas. A sincronização futura atualizará os nomes mantendo seus IDs.</p></div><button v-if="modal" title="Voltar às configurações" @click="emit('close')"><X :size="20"/></button></div>
  <div class="catalog-info"><Link2 :size="18"/><div><strong>Referências, sem duplicar seu CRM</strong><p>Informar um segmento ou uma campanha aqui não cria nem altera esse recurso no CRM. Você está preparando sua seleção nos nós.</p></div></div>
  <div class="catalog-toolbar"><select aria-label="Tipo de referência" v-model="kind"><option v-for="(label,key) in kinds" :value="key">{{label}}</option></select><div class="search"><Search :size="15"/><input v-model="q" @keyup.enter="load()" placeholder="Nome ou ID" aria-label="Buscar referências"><button @click="load()">Buscar</button></div><button class="primary" @click="start()"><Plus :size="16"/> Adicionar referência</button></div>
  <div v-if="message" class="catalog-message">{{message}}</div><div v-if="error" class="error" role="alert">{{error}}</div>
  <form v-if="form" class="catalog-form" @submit.prevent="save"><h3>{{editing?'Editar referência':'Nova referência'}} · {{kinds[kind]}}</h3><div class="form-row"><label>Nome para exibição<input v-model="form.name" required maxlength="200" placeholder="Ex.: Leads qualificados"></label><label>ID no CRM<input v-model="form.external_id" required :disabled="editing" maxlength="160" placeholder="Ex.: segmento_qualificados"></label></div><small class="config-hint">Use o identificador que o CRM enviará nos eventos e no catálogo. Esta referência fica marcada como preparada até ser confirmada pela sincronização.</small><div class="form-row"><label v-if="involvesChannel()">Canal<select v-model="form.channel" required><option value="email">E-mail</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></select></label><label v-if="kind==='field'">Tipo de campo<select v-model="form.metadata.data_type"><option value="text">Texto</option><option value="number">Número</option><option value="date">Data</option><option value="boolean">Sim / Não</option></select></label></div><label>Descrição <textarea v-model="form.metadata.description" rows="2" maxlength="1000"/></label><template v-if="kind==='template'"><div class="form-row"><label>ID da campanha vinculada <small>Opcional</small><input v-model="form.metadata.campaign_id" placeholder="Mesmo ID cadastrado em Campanhas"></label><label>Idioma<input v-model="form.metadata.language" placeholder="pt_BR"></label></div><label v-if="form.channel==='email'">Assunto sugerido<input v-model="form.metadata.subject" maxlength="200"></label><label>Parâmetros do template <small>Separados por vírgula</small><input v-model="parameterNames" placeholder="nome, produto, data"></label><label v-if="form.channel==='whatsapp'">Identificadores dos botões <small>Separados por vírgula</small><input v-model="buttonNames" placeholder="quero_saber_mais, quero_agendar"></label></template><label class="check-label"><input v-model="form.active" type="checkbox">Disponível para seleção</label><div class="catalog-form-actions"><button type="button" class="secondary" @click="form=null">Cancelar</button><button class="primary" :disabled="loading">Salvar referência</button></div></form>
  <div v-else class="table-card"><table><thead><tr><th>Nome</th><th>ID no CRM</th><th>Canal</th><th>Origem</th><th></th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><strong>{{item.name}}</strong></td><td><code>{{item.external_id}}</code></td><td>{{item.channel||'—'}}</td><td><span :class="['status',item.origin==='crm'?'active':'draft']">{{item.origin==='crm'?'Sincronizado':'Preparado'}}</span></td><td><button v-if="item.origin!=='crm'" title="Editar referência" @click="start(item)"><Pencil :size="15"/></button><small v-else>Gerenciado pelo CRM</small></td></tr></tbody></table><div v-if="!items.length" class="empty-small">{{loading?'Carregando referências…':'Nenhuma referência encontrada. Adicione os nomes e IDs que pretende usar, ou aguarde a sincronização do CRM.'}}</div><button v-if="more" class="secondary catalog-more" :disabled="loading" @click="load(true)">Carregar mais <ChevronRight :size="14"/></button></div>
 </section>
</template>
