<script setup>
import {checkMicrophone,microphoneMessage} from '../voice/microphone'
import {ref,onMounted,onBeforeUnmount,computed,defineAsyncComponent} from 'vue'
const InboundReportsPanel=defineAsyncComponent(()=>import('./InboundReportsPanel.vue'))
import {PhoneIncoming,PhoneOff,RefreshCw} from 'lucide-vue-next'
import {isEmbedded,voiceBase,voiceAuth} from '../voice/embed-session'
import {voiceApi,stamp} from '../voice/operations'
const emit=defineEmits(['ready'])
const props=defineProps({supervisor:Boolean,codes:{type:Array,default:()=>[]}})
const state=ref(null),error=ref(''),busy=ref(false),online=ref(false),ringing=ref(false),talking=ref(false),from=ref(''),form=ref(null),target=ref(''),code=ref(''),notes=ref('')
let device=null,call=null,timer=null,refreshing=false,disposed=false
const session=crypto.randomUUID()
const current=computed(()=>state.value?.current)
const labels={waiting:'Em espera',ringing:'Chamando atendente',answered:'Em conversa',ending:'Encerrando',tabulation:'Tabulação pendente',completed:'Concluída',unavailable:'Sem atendente',abandoned:'Abandonada'}
async function api(path='',method='GET',d){return voiceApi('/inbound'+path,method,d)}
async function load(){state.value=await api()}
async function run(fn){busy.value=true;error.value='';try{await fn()}catch(e){error.value=microphoneMessage(e)}finally{busy.value=false}}
function edit(r){form.value=r?{...r,enabled:!!r.enabled}:{number:state.value?.configured_number||'',queue_id:'',enabled:false,ring_seconds:20,wait_seconds:120}}
async function save(){await api('/routes'+(form.value.id?'/'+form.value.id:''),form.value.id?'PUT':'POST',form.value);form.value=null;await load()}
async function refreshToken(){const g=await api('/token','POST',{session_id:session});device?.updateToken(g.access_token)}
async function connect(){if(call||current.value)throw Error('Conclua o atendimento atual antes de reconectar.');if(!state.value?.queues.length)throw Error('Solicite ao administrador um vínculo com uma fila receptiva.');if(device)await disconnect();await checkMicrophone();const g=await api('/token','POST',{session_id:session});const {Device}=await import('@twilio/voice-sdk');device=new Device(g.access_token,{edge:g.edge,logLevel:'silent',closeProtection:true});
 device.on('registered',async()=>{try{await api('/device','POST',{session_id:session,ready:true});online.value=true;emit('ready',true)}catch(e){error.value=microphoneMessage(e);disconnect()}})
 device.on('tokenWillExpire',()=>refreshToken().catch(e=>{error.value=microphoneMessage(e);disconnect()}))
 device.on('unregistered',()=>{online.value=false;emit('ready',false);api('/device','POST',{session_id:session,ready:false}).catch(()=>{})})
 device.on('error',e=>{error.value='A conexão receptiva precisa ser conferida. Reconecte quando a chamada terminar.';online.value=false;emit('ready',false);api('/device','POST',{session_id:session,ready:false}).catch(()=>{})})
 device.on('incoming',incoming=>{if(call){incoming.reject();return}call=incoming;ringing.value=true;from.value=incoming.parameters.From||'Número não identificado';incoming.on('accept',()=>{ringing.value=false;talking.value=true;load().catch(()=>{})});for(const e of ['disconnect','cancel','reject'])incoming.on(e,()=>{ringing.value=false;talking.value=false;call=null;load().catch(()=>{})});incoming.on('error',()=>{error.value='Falha no áudio receptivo. Consulte o resultado no servidor.';ringing.value=false;talking.value=false;call=null});load().catch(()=>{})});
 await device.register()
}
async function disconnect(){if(call){error.value='Conclua a chamada antes de desconectar o receptivo.';return}await api('/device','POST',{session_id:session,ready:false}).catch(()=>{});device?.destroy();device=null;online.value=false;emit('ready',false)}
async function tick(){if(disposed||refreshing)return;refreshing=true;try{if(online.value)await api('/device','POST',{session_id:session,ready:true});await load()}catch(e){error.value=microphoneMessage(e)}finally{refreshing=false}}
function beforeUnload(e){if(call||current.value){e.preventDefault();e.returnValue=''}}
function pageHide(){if(isEmbedded()){fetch(voiceBase()+'/inbound/device',{method:'POST',credentials:'omit',keepalive:true,headers:{'Content-Type':'application/json',...voiceAuth()},body:JSON.stringify({session_id:session,ready:false})}).catch(()=>{});return}navigator.sendBeacon('/api/voice/inbound/device',new Blob([JSON.stringify({session_id:session,ready:false,_token:document.querySelector('meta[name="csrf-token"]').content})],{type:'application/json'}))}
async function requestLeave(fn){if(call||current.value){error.value='Conclua o atendimento receptivo e a tabulação antes de sair.';return}await disconnect();fn()}
defineExpose({requestLeave})
onMounted(()=>{run(load);timer=setInterval(tick,15000);window.addEventListener('beforeunload',beforeUnload);window.addEventListener('pagehide',pageHide)})
onBeforeUnmount(()=>{disposed=true;clearInterval(timer);window.removeEventListener('beforeunload',beforeUnload);window.removeEventListener('pagehide',pageHide);if(device){pageHide();device.destroy()}})
</script>
<template><section class="inbound">
 <div class="heading"><div><span class="eyebrow">{{supervisor?'ROTA DE ENTRADA':'VOZ RECEPTIVA'}}</span><h2>{{supervisor?'Recebimento de chamadas':'Receber chamadas'}}</h2></div><button class="secondary" @click="run(load)"><RefreshCw :size="15"/>Atualizar</button></div>
 <p v-if="error" class="error" role="alert">{{error}}</p>
 <template v-if="supervisor"><p>Vincule cada número a uma fila receptiva ou de entrada e saída. O recebimento depende da rota ativa, da entrada habilitada na fila e de um agente disponível com o navegador conectado.</p><div class="actions"><button class="primary" @click="edit()">Vincular número de entrada</button><a class="secondary" href="#/queues">Gerenciar filas de atendimento</a></div><div v-if="state" class="table-card box"><p>Na Twilio, configure o número com <b>A call comes in → Webhook / POST</b>:</p><code>{{state.voice_url}}</code><p>Em <b>Call status changes / POST</b>:</p><code>{{state.status_url}}</code><p>Os dois callbacks são necessários para liberar a capacidade após o encerramento. Salve a rota e use “Aplicar na Twilio” para conectar os callbacks ao número. Uma rota existente de outro sistema não será substituída.</p></div><form v-if="form" class="table-card box" @submit.prevent="run(save)"><h3>Configurar rota</h3><label>Número de entrada<select v-model="form.number" required :disabled="!!form.id"><option value="">Selecione um número autorizado</option><option v-for="n in [...new Set([...(state?.available_numbers||[]),...(form.id?[form.number]:[])])]" :key="n" :value="n">{{n}}</option></select></label><small>Novos números próprios aparecem após sincronizar o catálogo da Twilio. Identificadores apenas verificados para saída não recebem chamadas.</small><label>Fila receptiva<select v-model.number="form.queue_id" required><option value="">Selecione</option><option v-for="q in state?.queues" :value="q.id">{{q.name}} · {{q.direction==='mixed'?'Entrada e saída':'Receptivo'}}</option></select></label><div class="grid"><label>Toque por atendente (segundos)<input type="number" v-model.number="form.ring_seconds" min="5" max="60"></label><label>Espera máxima (segundos)<input type="number" v-model.number="form.wait_seconds" min="10" max="600"></label></div><label class="check-label"><input type="checkbox" v-model="form.enabled">Rota ativa</label><button class="primary" :disabled="busy">Salvar rota</button> <button class="secondary" type="button" @click="form=null">Cancelar</button></form><div class="table-card box" v-for="r in state?.routes" :key="r.id"><strong>{{r.number}}</strong><p>{{state.queues.find(q=>q.id===r.queue_id)?.name}} · {{r.enabled?'Ativa':'Pausada'}} · toque {{r.ring_seconds}} s</p><div class="actions"><button class="secondary" @click="edit(r)">Editar rota</button><button class="primary" :disabled="busy" @click="run(async()=>{await api('/routes/'+r.id+'/publish','POST',{});await load()})">Aplicar na Twilio</button><small>{{r.provider_synced_at?'Configurada no provedor em '+stamp(r.provider_synced_at):'Configuração no provedor pendente'}}</small></div></div></template>
 <template v-else><p>Conecte o navegador às suas filas receptivas e depois clique em Ficar disponível acima. Conectar o áudio não muda sua disponibilidade nem inicia chamadas de saída.</p><p v-if="!state?.queues.length">Nenhuma fila receptiva atribuída. O administrador pode vinculá-lo em Filas de atendimento.</p><p v-else>Filas: {{state.queues.map(q=>q.name).join(' · ')}}</p><div class="actions"><button v-if="!online" class="primary" :disabled="busy||!!call||!state?.queues.length" @click="run(connect)"><PhoneIncoming :size="17"/>Conectar receptivo</button><button v-else class="secondary" :disabled="busy||!!call" @click="run(disconnect)">Desconectar receptivo</button><span :class="['status',online?'active':'paused']">{{online?'Receptivo conectado':'Receptivo desconectado'}}</span></div><div v-if="ringing||talking" class="table-card box"><h3>{{ringing?'Chamada recebida':'Em conversa'}} · {{from}}</h3><div class="actions"><button v-if="ringing" class="primary" @click="call?.accept()">Atender</button><button class="secondary" @click="ringing?call?.reject():call?.disconnect()"><PhoneOff :size="16"/>{{ringing?'Recusar':'Encerrar'}}</button></div><div v-if="talking&&current"><label>Transferir para outro atendente<select v-model.number="target"><option value="">Selecione</option><option v-for="a in state.agents.filter(a=>a.id!==state.user_id)" :value="a.id">{{a.name}}</option></select></label><button class="secondary" :disabled="busy||!target" @click="run(async()=>{await api('/calls/'+current.id+'/transfer','POST',{user_id:target});await load()})">Transferir atendimento</button><small>A transferência conecta o próximo atendente disponível. Se ele não atender, o chamador volta à distribuição da fila.</small></div></div><form v-if="current?.status==='tabulation'" class="table-card box" @submit.prevent="run(async()=>{await api('/calls/'+current.id+'/disposition','POST',{code,notes,revision:current.revision});code='';notes='';await load()})"><h3>Concluir atendimento · {{current.from_number}}</h3><label>Resultado<select v-model="code" required><option value="">Selecione</option><option v-for="c in codes" :value="c.code">{{c.label}}</option></select></label><label>Anotações<textarea v-model="notes" maxlength="2000"/></label><button class="primary" :disabled="busy">Salvar tabulação</button></form></template>
 <InboundReportsPanel v-if="supervisor"/><div v-else class="table-card box scroll"><h3>{{supervisor?'Histórico receptivo':'Seus atendimentos receptivos'}}</h3><table><thead><tr><th>Origem</th><th>Estado</th><th>Recebida em</th><th>Tabulação</th><th></th></tr></thead><tbody><tr v-for="c in state?.calls" :key="c.id"><td>{{c.from_number}}</td><td>{{labels[c.status]||c.status}}</td><td>{{stamp(c.created_at)}}</td><td>{{c.disposition_code||'—'}}</td><td><button v-if="!c.capacity_released_at" class="secondary" :disabled="busy" @click="run(async()=>{await api('/calls/'+c.id+'/reconcile','POST',{});await load()})">Conferir na Twilio</button></td></tr></tbody></table><p v-if="!state?.calls.length">Nenhuma chamada recebida.</p></div>
</section></template>
<style scoped>
.inbound{margin:24px 0;padding:24px;border:1px solid #e2e3d9;border-radius:18px;background:#fafbf7}.heading,.actions{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.actions{justify-content:flex-start}.box{padding:22px;margin:18px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.scroll{overflow:auto}.inbound p,.inbound small{color:#707969;line-height:1.7}.inbound small{display:block;margin-top:14px}.inbound label:not(.check-label){display:flex;flex-direction:column;gap:7px;margin:16px 0;font-size:13px}.inbound code{word-break:break-all;font-size:12px}.inbound select{padding:12px;border-radius:10px;border:1px solid #dbddcf;background:white}@media(max-width:650px){.inbound{padding:14px}.grid{grid-template-columns:1fr}.box{padding:14px}}
</style>
