<script setup>
import {ref,computed,onMounted} from 'vue'
import {RefreshCw,ArrowLeft} from 'lucide-vue-next'
import {voiceApi,stamp} from '../voice/operations'
const day=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)
const defaults=()=>({from:day(new Date(Date.now()-6*86400000)),to:day(new Date()),queue_id:'',user_id:'',outcome:''})
const filters=ref(defaults()),page=ref(1),data=ref(null),detail=ref(null),busy=ref(false),error=ref('')
const names={answered:'Atendidas',abandoned:'Abandonadas',unavailable:'Sem agente disponível',active:'Aguardando atendimento',total:'Recebidas no MA',tabulation:'Aguardando tabulação',completed:'Concluída',offered:'Ofertada',transferred:'Transferida',transfer_pending:'Transferência pendente','no-answer':'Não atendeu',failed:'Falhou',busy:'Ocupado',waiting:'Em espera',ringing:'Tocando',ending:'Encerrando',unknown:'Sem confirmação'}
const max=computed(()=>Math.max(1,...(data.value?.days||[]).map(d=>d.answered+d.abandoned+d.unavailable+d.active)))
async function load(){if(busy.value)return;busy.value=true;error.value='';try{const query=new URLSearchParams(Object.entries({...filters.value,page:page.value}).filter(([,v])=>v!==''));data.value=await voiceApi('/inbound/reports?'+query)}catch(e){error.value=e.message}finally{busy.value=false}}
async function open(id){busy.value=true;error.value='';try{detail.value=await voiceApi('/inbound/reports/'+id)}catch(e){error.value=e.message}finally{busy.value=false}}
function choose(outcome){filters.value.outcome=outcome==='total'?'':outcome;page.value=1;load()}
function chooseDay(date){filters.value.from=date;filters.value.to=date;page.value=1;load()}
function reset(){filters.value=defaults();page.value=1;detail.value=null;load()}
onMounted(load)
</script>
<template><section class="inbound-reports"><div class="report-heading"><div><span class="eyebrow">SUPERVISÃO RECEPTIVA</span><h2>Resultados das chamadas de entrada</h2><p>Veja o atendimento por período, fila e responsável. Clique nos indicadores para abrir os registros.</p></div><button class="secondary" :disabled="busy" @click="load"><RefreshCw :size="15"/>Atualizar relatório</button></div><p v-if="error" role="alert" class="error">{{error}}</p>
 <form class="report-filters" @submit.prevent="page=1;load()"><label>De<input v-model="filters.from" type="date" required></label><label>Até<input v-model="filters.to" type="date" required></label><label>Fila<select aria-label="Fila do relatório receptivo" v-model="filters.queue_id"><option value="">Todas</option><option v-for="q in data?.queues" :key="q.id" :value="q.id">{{q.name}}</option></select></label><label>Responsável final<select aria-label="Responsável do relatório receptivo" v-model="filters.user_id"><option value="">Todos</option><option v-for="u in data?.users" :key="u.id" :value="u.id">{{u.name}}</option></select></label><button class="primary" :disabled="busy">Aplicar filtros</button><button class="secondary" type="button" :disabled="busy" @click="reset">Últimos 7 dias</button></form>
 <template v-if="data"><div class="report-stats"><button v-for="key in ['total','answered','abandoned','unavailable','active']" :key="key" class="table-card" :class="{chosen:filters.outcome===key||key==='total'&&!filters.outcome}" :disabled="busy" @click="choose(key)"><span>{{names[key]}}</span><strong>{{data.counts[key]}}</strong><small>Ver detalhes →</small></button></div><p class="report-note">{{data.scope}} Fuso: {{data.timezone}}.</p><div class="report-secondary"><span>Taxa de atendimento: <b>{{data.answer_rate===null?'Sem dados':data.answer_rate+'%'}}</b></span><span>Espera média até atender: <b>{{data.average_wait_seconds===null?'Sem dados':data.average_wait_seconds+' s'}}</b></span><span>Transferidas: <b>{{data.counts.transferred}}</b></span><span>Tabulações pendentes: <b>{{data.counts.tabulation_pending}}</b></span></div>
 <article class="table-card report-chart"><h3>Distribuição por dia</h3><div class="legend"><span v-for="key in ['answered','abandoned','unavailable','active']" :class="key" :key="key">{{names[key]}}</span></div><div class="bars"><button v-for="d in data.days" :key="d.date" :disabled="busy" :aria-label="'Detalhar '+d.date+': '+(d.answered+d.abandoned+d.unavailable+d.active)+' chamadas'" @click="chooseDay(d.date)"><span class="bar-area"><i v-for="key in ['active','unavailable','abandoned','answered']" :key="key" :class="key" :style="{height:(d[key]/max*120)+'px'}"></i></span><small>{{d.date.slice(8)}}/{{d.date.slice(5,7)}}</small></button></div><p v-if="!data.counts.total">Nenhuma chamada receptiva registrada neste período.</p></article>
 <article class="table-card report-detail" v-if="detail"><div class="report-heading"><h3>Atendimento de {{detail.call.from_number}}</h3><button class="secondary" @click="detail=null"><ArrowLeft :size="15"/>Fechar detalhes</button></div><p>{{names[detail.call.outcome]}} · recebida {{stamp(detail.call.created_at)}} · {{detail.call.disposition_code||'Sem tabulação'}}</p><p v-if="detail.call.notes">{{detail.call.notes}}</p><h4>Distribuição entre atendentes</h4><div class="report-scroll"><table><thead><tr><th>Atendente</th><th>Resultado</th><th>Ofertada</th><th>Atendida</th><th>Encerrada</th></tr></thead><tbody><tr v-for="o in detail.offers" :key="o.id"><td>{{o.agent_name}}</td><td>{{names[o.status]||o.status}}</td><td>{{stamp(o.created_at)}}</td><td>{{stamp(o.answered_at)}}</td><td>{{stamp(o.ended_at)}}</td></tr></tbody></table></div><p v-if="!detail.offers.length">Nenhuma oferta a atendente foi registrada.</p><details><summary>Eventos registrados</summary><p v-for="(e,i) in detail.events" :key="i">{{stamp(e.created_at)}} · {{e.event}}</p></details></article>
 <article class="table-card report-detail"><div class="report-heading"><h3>{{filters.outcome?names[filters.outcome]:'Todas as chamadas'}} · {{data.rows.total}}</h3><button v-if="filters.outcome" class="secondary" @click="choose('total')">Limpar resultado</button></div><div class="report-scroll"><table><thead><tr><th>Origem</th><th>Fila</th><th>Responsável</th><th>Resultado</th><th>Recebida</th><th></th></tr></thead><tbody><tr v-for="c in data.rows.data" :key="c.id"><td>{{c.from_number}}</td><td>{{c.queue_name}}</td><td>{{c.agent_name||'Sem responsável'}}</td><td>{{names[c.outcome]}}</td><td>{{stamp(c.created_at)}}</td><td><button class="secondary" :disabled="busy" @click="open(c.id)">Ver atendimento</button></td></tr></tbody></table></div><p v-if="!data.rows.data.length">Nenhum registro para este filtro.</p><div class="report-heading"><button class="secondary" :disabled="busy||page===1" @click="page--;load()">Anterior</button><small>{{page}} / {{data.rows.last_page}}</small><button class="secondary" :disabled="busy||page>=data.rows.last_page" @click="page++;load()">Próxima</button></div></article>
 <article v-if="data.agents.length" class="table-card report-detail"><h3>Distribuição por responsável final</h3><div class="report-scroll"><table><thead><tr><th>Atendente</th><th>Chamadas</th><th>Atendidas</th></tr></thead><tbody><tr v-for="u in data.agents" :key="u.user_id"><td>{{u.name}}</td><td>{{u.total}}</td><td>{{u.answered}}</td></tr></tbody></table></div><small>Uma chamada transferida conta uma vez, para o responsável final. O detalhe preserva as ofertas anteriores.</small></article></template>
</section></template>
<style scoped>
.inbound-reports{margin-top:28px}.report-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.report-heading p,.report-note,.report-detail small{font-size:12px;line-height:1.7;color:#737f67}.report-heading h2{font-size:22px}.report-filters{display:flex;gap:13px;align-items:flex-end;flex-wrap:wrap;margin:22px 0}.report-filters label{flex:1;min-width:135px;margin:0}.report-filters input,.report-filters select{width:100%;padding:11px;border:1px solid #dce0d3;border-radius:9px;background:#fff}.report-stats{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:13px}.report-stats>button{display:flex;flex-direction:column;align-items:flex-start;padding:20px;text-align:left;border:1px solid #dde1d4}.report-stats>button.chosen{border-color:#c69a3e;background:#fffaf0}.report-stats span{font-size:11px;color:#727d68}.report-stats strong{font-size:32px}.report-stats small{font-size:10px;color:#ae8330}.report-secondary{display:flex;gap:14px 25px;flex-wrap:wrap;margin:22px 0;font-size:12px;color:#6c775e}.report-chart,.report-detail{padding:22px;margin:18px 0}.report-chart h3,.report-detail h3{font-size:17px;margin:0 0 14px}.legend{display:flex;flex-wrap:wrap;gap:15px;font-size:11px}.legend span:before{content:'';display:inline-block;width:8px;height:8px;background:var(--bar);border-radius:3px;margin-right:7px}.answered{--bar:#4d9270}.abandoned{--bar:#c58270}.unavailable{--bar:#c9a14d}.active{--bar:#8b9ec0}.bars{display:flex;gap:12px;overflow-x:auto;margin-top:20px;padding-bottom:10px}.bars button{display:flex;flex-direction:column;justify-content:flex-end;gap:10px;flex:1;min-width:35px;padding:4px 0}.bar-area{display:flex;flex-direction:column;justify-content:flex-end;min-height:120px;width:min(45px,100%);border-bottom:2px solid #e1e6d8}.bar-area i{display:block;background:var(--bar);width:100%}.bars small{font-size:10px;color:#748167}.report-scroll{overflow:auto}.report-detail td{font-size:12px}.report-detail details{font-size:11px;margin-top:18px}.inbound-reports button:focus-visible{outline:3px solid #be9134;outline-offset:2px}@media(max-width:900px){.report-stats{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.report-detail,.report-chart{padding:15px}.report-stats>button{padding:15px}}
</style>
