<script setup>
import {ref,onMounted} from 'vue'
import {Plus,ExternalLink,KeyRound} from 'lucide-vue-next'
import {voiceApi,stamp} from '../voice/operations'
const state=ref(null),form=ref(null),secret=ref(null),error=ref(''),busy=ref(false)
const scopeLabels={'lists:read':'Consultar listas permitidas','lists:write':'Importar contatos nas listas permitidas','calls:read':'Consultar chamadas do workspace','reports:read':'Consultar relatórios de jornadas','events:read':'Receber e consultar eventos','voice:embed':'Emitir sessões de atendentes para o discador','leads:write':'Cadastrar leads sociais / CRM'}
async function api(path='',method='GET',d){return voiceApi('/integrations'+path,method,d)}
async function load(){state.value=await api()}
async function run(fn){busy.value=true;error.value='';try{await fn()}catch(e){error.value=e.message}finally{busy.value=false}}
function create(){secret.value=null;form.value={name:'',scopes:['lists:read'],list_keys:[],agent_ids:[],embed_origin:'',webhook_url:''}}
async function save(){secret.value=await api('','POST',form.value);form.value=null;await load()}
onMounted(()=>run(load))
</script>
<template><section class="integrations"><span class="eyebrow">SEU MA, CONECTADO</span><div class="heading"><div><h1>API e integrações</h1><p>Conecte CRMs e outros sistemas com acessos definidos para cada integração.</p></div><button class="primary" @click="create"><Plus :size="16"/>Nova integração</button></div><p v-if="error" class="error" role="alert">{{error}}</p><div class="actions"><a class="secondary" href="/integrations/openapi.json" target="_blank" rel="noopener">Contrato OpenAPI <ExternalLink :size="14"/></a><a class="secondary" href="/integrations/reference" target="_blank" rel="noopener">Cliente de referência <ExternalLink :size="14"/></a></div>
 <article v-if="secret" class="table-card secret"><KeyRound/><h3>Guarde as credenciais agora</h3><p>O token fica no servidor integrador. O discador no navegador usa uma sessão temporária, emitida por esse servidor.</p><label>Token da integração<textarea readonly :value="secret.token" rows="2"/></label><label>Segredo de assinatura dos webhooks<textarea readonly :value="secret.webhook_secret" rows="2"/></label><p>Estes valores não serão exibidos novamente.</p><button class="primary" @click="secret=null">Guardei as credenciais</button></article>
 <form v-if="form" class="table-card box" @submit.prevent="run(save)"><h2>Criar acesso</h2><label>Nome<input v-model="form.name" required maxlength="160" placeholder="Ex.: CRM de homologação"></label><fieldset><legend>Permissões</legend><label v-for="scope in state?.scopes||[]" class="check-label"><input type="checkbox" v-model="form.scopes" :value="scope">{{scopeLabels[scope]}}</label></fieldset><fieldset v-if="form.scopes.some(s=>s.startsWith('lists:'))"><legend>Listas permitidas</legend><label v-for="l in state?.lists||[]" class="check-label"><input type="checkbox" v-model="form.list_keys" :value="l.key">{{l.name}} · {{l.key}}</label></fieldset><template v-if="form.scopes.includes('voice:embed')"><label>Origem HTTPS do sistema integrador<input v-model="form.embed_origin" placeholder="https://crm.exemplo.com" type="url" required></label><p>Informe somente a origem, sem caminho e sem barra final.</p><fieldset><legend>Atendentes delegáveis</legend><label v-for="a in state?.agents||[]" class="check-label"><input type="checkbox" v-model="form.agent_ids" :value="a.id">{{a.name}}</label></fieldset></template><label v-if="form.scopes.includes('events:read')">Webhook HTTPS · opcional<input v-model="form.webhook_url" type="url" placeholder="https://crm.exemplo.com/webhooks/zyrex"></label><p v-if="form.webhook_url">Os próximos eventos serão enviados automaticamente para esse destino após criar a integração.</p><div class="actions"><button class="primary" :disabled="busy">Criar credenciais</button><button type="button" class="secondary" @click="form=null">Cancelar</button></div></form>
 <div class="table-card box" v-for="i in state?.integrations" :key="i.id"><div class="heading"><div><h3>{{i.name}}</h3><span :class="['status',i.active?'active':'paused']">{{i.active?'Ativa':'Revogada'}}</span></div><button v-if="i.active" class="secondary" :disabled="busy" @click="run(async()=>{await api('/'+i.id+'/revoke','POST',{});await load()})">Revogar acesso</button></div><p>{{JSON.parse(i.scopes).map(s=>scopeLabels[s]).join(' · ')}}</p><p>Último uso: {{stamp(i.last_used_at)}} · Origem: {{i.embed_origin||'Sem discador incorporado'}}</p><small>{{i.webhook_url||'Eventos disponíveis por consulta na API'}}</small></div><p v-if="state&&!state.integrations.length">Crie uma integração para gerar o primeiro acesso externo.</p>
 <details class="table-card box"><summary>Entregas de eventos</summary><p>O consumidor deve conferir a assinatura e deduplicar pelo ID. Reentregas preservam o ID original.</p><div class="scroll"><table><thead><tr><th>Evento</th><th>Estado</th><th>Tentativas</th><th>HTTP</th><th></th></tr></thead><tbody><tr v-for="d in state?.deliveries" :key="d.id"><td>#{{d.event_sequence}}</td><td>{{d.status}}</td><td>{{d.attempts}}</td><td>{{d.http_status||'—'}}</td><td><button v-if="['dead','retry'].includes(d.status)" class="secondary" @click="run(async()=>{await api('/deliveries/'+d.id+'/retry','POST',{revision:d.revision});await load()})">Reprocessar evento</button></td></tr></tbody></table></div></details>
</section></template>
<style scoped>.heading,.actions{display:flex;gap:14px;align-items:center;justify-content:space-between;flex-wrap:wrap}.actions{justify-content:flex-start;margin:18px 0}.box,.secret{padding:25px;margin:20px 0}.integrations p,.integrations small{color:#74806b;line-height:1.7}.integrations label:not(.check-label){display:flex;flex-direction:column;gap:8px;margin:16px 0;font-size:13px}.integrations fieldset{border:1px solid #e0e3d6;border-radius:12px;padding:15px;margin:18px 0}.check-label{margin:10px 0}.secret{border:1px solid #c99d3b;background:#fffaec}.secret textarea{font-family:monospace;font-size:12px}.scroll{overflow:auto}.integrations a{display:inline-flex;gap:10px;align-items:center;text-decoration:none}</style>
