<script setup>
import {ref,onMounted,computed} from 'vue'
import {voiceApi,stamp} from '../voice/operations'
const tab=ref('costs'),costs=ref(null),recovery=ref(null),retention=ref(null),form=ref(null),error=ref(''),notice=ref(''),busy=ref(false),detail=ref(null),confirm=ref(null)
const dirty=computed(()=>form.value&&retention.value&&['audio_days','session_days','delivery_days','automatic'].some(k=>k==='automatic'?!!form.value[k]!==!!retention.value.policy[k]:Number(form.value[k])!==Number(retention.value.policy[k])))
function resetForm(){form.value={...retention.value.policy,automatic:!!retention.value.policy.automatic};confirm.value=null}
const newKey=()=>crypto.randomUUID()
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date())
const from=ref(today.slice(0,8)+'01'),to=ref(today),channel=ref(''),page=ref(1)
const channels={voice_outbound:'Voz de saída',voice_inbound:'Voz receptiva',whatsapp_api:'WhatsApp API',whatsapp_qr:'WhatsApp QR'}
const costLabels={complete:'Recursos consultados',partial:'Parcial',pending:'Não informado',unavailable:'Não informado pelo QR'}
const states={pending:'Na fila',retry:'Aguardando nova tentativa',delivering:'Em entrega',dead:'Tentativas esgotadas',delivered:'Entregue',cancelled:'Cancelado',running:'Em andamento',failed:'Falhou',abandoned:'Prazo esgotado'}
const errors={http_error:'O destino recusou a entrega',transport_error:'Falha de conexão',invalid_destination:'Destino indisponível ou inválido',lease_expired:'Prazo de execução esgotado',attempts_exhausted:'Limite de tentativas atingido',integration_inactive:'Integração desativada'}
const money=(v,c)=>Number(v).toLocaleString('pt-BR',{minimumFractionDigits:4,maximumFractionDigits:6})+' '+c
const counts=v=>{const c=typeof v==='string'?JSON.parse(v):v;return `${c.audio} testes · ${c.session} sessões · ${c.delivery} eventos`}
async function api(path,method='GET',data){return voiceApi('/health/'+path,method,data)}
async function load(){if(tab.value==='costs')costs.value=await api('costs?'+new URLSearchParams({from:from.value,to:to.value,channel:channel.value,page:page.value}));else if(tab.value==='recovery')recovery.value=await api('recovery?page='+page.value);else{retention.value=await api('retention');if(!form.value)form.value={...retention.value.policy,automatic:!!retention.value.policy.automatic}}}
async function run(fn){if(busy.value)return;busy.value=true;error.value='';try{await fn()}catch(e){error.value=e.message}finally{busy.value=false}}
async function change(key){tab.value=key;page.value=1;detail.value=null;confirm.value=null;await run(load)}
async function sync(row){await api(`costs/${row.channel}/${row.id}/sync`,'POST',{});notice.value='Consulta concluída. Valores ainda ausentes permanecem pendentes.';await load()}
async function save(){await api('retention','PUT',form.value);form.value=null;confirm.value=null;notice.value='Política salva.';await load()}
async function execute(){const c=confirm.value;if(c.kind==='retry'){await voiceApi(`/integrations/deliveries/${c.row.id}/retry`,'POST',{revision:c.row.revision});notice.value='Evento reagendado com o mesmo identificador. O histórico foi preservado.'}else if(c.kind==='archive'){const result=await api('retention/archive','POST',{revision:retention.value.policy.revision,idempotency_key:c.key,confirm:true});notice.value='Arquivamento concluído: '+counts(result.counts)+'.'}else{await api(`retention/${c.id}/restore`,'POST',{confirm:true});notice.value='Lote restaurado. Os eventos concluídos não serão reenviados.'}confirm.value=null;await load()}
onMounted(()=>run(load))
</script>
<template><section class="table-card controls"><div class="heading"><div><span class="eyebrow">CONTROLE DA OPERAÇÃO</span><h2>Custos, recuperação e retenção</h2></div><button class="secondary" :disabled="busy" @click="run(load)">Atualizar dados</button></div><nav aria-label="Controles operacionais"><button v-for="(label,key) in {costs:'Custos por canal',recovery:'Recuperação de eventos',retention:'Retenção técnica'}" :key="key" :class="tab===key?'primary':'secondary'" :aria-pressed="tab===key" :disabled="busy" @click="change(key)">{{label}}</button></nav><p v-if="error" role="alert" class="error">{{error}}</p><p v-if="notice" role="status" class="notice">{{notice}}</p>
<template v-if="tab==='costs'"><form class="filters" @submit.prevent="page=1;run(load)"><label>De<input type="date" v-model="from" required></label><label>Até<input type="date" v-model="to" required></label><label>Canal<select v-model="channel"><option value="">Todos</option><option v-for="(name,key) in channels" :value="key">{{name}}</option></select></label><button class="secondary" :disabled="busy">Consultar período</button></form><template v-if="costs"><p>{{costs.scope}}</p><small>Datas em São Paulo. Totais incluem todos os canais do período; o filtro de canal organiza o detalhamento.</small><div class="cards"><article v-for="c in costs.channels" :key="c.channel"><h3>{{channels[c.channel]}}</h3><strong v-for="v in c.known">{{money(v.amount,v.currency)}}</strong><strong v-if="!c.known.length">Não informado</strong><small>{{c.records}} registros · {{c.partial}} parciais · {{c.unknown}} sem custo informado</small></article></div><div class="scroll"><table><thead><tr><th>Registro / canal</th><th>Data</th><th>Cobertura dos custos</th><th></th></tr></thead><tbody><template v-for="row in costs.rows.data" :key="row.id"><tr><td>{{row.phone}}<small>{{channels[row.channel]}} · {{row.direction==='inbound'?'Entrada':row.direction==='outbound'?'Saída':row.provider}}</small></td><td>{{stamp(row.created_at)}}</td><td>{{costLabels[row.cost_status]}}</td><td class="actions"><button class="secondary" :aria-expanded="detail===row.id" @click="detail=detail===row.id?null:row.id">Detalhar</button><button v-if="costs.can_manage&&row.can_sync" class="secondary" :disabled="busy" @click="run(()=>sync(row))">Consultar custo</button></td></tr><tr v-if="detail===row.id"><td colspan="4"><p>Referência: {{row.id}} · Estado: {{row.status}}</p><p v-for="(c,i) in row.components" :key="i">{{{incoming:'Recebimento',agent:'Atendente',message:'Mensagem',parent:'Origem',child:'Destino'}[c.leg]||c.leg}}: {{c.amount===null?'Não informado':money(c.amount,c.currency)}} · Consultado em {{stamp(c.synced_at)}}</p><p v-if="!row.components.length">Ainda não há valores informados para este registro.</p><small>Exibe os recursos identificados nesta operação. Uma consulta não inicia chamadas nem envia mensagens.</small></td></tr></template></tbody></table></div><p v-if="!costs.rows.total">Nenhum registro no período.</p></template></template>
<template v-if="tab==='recovery'&&recovery"><p>Acompanhe as entregas de eventos às integrações. Cada ciclo faz até seis tentativas. Reagendar preserva o ID do evento; o sistema de destino deve deduplicar por esse ID.</p><div class="tags"><span v-for="c in recovery.counts">{{states[c.status]||c.status}}: {{c.total}}</span></div><div class="scroll"><table><thead><tr><th>Integração / evento</th><th>Estado</th><th>Tentativas no ciclo</th><th></th></tr></thead><tbody><template v-for="d in recovery.rows.data" :key="d.id"><tr><td>{{d.integration_name}}<small>#{{d.event_sequence}} · {{d.type}}</small></td><td>{{states[d.status]||d.status}}<small>{{errors[d.last_error]||''}}</small></td><td>{{d.attempts}} / 6</td><td class="actions"><button class="secondary" :disabled="busy" @click="run(async()=>{detail={id:d.id,...await api('recovery/'+d.id+'/attempts')}})">Histórico</button><button v-if="recovery.can_manage&&d.active&&['dead','retry'].includes(d.status)" class="secondary" :disabled="busy" @click="confirm={kind:'retry',row:d}">Reagendar</button></td></tr><tr v-if="detail?.id===d.id"><td colspan="4"><p v-if="!detail.attempts.length">Sem histórico detalhado. Tentativas anteriores à atualização não foram reconstruídas.</p><p v-for="a in detail.attempts" :key="a.id">{{stamp(a.started_at)}} · tentativa {{a.attempt}} · {{states[a.status]||a.status}} · {{a.http_status?'HTTP '+a.http_status:errors[a.error]||'Sem resposta registrada'}}</p><small>Últimas 100 execuções. Corpos de resposta e segredos não são armazenados.</small></td></tr></template></tbody></table></div><p v-if="!recovery.rows.total">Nenhuma entrega de evento registrada.</p></template>
<template v-if="tab==='retention'&&retention"><p>Arquive registros técnicos antigos para organizar os históricos. O arquivamento é reversível e não libera espaço no banco. Chamadas, conversas, custos, consentimentos e auditorias são preservados.</p><form v-if="form" @submit.prevent="run(save)"><fieldset :disabled="busy||!retention.can_manage"><div class="filters"><label>Testes de áudio · dias<input type="number" min="30" max="3650" v-model.number="form.audio_days" required></label><label>Sessões expiradas · dias<input type="number" min="30" max="3650" v-model.number="form.session_days" required></label><label>Entregas concluídas · dias<input type="number" min="30" max="3650" v-model.number="form.delivery_days" required></label></div><label class="check-label"><input type="checkbox" v-model="form.automatic">Arquivar automaticamente todos os dias, às 00:30 de São Paulo</label><p>Somente registros encerrados e fora do prazo. Entregas pendentes ou com falhas permanecem visíveis. Limite por execução: 500 registros de cada tipo.</p><div v-if="retention.can_manage" class="actions"><button class="primary" :disabled="!dirty">Salvar política</button><button type="button" class="secondary" @click="resetForm">Descartar edição</button><small>{{dirty?'Alterações ainda não salvas':'Política salva'}}</small></div></fieldset></form><div class="preview"><h3>Prévia com a política salva</h3><p>{{counts(retention.eligible)}}</p><button v-if="retention.can_manage" class="secondary" :disabled="busy||dirty||!Object.values(retention.eligible).some(Boolean)" @click="confirm={kind:'archive',key:newKey()}">Arquivar lote agora</button></div><h3>Últimos lotes</h3><p v-if="!retention.runs.length">Nenhum arquivamento executado.</p><div v-for="r in retention.runs" :key="r.id" class="batch"><div>{{stamp(r.created_at)}}<small>{{counts(r.counts)}}</small></div><span v-if="r.restored_at">Restaurado em {{stamp(r.restored_at)}}</span><button v-else-if="retention.can_manage" class="secondary" :disabled="busy" @click="confirm={kind:'restore',id:r.id}">Restaurar lote</button></div><small>Se o arquivamento automático estiver ativo, registros restaurados poderão voltar a ser arquivados na próxima execução.</small></template>
<div v-if="confirm" class="confirmation" role="alert"><p v-if="confirm.kind==='retry'">Reagendar o evento #{{confirm.row.event_sequence}} para {{confirm.row.integration_name}}? A integração receberá outra tentativa com o mesmo ID.</p><p v-else-if="confirm.kind==='archive'">Arquivar até 500 registros elegíveis de cada tipo, usando a política salva? Você poderá restaurar este lote.</p><p v-else>Restaurar este lote nos históricos? O estado das entregas será preservado.</p><div class="actions"><button class="primary" :disabled="busy" @click="run(execute)">Confirmar {{confirm.kind==='retry'?'reagendamento':confirm.kind==='archive'?'arquivamento':'restauração'}}</button><button class="secondary" :disabled="busy" @click="confirm=null">Cancelar</button></div></div>
<div v-if="tab!=='retention'&&(tab==='costs'?costs:recovery)" class="pagination"><button class="secondary" :disabled="busy||page<=1" @click="page--;run(load)">Anterior</button><span>Página {{page}} de {{(tab==='costs'?costs:recovery).rows.last_page}}</span><button class="secondary" :disabled="busy||page>=(tab==='costs'?costs:recovery).rows.last_page" @click="page++;run(load)">Próxima</button></div></section></template>
<style scoped>
.controls{padding:24px;margin-bottom:22px;min-width:0}.heading,nav,.filters,.actions,.tags,.batch,.pagination{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.heading,.batch{justify-content:space-between}nav{margin:20px 0}.controls h2{font-size:20px}.controls h3{font-size:14px}.controls p,.controls small{line-height:1.7;color:#727d67}.controls small{display:block;font-size:12px}.filters{align-items:end;margin:20px 0}.filters label{display:flex;flex-direction:column;gap:8px;font-size:12px;min-width:150px}.cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:24px 0}.cards article,.preview{padding:18px;border:1px solid #e0e3d9;border-radius:12px}.cards strong{display:block;font-size:20px;margin:12px 0;overflow-wrap:anywhere}.scroll{overflow:auto}.controls table{font-size:12px;width:100%}.controls td{vertical-align:top}.controls td.actions{min-width:160px}.tags span{background:#f6f2e8;border-radius:20px;padding:8px 12px;font-size:12px}.confirmation{background:#fff4d8;border-radius:12px;padding:20px;margin-top:20px}.notice{background:#ecf5ef;padding:12px;border-radius:8px}fieldset{border:0;padding:0;min-width:0}.preview,.batch{margin:20px 0}.batch{padding:16px 0;border-bottom:1px solid #e0e3d9}.pagination{justify-content:end;margin-top:20px}@media(max-width:1000px){.cards{grid-template-columns:1fr 1fr}}@media(max-width:600px){.controls{padding:16px}.cards{grid-template-columns:1fr}.filters>*{width:100%}.filters label{min-width:0}nav button{flex:1}input,select{max-width:100%}}
</style>
