<script setup>
const props=defineProps({modelValue:Object,section:String})
const days=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom']
</script>
<template>
 <fieldset v-if="section==='channels'"><legend>Horário de funcionamento</legend><label class="check"><input type="checkbox" v-model="modelValue.schedule_enabled">Definir horário da fila</label><p>Sem esta opção, a fila não adiciona restrição de horário. Cadências continuam respeitando seus próprios horários.</p>
 <div v-if="modelValue.schedule_enabled" class="queue-form-grid"><label>Fuso horário da fila<input v-model="modelValue.schedule_timezone" required placeholder="America/Sao_Paulo"></label><label>Abertura<input type="time" v-model="modelValue.schedule_start" required></label><label>Fechamento<input type="time" v-model="modelValue.schedule_end" required></label><div><strong>Dias de abertura</strong><label v-for="(day,i) in days" :key="day" class="check"><input type="checkbox" :value="i+1" v-model="modelValue.schedule_days">{{day}}</label></div><p>Se o fechamento for anterior à abertura, o expediente termina no dia seguinte. Vale para novas chamadas de entrada e saída, incluindo discagem manual; chamadas em andamento continuam.</p></div></fieldset>
 <fieldset v-if="section==='rules'"><legend>Disponibilidade dos atendentes</legend><div class="queue-form-grid"><label>Tempo para aceitar uma chamada (segundos)<input type="number" min="5" max="60" v-model.number="modelValue.agent_ring_seconds" placeholder="Usar tempo da rota de entrada"></label><p>Tempo para o agente aceitar uma oferta receptiva antes de procurar outro agente. Não altera o tempo de espera para o cliente atender uma ligação de saída.</p></div>
 <label class="check"><input type="checkbox" v-model="modelValue.pause_on_disconnect">Pausar atendimento ao perder a conexão de voz receptiva</label><p>A pausa bloqueia novas distribuições e informa o motivo. Não encerra uma conversa em andamento. Conexões sem atualização são detectadas em até dois minutos.</p>
 <label>Pausar após ofertas consecutivas não atendidas<select aria-label="Pausar após ofertas consecutivas não atendidas" v-model.number="modelValue.missed_offer_limit"><option :value="0">Não pausar automaticamente</option><option v-for="n in 10" :key="n" :value="n">{{n}} {{n===1?'oferta':'ofertas'}}</option></select></label><p>Conta ofertas receptivas recusadas ou não atendidas pelo agente; não conta clientes que não atendem. Atender uma oferta ou clicar em Online zera o contador. A pausa vale para o atendimento do agente em todas as filas.</p>
 </fieldset>
 <fieldset v-if="section==='rules'"><legend>Outros destinos de saída</legend><label class="check"><input type="checkbox" v-model="modelValue.allow_international">Permitir chamadas internacionais</label><label class="check"><input type="checkbox" v-model="modelValue.allow_special">Permitir serviços especiais brasileiros</label><p>Serviços 0300, 0500, 0800 e 0900. A permissão da fila não substitui a disponibilidade, as tarifas ou as permissões da operadora. Números curtos de emergência não são suportados pelo discador.</p></fieldset>
 <fieldset v-if="section==='recording'"><legend>Gravação das chamadas</legend><p>Disponível para chamadas pela Twilio API. A gravação começa quando há atendimento; não grava o tempo de espera. SIP/Asterisk ainda não oferece gravação integrada.</p><label class="check"><input type="checkbox" v-model="modelValue.recording_enabled" :disabled="modelValue.calling_method==='sip_trunk'">Gravar chamadas atendidas desta fila</label>
 <div v-if="modelValue.recording_enabled"><p>As próximas chamadas serão gravadas na Twilio, sujeitas à cobrança do serviço. A configuração não inicia chamadas e não recupera áudio de chamadas anteriores.</p><label class="check"><input type="checkbox" v-model="modelValue.recording_agent_access" @change="!modelValue.recording_agent_access&&(modelValue.recording_agent_pause=false)">Permitir ao agente visualizar e ouvir suas gravações</label><label class="check"><input type="checkbox" v-model="modelValue.recording_agent_pause" :disabled="!modelValue.recording_agent_access">Permitir ao agente pausar e retomar a gravação</label><label>Prazo de retenção (dias)<input type="number" min="1" max="365" v-model.number="modelValue.recording_retention_days" required></label><p>Após o prazo, o acesso é bloqueado e a exclusão na Twilio é processada automaticamente. O registro da chamada permanece nos relatórios. Mudanças valem para novas gravações.</p></div></fieldset>
</template>
<style scoped>
fieldset{border:0;border-top:1px solid #e3e3d8;margin:18px 0 28px;padding:18px 0 0;min-width:0}legend{padding-right:10px;font-size:13px;font-weight:650}p{font-size:12px;line-height:1.7;color:#7a856d;margin:10px 0 16px}label{display:flex;flex-direction:column;gap:8px;font-size:12px;font-weight:600;color:#566346;margin:12px 0}.check{flex-direction:row;align-items:center;gap:10px}.queue-form-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px}.queue-form-grid label{margin:0}input:not([type=checkbox]),select{width:100%;min-width:0}input[type=checkbox]{flex:none}strong{font-size:12px} @media(max-width:600px){.queue-form-grid{grid-template-columns:1fr}fieldset{margin-bottom:20px}}
</style>
