<script setup>
import {ref,onMounted} from 'vue'
import {Users,Plus,RefreshCw,X} from 'lucide-vue-next'
const data=ref({users:[],queues:[]}),form=ref(null),busy=ref(false),error=ref(''),notice=ref('')
const roles={admin:'Administrador',supervisor:'Supervisor',agent:'Atendente'}
async function api(path,method='GET',body){const res=await fetch('/api/voice/team'+path,{method,headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},...(body?{body:JSON.stringify(body)}:{})});const j=await res.json();if(!res.ok)throw Error(Object.values(j.errors||{}).flat().join(' ')||j.message||'Não foi possível concluir.');return j}
async function load(){try{data.value=await api('')}catch(e){error.value=e.message}}
function edit(u){error.value='';notice.value='';form.value=u?{id:u.id,name:u.name,email:u.email,role:u.voice_role,enabled:u.voice_enabled,revision:u.voice_revision,queue_ids:[...u.queue_ids],password:''}:{name:'',email:'',role:'agent',enabled:true,queue_ids:[],password:''}}
async function save(){busy.value=true;error.value='';try{const f=form.value;await api(f.id?'/'+f.id:'',f.id?'PUT':'POST',f);form.value=null;notice.value='Cadastro salvo. O atendente acessa o MA com o e-mail e a senha definidos.';await load()}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(load)
</script>
<template>
 <div class="team">
  <span class="eyebrow">PESSOAS QUE CONECTAM</span><div class="heading"><div><h1>Equipe e acessos</h1><p>Cadastre atendentes, escolha o perfil e vincule as filas de atendimento.</p></div><button class="primary" @click="edit()"><Plus :size="16"/>Novo atendente</button></div>
  <p v-if="notice" class="notice" role="status">{{notice}}</p><p v-if="error&&!form" class="error" role="alert">{{error}}</p>
  <div class="table-card"><div class="toolbar"><strong>{{data.users.length}} pessoas</strong><button class="secondary" @click="load"><RefreshCw :size="15"/>Atualizar estados</button></div><div class="scroll"><table><thead><tr><th>Pessoa</th><th>Perfil</th><th>Estado</th><th>Filas</th><th></th></tr></thead><tbody><tr v-for="u in data.users" :key="u.id"><td><strong>{{u.name}}</strong><small>{{u.email}}</small></td><td>{{roles[u.voice_role]}}</td><td><span :class="['status',u.voice_enabled?'active':'paused']">{{!u.voice_enabled?'Desativado':u.active?'Em atendimento':u.online?u.status==='available'?'Disponível':'Em pausa':'Offline'}}</span></td><td>{{data.queues.filter(q=>u.queue_ids.includes(q.id)).map(q=>q.name).join(', ')||'Sem fila'}}</td><td><button v-if="data.role==='admin'||u.voice_role==='agent'" class="secondary" @click="edit(u)">Editar</button></td></tr></tbody></table></div></div>
  <div class="explanation"><Users :size="20"/><p><b>Atendentes</b> acessam sua operação e filas atribuídas. <b>Supervisores</b> acompanham cadências e gerenciam atendentes. <b>Administradores</b> também gerenciam os perfis de acesso. Desativar bloqueia novas reservas e preserva chamadas em andamento.</p></div>
  <div v-if="form" class="modal-backdrop" @click.self="!busy&&(form=null)"><form class="modal" @submit.prevent="save"><div class="heading"><h2>{{form.id?'Editar pessoa':'Novo atendente'}}</h2><button type="button" @click="form=null" :disabled="busy" aria-label="Fechar"><X/></button></div><label>Nome<input v-model="form.name" required maxlength="160"></label><label>E-mail de acesso<input v-model="form.email" type="email" required maxlength="200" autocomplete="off"></label><label>{{form.id?'Nova senha (deixe em branco para manter)':'Senha inicial'}}<input v-model="form.password" type="password" :required="!form.id" minlength="12" maxlength="128" autocomplete="new-password"></label><small>Use pelo menos 12 caracteres. Compartilhe a senha com o atendente por um canal privado.</small><label>Perfil<select v-model="form.role" :disabled="data.role!=='admin'"><option value="agent">Atendente</option><option value="supervisor">Supervisor</option><option value="admin">Administrador</option></select></label><label class="check-label"><input type="checkbox" v-model="form.enabled">Acesso ativo</label><fieldset><legend>Filas atribuídas</legend><label v-for="q in data.queues" :key="q.id" class="check-label"><input type="checkbox" v-model="form.queue_ids" :value="q.id">{{q.name}} · {{({inbound:'Receptivo',outbound:'Saída',mixed:'Entrada e saída'})[q.direction]}}</label><p v-if="!data.queues.length">Cadastre uma fila em Cadências → Supervisão.</p></fieldset><p v-if="error" class="error" role="alert">{{error}}</p><div class="modal-actions"><button type="button" class="secondary" @click="form=null" :disabled="busy">Cancelar</button><button class="primary" :disabled="busy">{{busy?'Salvando…':'Salvar pessoa'}}</button></div></form></div>
 </div>
</template>
<style scoped>
.heading,.toolbar{display:flex;align-items:center;justify-content:space-between;gap:20px}.heading{margin-bottom:24px}.heading h1,.heading h2{margin:0}.heading p{color:#7b8273}.toolbar{padding:18px 22px;border-bottom:1px solid #e5e7df}.scroll{overflow:auto}td{max-width:300px}small{display:block;color:#7b8273;margin-top:5px}.explanation{display:flex;gap:14px;line-height:1.8;color:#707969;margin-top:24px;max-width:920px}.explanation svg{flex-shrink:0;margin-top:18px;color:#bc9034}.modal{max-height:90vh;overflow:auto;width:min(580px,95vw)}fieldset{border:1px solid #e2e4d9;border-radius:12px;padding:12px;margin-top:20px}legend{font-size:13px}.notice{background:#e7f5eb;color:#2c6a48;padding:15px;border-radius:10px}@media(max-width:700px){.heading{align-items:flex-start;flex-direction:column}}
</style>
