<script setup>
import {computed,ref,watch,onBeforeUnmount} from 'vue'
import {Save,ArrowRight,ShieldCheck} from 'lucide-vue-next'
import VoiceFollowupSettings from './VoiceFollowupSettings.vue'
const props=defineProps({node:String,journey:Object,campaign:Object,contacts:Array,lists:Array,senders:Array,templates:Array,qrTemplates:Array,references:Array,canManage:Boolean})
const emit=defineEmits(['saved','navigate','dirty','saving'])
const form=ref(null),initial=ref(''),revision=ref(0),busy=ref(false),error=ref(''),notice=ref(''),search=ref('')
const titles={entry:'Público da jornada',voice:'Ligar para o cliente',decision:'Resultado da ligação',wait:'Intervalo entre tentativas',message:'Enviar WhatsApp',exit:'Encerrar abordagem'}
const fields={voice:['mode','max_attempts','whatsapp_after','timezone','days','start_time','end_time','concurrency','script'],decision:['whatsapp_after'],wait:['retry_minutes'],message:['whatsapp_enabled','whatsapp_delivery','number_mode','whatsapp_number','whatsapp_sender_id','whatsapp_after','whatsapp_delay','whatsapp_text','whatsapp_qr_template_id', 'whatsapp_qr_buttons_confirmed', 'whatsapp_real_template_id','whatsapp_template_id','whatsapp_variables']}
const dirty=computed(()=>!!form.value&&JSON.stringify(form.value)!==initial.value)
watch(dirty,v=>{emit('dirty',v);if(v)notice.value=''},{flush:'sync'});watch(busy,v=>emit('saving',v),{flush:'sync'});onBeforeUnmount(()=>{emit('dirty',false);emit('saving',false)})
function reset(journey=props.journey,contactIds=props.campaign?.contact_ids||[]){const s=JSON.parse(JSON.stringify(journey.settings));s.whatsapp_variables||={};form.value={...s,list_id:journey.list?.id||null,list_kind:journey.list?.kind||'voice',contact_ids:[...contactIds]};if(props.node==='wait')form.value.retry_minutes=journey.retry_minutes?.no_answer??s.retry_minutes;revision.value=journey.revision;initial.value=JSON.stringify(form.value);error.value='';notice.value=''}
watch([()=>props.node,()=>props.journey.id],()=>reset(),{immediate:true})
defineExpose({reset:()=>reset()})
const thresholdConflict=computed(()=>props.node==='voice'&&form.value?.whatsapp_enabled&&form.value.max_attempts<form.value.whatsapp_after)
const canAlignThreshold=computed(()=>Number.isInteger(form.value?.max_attempts)&&form.value.max_attempts>=1&&form.value.max_attempts<=20)
function alignThreshold(){if(canAlignThreshold.value){form.value.whatsapp_after=form.value.max_attempts;error.value='';notice.value='Limite do WhatsApp ajustado no formulário. Clique em Salvar etapa para aplicar os dois valores.'}}
const audienceChoice=computed({get:()=>form.value.list_id?form.value.list_kind+':'+form.value.list_id:'',set:value=>{const [kind,id]=value.split(':');form.value.list_kind=kind||'voice';form.value.list_id=id?Number(id):null}})
const allowed=computed(()=>props.canManage&&['paused','draft'].includes(props.journey.status))
const matches=computed(()=>props.contacts.filter(c=>(c.name+' '+c.phone).toLowerCase().includes(search.value.toLowerCase())))
const crm=kind=>props.references.filter(r=>r.kind===kind)
const sendersForMode=computed(()=>props.senders.filter(s=>form.value.number_mode==='separate'||s.number===props.journey.settings.business_number))
function senderChanged(){const s=props.senders.find(s=>s.id===form.value.whatsapp_sender_id);form.value.whatsapp_number=form.value.number_mode==='single'?form.value.business_number:(s?.number||'')}
function numberModeChanged(){form.value.whatsapp_sender_id=null;senderChanged()}
async function save(){if(busy.value)return;if(thresholdConflict.value){error.value='Não foi salvo: ajuste o limite do WhatsApp antes de salvar esta etapa.';return}busy.value=true;error.value='';notice.value='';try{let config;if(props.node==='entry'){config={list_kind:form.value.list_kind,list_id:form.value.list_id,contact_ids:form.value.contact_ids,crm_campaign_id:form.value.crm_campaign_id||null,segment_id:form.value.segment_id||null}}else{config=Object.fromEntries(fields[props.node].filter(k=>form.value[k]!==undefined).map(k=>[k,form.value[k]]))}const r=await fetch('/api/voice/journeys/'+props.journey.id+'/nodes/'+props.node,{method:'PUT',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify({revision:revision.value,config})});const d=await r.json();if(!r.ok)throw new Error(d.errors?Object.values(d.errors).flat().join(' · '):d.message);reset(d.journey,form.value.contact_ids);notice.value='Etapa salva. A configuração já está aplicada à jornada.';emit('saved',d.journey)}catch(e){error.value='Não foi salvo: '+e.message}finally{busy.value=false}}
</script>
<template><aside class="vj-node-editor" aria-label="Configuração do cartão"><header><span class="eyebrow">CONFIGURAR ETAPA</span><h3>{{titles[node]}}</h3><p v-if="node!=='exit'">Edite este cartão e salve para aplicar à jornada.</p></header><p v-if="!allowed&&node!=='exit'" class="vj-hint">{{canManage?'Pause a campanha antes de editar as etapas.':'A edição é reservada à supervisão.'}}</p>
<form v-if="form&&node!=='exit'" @submit.prevent="save"><fieldset :disabled="busy||!allowed" class="vj-form-fields">
<template v-if="node==='entry'"><label>Origem do público<select aria-label="Origem do público" v-model="audienceChoice"><option value="">Selecionar contatos individualmente</option><option v-for="l in lists" :key="(l.kind||'voice')+':'+l.id" :value="(l.kind||'voice')+':'+l.id">{{l.name}} · {{l.kind==='automation'?'MA':'Voz e WhatsApp'}}</option></select></label><p v-if="form.list_id" class="vj-hint">{{form.list_kind==='automation'?'Esta lista do MA será vinculada à jornada. Os contatos com telefone válido são atualizados ao salvar e antes de buscar o próximo contato na fila.':'Ao salvar, os membros ativos desta lista substituem o público vinculado à campanha.'}} Autorizações, exclusões e tentativas anteriores são preservadas.</p><p v-if="form.list_id&&form.list_kind==='automation'" class="vj-hint">Gerencie os contatos em Segmentos. Cadastros sem telefone válido ficam fora do discador; sem autorização documentada, não recebem chamadas. Limite atual: 500 contatos por lista.</p><template v-if="!form.list_id"><label>Buscar contato<input v-model="search" placeholder="Nome ou telefone"></label><div class="vj-contact-list"><label v-for="c in matches" :key="c.id" class="vj-check"><input type="checkbox" v-model="form.contact_ids" :value="c.id"><span>{{c.name}}<small>{{c.phone}}</small></span></label><p v-if="!matches.length">Nenhum contato encontrado.</p></div><small>{{form.contact_ids.length}} contato(s) selecionado(s)</small></template><label>Referência de campanha do CRM<select aria-label="Referência de campanha do CRM" v-model="form.crm_campaign_id"><option :value="null">Sem vínculo</option><option v-for="r in crm('campaign')" :value="r.external_id">{{r.name}}</option></select></label><label>Referência de segmento<select aria-label="Referência de segmento" v-model="form.segment_id"><option :value="null">Sem vínculo</option><option v-for="r in crm('segment')" :value="r.external_id">{{r.name}}</option></select></label><p class="vj-hint">As referências ficam prontas para integração. A seleção acima não sincroniza contatos com o CRM.</p></template>
<template v-else-if="node==='voice'"><label>Modo de discagem<select aria-label="Modo de discagem" v-model="form.mode"><option value="preview">Preview · seleção pelo atendente</option><option value="progressive">Progressivo · próximo contato elegível</option></select></label><label>Máximo de tentativas<input aria-label="Máximo de tentativas" type="number" v-model.number="form.max_attempts" min="1" max="20" required></label><div v-if="thresholdConflict" class="vj-conflict" role="alert"><p>O WhatsApp está configurado após {{form.whatsapp_after}} não atendimentos, mas o máximo é {{form.max_attempts}}. Esses valores não podem ser salvos juntos.</p><button type="button" class="secondary" :disabled="!canAlignThreshold" @click="alignThreshold">Ajustar WhatsApp para {{form.max_attempts}} {{form.max_attempts===1?'não atendimento':'não atendimentos'}}</button><p>Esse ajuste fica no formulário até você salvar. Você também pode aumentar o máximo de tentativas.</p></div><div class="vj-two"><label>Início<input type="time" v-model="form.start_time" required></label><label>Fim<input type="time" v-model="form.end_time" required></label></div><label>Fuso horário<input v-model="form.timezone" required placeholder="America/Sao_Paulo"></label><div class="vj-days"><label v-for="(day,i) in ['Seg','Ter','Qua','Qui','Sex','Sáb','Dom']" :key="day"><input type="checkbox" v-model="form.days" :value="i+1">{{day}}</label></div><label>Chamadas simultâneas<input type="number" v-model.number="form.concurrency" min="1" max="2" required></label><label>Roteiro do atendente<textarea v-model="form.script" rows="5" maxlength="4000"/></label><p class="vj-hint">Origem configurada: {{form.business_number||'pendente'}}. Disponibilidade, limites da fila e conexão de voz também são verificados antes de ligar.</p></template>
<template v-else-if="node==='wait'"><label>Intervalo após não atendimento (minutos)<input aria-label="Intervalo após não atendimento (minutos)" type="number" v-model.number="form.retry_minutes" min="1" max="10080" required></label><p class="vj-hint">Este valor passa a ser o intervalo padrão da campanha e substitui a exceção de “Não atendeu”, se houver. Exceções de ocupado, erro e cancelamento permanecem nas regras avançadas.</p><p>A próxima tentativa só acontece dentro do horário permitido e enquanto o contato estiver elegível.</p></template>
<template v-else-if="node==='decision'"><div class="vj-rule"><ShieldCheck :size="19"/><p><strong>Atendeu?</strong><br>Encerra imediatamente a abordagem e cancela o WhatsApp pendente.</p></div><label>Enviar WhatsApp após quantos não atendimentos?<input aria-label="Enviar WhatsApp após quantos não atendimentos?" type="number" v-model.number="form.whatsapp_after" min="1" :max="form.max_attempts" required></label><p class="vj-hint">Máximo da campanha: {{form.max_attempts}} tentativas. Antes do limite de não atendimentos, a jornada aguarda o intervalo e tenta novamente.</p><p class="vj-hint">Ocupado, erro e cancelamento não contam como “Não atendeu”. Se o total de tentativas acabar antes de atingir o limiar, o WhatsApp não é enviado.</p></template>
<template v-else-if="node==='message'"><label>Números da jornada<select aria-label="Números da jornada" v-model="form.number_mode" @change="numberModeChanged"><option value="single">Usar o mesmo número de voz</option><option value="separate">Usar outro número no WhatsApp</option></select></label><label>Remetente WhatsApp<select aria-label="Remetente WhatsApp" v-model="form.whatsapp_sender_id" @change="senderChanged"><option :value="null">Selecione uma conexão</option><option v-for="s in sendersForMode" :key="s.id" :value="s.id">{{s.label}} · {{s.provider==='qr'?'QR Code':'Twilio'}} · {{s.number}}</option></select></label><p v-if="!sendersForMode.length" class="vj-hint">Cadastre um remetente compatível na aba WhatsApp ou selecione outro número.</p><VoiceFollowupSettings :settings="form" :senders="senders" :templates="templates" :qr-templates="qrTemplates" :references="crm('template').filter(r=>r.channel==='whatsapp')" :contacts="contacts" :campaign-name="journey.name"/></template>
</fieldset><footer class="vj-save"><p v-if="error" role="alert" class="error">{{error}}</p><p v-else-if="thresholdConflict" role="status" class="vj-save-warning">Não foi salvo: o limite do WhatsApp excede o máximo de tentativas.</p><p v-if="notice" role="status" class="vj-success">{{notice}}</p><span>{{busy?'Salvando…':dirty?'Alterações não salvas':'Configuração salva'}}</span><div><button type="button" class="secondary" :disabled="busy||!dirty" @click="reset()">Descartar</button><button class="primary" :disabled="busy||!allowed||!dirty||thresholdConflict"><Save :size="15"/>{{busy?'Salvando…':'Salvar etapa'}}</button></div></footer></form>
<template v-else><div class="vj-rule"><ShieldCheck :size="22"/><p><strong>Atendeu, saiu da jornada.</strong><br>A confirmação de atendimento cancela as próximas tentativas e a mensagem pendente.</p></div><p>Esta regra é fixa. A tabulação continua disponível após a conversa; alterá-la não reinicia a abordagem.</p></template>
<div class="vj-shortcuts"><button v-if="node==='entry'" class="secondary" @click="emit('navigate','lists')">Importar e gerenciar listas <ArrowRight :size="15"/></button><button v-if="node==='voice'" class="secondary" @click="emit('navigate','live')">Configurar fila e atendentes <ArrowRight :size="15"/></button><button v-if="node==='wait'" class="secondary" @click="emit('navigate','policies')">Regras avançadas por resultado <ArrowRight :size="15"/></button><button v-if="node==='message'" class="secondary" @click="emit('navigate','whatsapp')">Conexões e templates <ArrowRight :size="15"/></button><button v-if="node==='exit'" class="secondary" @click="emit('navigate','reports')">Relatórios e tabulação <ArrowRight :size="15"/></button></div></aside></template>
<style scoped>
.vj-node-editor{padding:24px;min-width:0;overflow:auto;background:white;height:100%}.vj-node-editor h3{font-size:22px;line-height:1.2;margin:12px 0}.vj-node-editor p{font-size:12px;line-height:1.7;color:#70766e}.vj-node-editor .eyebrow{font-size:9px}.vj-form-fields{border:0!important;padding:0!important;margin:0!important;min-width:0}.vj-form-fields>label,.vj-two label{display:flex;flex-direction:column;gap:8px;font-size:12px;font-weight:600;margin:20px 0}.vj-node-editor input:not([type=checkbox]),.vj-node-editor select,.vj-node-editor textarea{width:100%;min-width:0;padding:11px;border:1px solid #dcded6;border-radius:9px;background:white;font:inherit;color:#30372c}.vj-node-editor textarea{resize:vertical}.vj-node-editor :deep(select){max-width:100%}.vj-two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.vj-days{display:flex;flex-wrap:wrap;gap:10px;font-size:11px}.vj-days label{display:grid;gap:5px;text-align:center}.vj-hint{background:#f7f6f1;padding:12px;border-radius:8px}.vj-contact-list{max-height:220px;overflow:auto;border:1px solid #e4e5df;border-radius:9px;padding:10px}.vj-contact-list .vj-check{display:flex;align-items:center;gap:10px;font-size:12px;margin:12px 0}.vj-check small{display:block;font-size:10px;color:#777}.vj-rule{display:flex;gap:12px;background:#eef7f0;border:1px solid #d6e8da;padding:15px;border-radius:12px;color:#3e7853;margin:16px 0}.vj-rule svg{flex-shrink:0;margin-top:3px}.vj-rule p{margin:0}.vj-save{position:sticky;bottom:-24px;background:#fffef8;padding:14px 0;border-top:1px solid #e8e4d9;margin-top:20px;z-index:2}.vj-save>span{font-size:10px;color:#8a7648;display:block;margin-bottom:9px}.vj-save>div{display:flex;gap:8px}.vj-save button{font-size:11px;padding:10px 12px}.vj-conflict{background:#fff3df;border:1px solid #ead4a6;border-radius:9px;padding:12px;margin:12px 0}.vj-conflict p{margin:0 0 10px}.vj-conflict button{font-size:11px;white-space:normal}.vj-conflict p:last-child{margin:10px 0 0}.vj-save .error,.vj-save-warning{font-size:11px!important;color:#a13b2f!important;margin:0 0 9px}.vj-success{color:#23764b!important}.vj-shortcuts{margin-top:20px}.vj-shortcuts button{font-size:11px;width:100%;justify-content:space-between}.vj-node-editor :deep(.followup-settings){padding:12px!important;margin-top:20px}.vj-node-editor :deep(.followup-grid){grid-template-columns:1fr;gap:0}.vj-node-editor :deep(.variable-chips button){font-size:10px}.vj-node-editor :deep(.personalization-preview){padding:12px}.vj-node-editor :deep(.followup-settings select){font-size:12px}
</style>
