<script setup>
import {ref,onMounted} from 'vue'
import {ExternalLink,RefreshCw} from 'lucide-vue-next'
const state=ref(null),error=ref(''),loading=ref(false)
async function refresh(){loading.value=true;error.value='';try{const r=await fetch('/api/voice/provider/twilio',{headers:{Accept:'application/json'},signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error(r.status===403?'A conexão Twilio pertence ao workspace original do MA.':'Não foi possível consultar a preparação da Twilio.');state.value=await r.json()}catch(e){error.value=e.message}finally{loading.value=false}}
onMounted(refresh)
</script>
<template>
 <section class="twilio-panel">
  <div class="twilio-heading"><div><span class="eyebrow">OPERADORA ESCOLHIDA</span><h2>Twilio · Métodos de chamada</h2><p>Conecte a telefonia ao discador do MA. O teste interno de áudio continua disponível.</p></div><button class="secondary" :disabled="loading" @click="refresh"><RefreshCw :size="16"/> Atualizar conexão</button></div>
  <p v-if="error" class="error" role="alert">{{error}}</p>
  <template v-if="state">
   <div class="twilio-status" role="status"><strong>{{state.methods.programmable_voice.ready||state.methods.sip_trunk.ready?'Método habilitado para homologação manual':'Configure a conexão de voz escolhida'}}</strong><p>Configure um ou ambos os métodos. Escolha a conexão de cada ligação na aba Chamadas; não há troca automática de provedor em caso de falha. O recebimento externo ainda não está habilitado.</p></div>
   <div class="twilio-grid method-cards">
    <article class="table-card"><h3>API · Programmable Voice</h3><strong>{{state.methods.programmable_voice.ready?'Habilitado para teste manual':state.methods.programmable_voice.provider_configured?'Credenciais cadastradas · falta habilitar':'Aguardando configuração'}}</strong><p>Chamadas pelo navegador com a conexão de áudio da Twilio.</p><ul><li>Account SID (AC…)</li><li>API Key SID (SK…) e Secret · Standard / US1</li><li>Auth Token atual, para validar os retornos</li><li>TwiML Application SID (AP…)</li><li>Número Twilio autorizado para voz</li></ul><p>Na TwiML App, configure Voice Request URL com método POST:</p><code class="callback-url">{{state.methods.programmable_voice.dial_url}}</code><p>As credenciais são cadastradas em configuração privada no servidor. Depois, defina os destinos autorizados e habilite os testes.</p><a href="https://www.twilio.com/docs/voice/sdks/javascript/get-started" target="_blank" rel="noopener noreferrer">Configuração no console Twilio <ExternalLink :size="14"/></a></article>
    <article class="table-card"><h3>Asterisk · Elastic SIP Trunking</h3><strong>{{state.methods.sip_trunk.ready?'Habilitado para teste manual':state.methods.sip_trunk.provider_configured?'Credenciais cadastradas · falta instalar a rota':'Aguardando configuração'}}</strong><p>Chamadas pelo navegador com a conexão de áudio do PBX do MA.</p><ul><li>Account SID (AC…)</li><li>Trunk SID (TK…)</li><li>Termination SIP URI</li><li>Usuário e senha da Credential List SIP</li><li>Número Twilio autorizado para voz</li></ul><p>A senha SIP é diferente do Auth Token. Após cadastrar os dados e definir destinos, a rota precisa ser validada e instalada no PBX.</p></article>
   </div>
   <div class="twilio-grid">
    <article class="table-card"><h3>Preparar o método SIP</h3><ol><li>Crie a conta e confira o acesso ao Elastic SIP Trunking. A documentação atual informa que o tronco exige upgrade da conta de teste.</li><li>Crie um tronco exclusivo para o MA e configure sua Termination SIP URI.</li><li>Crie uma Credential List SIP exclusiva e associe-a ao tronco. Os dados serão cadastrados pelo responsável técnico em configuração privada.</li><li>Confirme o número de origem, a permissão para ligar ao Brasil e as condições de uso do discador.</li><li>Depois do cadastro, vamos homologar chamadas de saída com destinos de teste autorizados.</li></ol><a href="https://console.twilio.com/" target="_blank" rel="noopener noreferrer">Abrir console da Twilio <ExternalLink :size="14"/></a></article>
    <article class="table-card"><h3>Capacidade para crescer</h3><p>Chamadas simultâneas e novas chamadas por segundo são limites diferentes. A capacidade deverá respeitar a conta Twilio e os servidores disponíveis.</p><dl><div><dt>Simultaneidade planejada</dt><dd>{{state.planned_concurrency??'A definir'}}</dd></div><div><dt>Novas chamadas por segundo planejadas</dt><dd>{{state.planned_cps??'A definir'}}</dd></div><div><dt>Capacidade externa homologada</dt><dd>Pendente</dd></div></dl><p>O teste de eco mantém o limite de duas chamadas na VM atual. Os valores planejados não alteram esse limite nem comprovam capacidade de produção.</p><a href="https://www.twilio.com/docs/sip-trunking/scale-and-limits" target="_blank" rel="noopener noreferrer">Consultar limites da Twilio <ExternalLink :size="14"/></a></article>
   </div>
   <article class="table-card twilio-number"><h3>Validar o número antes de contratar</h3><p>As diretrizes da Twilio para o Brasil restringem o uso de número brasileiro de outra operadora como origem. Um número verificado na conta, sozinho, não comprova autorização para essa rota. Confirme com a Twilio o número elegível para saída e retorno.</p><p>Cada campanha pode usar um número único ou números separados para voz e WhatsApp. Um número de outra operadora no WhatsApp não comprova elegibilidade como origem de voz na Twilio. Prepare mensagens na aba WhatsApp.</p><a href="https://www.twilio.com/en-us/guidelines/br/voice" target="_blank" rel="noopener noreferrer">Diretrizes de voz para o Brasil <ExternalLink :size="14"/></a></article>
  </template>
 </section>
</template>
<style scoped>
.method-cards{margin-bottom:22px}.callback-url{display:block;overflow-wrap:anywhere;font-size:12px}.twilio-heading{display:flex;align-items:center;justify-content:space-between;gap:18px;margin:24px 0}.twilio-panel p,.twilio-panel li{color:#776e80;line-height:1.7;font-size:14px}.twilio-heading h2{margin:10px 0}.twilio-status{padding:20px 24px;background:#f2edf9;border:1px solid #e4d9f2;border-radius:12px;margin-bottom:22px}.twilio-status p{margin-bottom:0}.twilio-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.twilio-panel article{padding:26px}.twilio-panel li{margin:12px 0}.twilio-panel ol{padding-left:20px}.twilio-panel a{display:inline-flex;gap:8px;align-items:center;color:#6944aa;font-size:14px}.twilio-panel dl>div{display:flex;justify-content:space-between;gap:15px;padding:12px 0;border-bottom:1px solid #eee8f2;font-size:13px}.twilio-panel dd{margin:0;text-align:right}.twilio-number{margin-top:22px}@media(max-width:900px){.twilio-grid{grid-template-columns:1fr}.twilio-heading{align-items:flex-start;flex-direction:column}}
</style>
