<script setup>
import {ref,computed,onMounted,onBeforeUnmount} from 'vue'
import {Plus,RefreshCw,Users,Play,Pause} from 'lucide-vue-next'
const data=ref(null),error=ref(''),notice=ref(''),busy=ref(false),selected=ref(''),form=ref(null),pauseReason=ref('Intervalo')
const outcome=ref('no_answer'),qualification=ref('interested'),callbackAt=ref(''),notes=ref('')
const labels={available:'Disponível',paused:'Pausado',offline:'Offline',busy:'Em atendimento',wrapup:'Pós-atendimento',waiting:'Aguardando',reserved:'Reservado',done:'Concluído',blocked:'Impedido',running:'Em simulação',active:'Em atendimento',completed:'Concluído',expired:'Expirado',cancelled:'Cancelado',answered:'Atendida',no_answer:'Não atendeu',machine:'Caixa postal',invalid:'Número inválido',rejected:'Rejeitada',interested:'Interessado',callback:'Retorno agendado',not_interested:'Sem interesse',opt_out:'Pediu interrupção'}
const me=computed(()=>data.value?.agents.find(a=>a.id===data.value.user_id))
const queue=computed(()=>data.value?.queues.find(q=>q.id===Number(selected.value)))
const items=computed(()=>(data.value?.items||[]).filter(i=>i.queue_id===Number(selected.value)))
const history=computed(()=>(data.value?.history||[]).filter(i=>i.queue_id===Number(selected.value)))
let timer=null,disposed=false,refreshing=false,claimKey=null
const date=s=>s?new Date(/[Z+]|T.*-\d\d:\d\d$/.test(s)?s:s.replace(' ','T')+'Z').toLocaleString('pt-BR'):'—'
const person=id=>data.value?.agents.find(a=>a.id===id)?.name||'Atendente'
async function api(path='',method='GET',body){const r=await fetch('/api/voice/queues'+path,{method,signal:AbortSignal.timeout(10000),headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},...(body?{body:JSON.stringify(body)}:{})});if(r.status===204)return null;const result=await r.json();if(!r.ok)throw new Error(result.errors?Object.values(result.errors).flat().join(' · '):result.message||'Não foi possível atualizar a fila.');return result}
async function refresh(){if(refreshing||disposed)return;refreshing=true;try{const next=await api();if(disposed)return;data.value=next;if(!selected.value&&next.queues.length)selected.value=String(next.queues[0].id)}finally{refreshing=false}}
async function run(fn){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await fn();await refresh()}catch(e){error.value=e.message}finally{busy.value=false}}
function edit(q=null){form.value=q?{...q,agent_ids:[...q.agent_ids]}:{name:'',campaign_id:'',strategy:'fifo',wrapup_seconds:30,agent_ids:data.value?[data.value.user_id]:[]}}
async function save(){await run(async()=>{const f=form.value;const saved=await api(f.id?'/'+f.id:'',f.id?'PUT':'POST',{name:f.name,campaign_id:Number(f.campaign_id),strategy:f.strategy,wrapup_seconds:Number(f.wrapup_seconds),agent_ids:f.agent_ids,...(f.id?{revision:f.revision}:{})});form.value=null;selected.value=String(saved.id);notice.value='Fila salva. Carregue o público da campanha para iniciar.'})}
async function presence(status){await run(()=>api('/presence','POST',{status,pause_reason:status==='paused'?pauseReason.value:null}))}
async function transition(status){await run(()=>api('/'+queue.value.id+'/status','POST',{status}))}
async function populate(){await run(async()=>{const r=await api('/'+queue.value.id+'/populate','POST');notice.value=r.added+' contato(s) adicionado(s). Os já existentes foram preservados.'})}
async function claim(){await run(async()=>{claimKey ||= crypto.randomUUID();const result=await api('/'+queue.value.id+'/claim','POST',{idempotency_key:claimKey});claimKey=null;notice.value=result.message;notes.value='';outcome.value='no_answer';qualification.value='interested';callbackAt.value=''})}
async function finish(){await run(async()=>{const current=data.value.current;await api('/assignments/'+current.id+'/finish','POST',{outcome:outcome.value,notes:notes.value||null,...(outcome.value==='answered'?{qualification:qualification.value,...(qualification.value==='callback'?{callback_at:new Date(callbackAt.value).toISOString()}:{})}:{})});notice.value='Resultado simulado registrado. Retornos e intervalos foram aplicados.'})}
async function priority(item){await run(()=>api('/items/'+item.id+'/priority','POST',{priority:Number(item.priority)}))}
onMounted(()=>{run(refresh);timer=setInterval(async()=>{if(busy.value||disposed)return;try{await api('/heartbeat','POST');await refresh()}catch{if(!disposed)error.value='Conexão interrompida. A presença poderá expirar; atualize antes de continuar.'}},20000)})
onBeforeUnmount(()=>{disposed=true;clearInterval(timer)})
</script>
<template>
<section class="queues-panel">
 <div class="queue-heading"><div><span class="eyebrow">OPERAÇÃO · SIMULAÇÃO</span><h2>Filas e equipe</h2><p>Distribua contatos, teste o atendimento e organize os retornos.</p></div><div class="queue-actions"><button class="secondary" :disabled="busy" @click="run(refresh)"><RefreshCw :size="16"/> Atualizar filas</button><button class="primary" :disabled="!data||busy" @click="edit()"><Plus :size="16"/> Nova fila</button></div></div>
 <p class="queue-notice">Esta fila simula atendimentos de saída. Solicitar um contato não liga para ele nem envia mensagens. A fila de chamadas recebidas será habilitada em outra etapa.</p>
 <p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" class="queue-notice" role="status">{{notice}}</p>
 <article v-if="data" class="table-card queue-box"><div class="queue-heading"><h3>Sua disponibilidade</h3><strong role="status">{{labels[me?.status]||'Offline'}}</strong></div><div class="queue-actions"><button class="secondary" :disabled="busy" @click="presence('available')">Ficar disponível</button><label>Motivo da pausa<input v-model="pauseReason" maxlength="160" aria-label="Motivo da pausa"></label><button class="secondary" :disabled="busy||!pauseReason.trim()" @click="presence('paused')">Pausar atendimento</button><button class="secondary" :disabled="busy" @click="presence('offline')">Ficar offline</button></div><p>Disponibilidade renovada enquanto esta aba estiver aberta. Após {{data.presence_seconds}} segundos sem contato, uma reserva simulada pode expirar. Pausar impede novas reservas e permite concluir o atendimento atual.</p><p v-if="me?.status==='wrapup'">Próxima reserva após {{date(me.available_after)}}.</p></article>
 <article v-if="form" class="table-card queue-box"><h3>{{form.id?'Editar fila':'Configurar nova fila'}}</h3><form @submit.prevent="save"><fieldset :disabled="busy"><div class="queue-grid"><label>Nome da fila<input v-model="form.name" aria-label="Nome da fila" required maxlength="160"></label><label>Campanha vinculada<select v-model="form.campaign_id" aria-label="Campanha vinculada" required :disabled="!!form.id"><option value="">Selecione</option><option v-for="c in data.campaigns" :key="c.id" :value="c.id">{{c.name}} · {{c.status==='testing'?'Em simulação':c.status}}</option></select></label><label>Ordem dos contatos<select v-model="form.strategy" aria-label="Ordem dos contatos"><option value="fifo">Mais antigo elegível primeiro</option><option value="priority">Maior prioridade primeiro</option></select></label><label>Pós-atendimento em segundos<input v-model="form.wrapup_seconds" aria-label="Pós-atendimento em segundos" type="number" min="0" max="120" required></label></div><fieldset><legend>Atendentes vinculados</legend><label v-for="agent in data.agents" :key="agent.id" class="queue-check"><input type="checkbox" v-model="form.agent_ids" :value="agent.id">{{agent.name}}</label></fieldset><div class="queue-actions"><button class="primary" :disabled="!form.agent_ids.length">Salvar fila</button><button type="button" class="secondary" @click="form=null">Cancelar edição</button></div></fieldset></form><p v-if="!data.campaigns.length">Cadastre uma campanha com contatos na aba Campanhas antes de criar a fila.</p></article>
 <article class="table-card queue-box"><label>Fila de trabalho<select v-model="selected" aria-label="Fila de trabalho" @change="claimKey=null"><option value="">Selecione uma fila</option><option v-for="q in data?.queues||[]" :key="q.id" :value="String(q.id)">{{q.name}}</option></select></label><template v-if="queue"><div class="queue-heading"><h3>{{queue.name}}</h3><span class="status" :class="queue.status==='running'?'active':'paused'">{{labels[queue.status]}}</span></div><div class="queue-stats"><span>Aguardando <strong>{{queue.counts.waiting||0}}</strong></span><span>Reservados <strong>{{queue.counts.reserved||0}}</strong></span><span>Concluídos <strong>{{queue.counts.done||0}}</strong></span><span>Impedidos <strong>{{queue.counts.blocked||0}}</strong></span></div><div class="queue-actions"><button class="secondary" :disabled="busy" @click="populate">Carregar público da campanha</button><button class="secondary" :disabled="busy" @click="transition(queue.status==='running'?'paused':'running')"><component :is="queue.status==='running'?Pause:Play" :size="16"/>{{queue.status==='running'?'Pausar fila':'Iniciar fila simulada'}}</button><button class="secondary" :disabled="busy||queue.status!=='paused'" @click="edit(queue)">Editar fila</button><button class="primary" :disabled="busy||queue.status!=='running'||me?.status!=='available'||!!data.current||!queue.agent_ids.includes(data.user_id)" @click="claim">Solicitar próximo contato</button></div><p>A campanha também precisa estar em simulação e dentro dos dias e horários configurados. Cada solicitação reserva um contato para um atendente disponível; não há distribuição de áudio nesta etapa.</p></template><p v-else>Nenhuma fila selecionada. Crie uma fila e vincule os atendentes do MA.</p></article>
 <article v-if="data?.current" class="table-card queue-box current-assignment"><h3>Atendimento simulado em andamento</h3><p><strong>{{data.current.contact.name}}</strong> · {{data.current.contact.phone}}</p><p>Reserva até {{date(data.current.attempt.expires_at)}}. Esta tentativa é uma simulação.</p><p v-if="data.current.script" class="queue-script">{{data.current.script}}</p><form @submit.prevent="finish"><fieldset :disabled="busy"><div class="queue-grid"><label>Resultado simulado<select v-model="outcome" aria-label="Resultado simulado"><option value="no_answer">Não atendeu</option><option value="answered">Atendida</option><option value="busy">Ocupado</option><option value="machine">Caixa postal</option><option value="invalid">Número inválido</option><option value="rejected">Rejeitada</option></select></label><label v-if="outcome==='answered'">Qualificação<select v-model="qualification" aria-label="Qualificação"><option value="interested">Interessado</option><option value="callback">Retorno agendado</option><option value="not_interested">Sem interesse</option><option value="opt_out">Pediu interrupção</option></select></label><label v-if="outcome==='answered'&&qualification==='callback'">Retorno no seu horário local<input type="datetime-local" v-model="callbackAt" aria-label="Retorno no seu horário local" required></label></div><label>Notas do atendimento<textarea v-model="notes" aria-label="Notas do atendimento" maxlength="2000"/></label><button class="primary">Concluir simulação</button></fieldset></form></article>
 <article class="table-card queue-box"><h3><Users :size="18"/> Equipe do workspace</h3><div class="queue-table"><table><thead><tr><th>Atendente</th><th>Disponibilidade</th><th>Pausa</th></tr></thead><tbody><tr v-for="a in data?.agents||[]" :key="a.id"><td>{{a.name}}</td><td>{{labels[a.status]}}</td><td>{{a.pause_reason||'—'}}</td></tr></tbody></table></div></article>
 <article v-if="queue" class="table-card queue-box"><h3>Contatos da fila</h3><div class="queue-table"><table><thead><tr><th>Contato</th><th>Estado</th><th>Elegível a partir de</th><th>Prioridade</th><th>Observação</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{item.name}}<small>{{item.phone}}</small></td><td>{{labels[item.status]}}</td><td>{{date(item.available_at)}}</td><td><form class="priority-form" @submit.prevent="priority(item)"><input type="number" v-model="item.priority" min="0" max="100" required :aria-label="'Prioridade de '+item.name" :disabled="busy||item.status!=='waiting'"><button class="secondary" :disabled="busy||item.status!=='waiting'">Aplicar</button></form></td><td>{{item.reason||'—'}}</td></tr></tbody></table></div><p v-if="!items.length">Carregue o público da campanha. Até 500 itens são exibidos.</p></article>
 <article v-if="queue" class="table-card queue-box"><h3>Histórico de atendimentos simulados</h3><div class="queue-table"><table><thead><tr><th>Atendente</th><th>Estado</th><th>Resultado</th><th>Qualificação</th><th>Notas</th><th>Início</th></tr></thead><tbody><tr v-for="a in history" :key="a.id"><td>{{person(a.user_id)}}</td><td>{{labels[a.status]}}</td><td>{{a.outcome==='busy'?'Ocupado':labels[a.outcome]||'—'}}</td><td>{{labels[a.qualification]||'—'}}</td><td>{{a.notes||'—'}}</td><td>{{date(a.created_at)}}</td></tr></tbody></table></div><p v-if="!history.length">Sem atendimentos nesta fila. Até 100 reservas recentes do workspace são exibidas.</p></article>
</section>
</template>
<style scoped>
.queue-heading{display:flex;align-items:center;justify-content:space-between;gap:18px;margin:20px 0}.queue-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.queue-box{padding:24px;margin:20px 0}.queue-box p,.queue-heading p{color:#776e80;line-height:1.65}.queue-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.queue-box label:not(.queue-check){display:flex;flex-direction:column;gap:8px;font-size:13px;margin-bottom:14px}.queue-box select,.queue-box input:not([type=checkbox]){padding:11px;border:1px solid #ddd5e7;border-radius:8px;background:white;max-width:100%;box-sizing:border-box}.queue-box select{width:100%}.queue-box fieldset{border:0;padding:0;min-width:0;margin-bottom:16px}.queue-check{display:inline-flex;align-items:center;gap:8px;margin:12px}.queue-check input{width:auto}.queue-notice{padding:15px 20px;border-radius:10px;background:#f2edf9;color:#654590;font-size:14px;line-height:1.6}.queue-stats{display:flex;flex-wrap:wrap;gap:24px;margin:20px 0;color:#776e80}.queue-stats strong{display:block;font-size:24px;color:#3b2950}.queue-table{overflow:auto}.queue-table td{max-width:300px;overflow-wrap:anywhere}.queue-table small{display:block;color:#8a8092}.priority-form{display:flex;gap:6px;min-width:165px}.priority-form input{width:70px}.queue-script{white-space:pre-wrap;padding:16px;background:#f8f5fc}.current-assignment{border:1px solid #b4a0d8}.queues-panel button:disabled{opacity:.5}@media(max-width:800px){.queue-heading{align-items:flex-start;flex-direction:column}.queue-grid{grid-template-columns:1fr}.queue-box{padding:16px}.queue-actions{align-items:stretch}.queue-table table{min-width:540px}}
</style>
