<script setup>
import {ref,computed,onMounted,onBeforeUnmount} from 'vue'
import {voiceBase,voiceAuth,voiceCredentials} from '../voice/embed-session'
import {Phone,PhoneOff,RefreshCw} from 'lucide-vue-next'
const props=defineProps({reservation:Object,initialMethod:{type:String,default:'programmable_voice'},compact:{type:Boolean,default:false}});const emit=defineEmits(['failed','finished'])
const state=ref(null),phase=ref('idle'),error=ref(''),audio=ref(null),autoplayBlocked=ref(false),settling=ref('')
const method=ref(props.initialMethod)
const connection=computed(()=>state.value?.methods?.[method.value]||{})
const methodLabels={programmable_voice:'API · Programmable Voice',sip_trunk:'Asterisk · SIP Trunk'}
const contactId=ref(props.reservation?.contact_id||''),campaignId=ref(props.reservation?.queue?.campaign_id||null),consent=ref(false),evidence=ref(props.reservation?.contact?.consent_evidence||'')
const metrics=ref({packets_sent:0,packets_received:0,audio_energy:0})
const callLabels={pending:'Reservada',dialing:'Discando',answered:'Atendida',completed:'Encerrada',busy:'Ocupado',no_answer:'Não atendeu',failed:'Falhou',cancelled:'Cancelada',unknown:'Sem confirmação final'}
let device=null,apiCall=null,ua=null,call=null,grantId=null,poll=null,deadline=null,statsTimer=null,closing=false,disposed=false,startKey=null,generation=0
async function api(path='',method='GET',body){const r=await fetch(voiceBase()+'/calling'+path,{method,credentials:voiceCredentials(),signal:AbortSignal.timeout(8000),headers:{Accept:'application/json','Content-Type':'application/json',...voiceAuth()},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.message||'Não foi possível concluir a ligação.');return d}
async function refresh(){try{state.value=await api();if(props.reservation?.contact){state.value.contacts=state.value.contacts.filter(c=>c.id!==props.reservation.contact_id);state.value.contacts.push(props.reservation.contact)}}catch(e){if(!disposed)error.value=e.message}}
function pc(){return call?.sessionDescriptionHandler?.peerConnection}
async function collect(){try{const reports=await pc()?.getStats();if(!reports)return;let sent=0,received=0,energy=0;reports.forEach(s=>{if(s.type==='outbound-rtp'&&s.kind==='audio')sent+=s.packetsSent||0;if(s.type==='inbound-rtp'&&s.kind==='audio'){received+=s.packetsReceived||0;energy+=s.totalAudioEnergy||0}});metrics.value={packets_sent:sent,packets_received:received,audio_energy:energy}}catch{}}
async function stop(){generation++;if(closing)return;closing=true;clearInterval(statsTimer);clearTimeout(deadline);try{apiCall?.disconnect();apiCall=null;device?.destroy();device=null;await collect();if(call?.state==='Established')await call.bye();else if(call&&['Initial','Establishing'].includes(call.state))await call.cancel();}catch{}finally{const old=ua,connection=pc();ua=null;call=null;connection?.getSenders().forEach(s=>s.track?.stop());connection?.close();old?.stop().catch(()=>{});if(grantId)await api('/calls/'+grantId+'/cancel','POST').catch(()=>{});grantId=null;if(audio.value){audio.value.srcObject?.getTracks().forEach(t=>t.stop());audio.value.srcObject=null}phase.value='idle';closing=false;await refresh();emit('finished')}}
async function providerEnded(message){
 const id=grantId;if(closing||disposed)return
 await stop();if(disposed)return
 let row=state.value?.calls.find(c=>c.id===id)
 if(row?.started_at&&!row.capacity_released_at){try{await api('/calls/'+id+'/reconcile','POST');await refresh();row=state.value?.calls.find(c=>c.id===id)}catch{}}
 if(row?.started_at&&row.capacity_released_at&&['no_answer','busy','cancelled','completed'].includes(row.status)){error.value='';settling.value='Resultado confirmado pela telefonia.';return}
 if(row?.started_at&&!row.capacity_released_at&&row.status!=='unknown'){error.value='';settling.value='Aguardando confirmação do resultado pela telefonia.';return}
 error.value=message;emit('failed')
}
async function begin(){if(phase.value!=='idle')return;if(!consent.value||evidence.value.trim().length<8){error.value='Confirme a autorização e informe a evidência.';emit('failed');return;}error.value='';settling.value='';autoplayBlocked.value=false;phase.value='permission';const attempt=++generation;metrics.value={packets_sent:0,packets_received:0,audio_energy:0}
 try{
  if(!navigator.mediaDevices?.getUserMedia)throw new Error('Abra o MA em HTTPS em um navegador com suporte a microfone.')
  const microphone=await navigator.mediaDevices.getUserMedia({audio:true,video:false});microphone.getTracks().forEach(t=>t.stop());if(disposed||attempt!==generation)return
  startKey ||= crypto.randomUUID();const grant=await api('/calls','POST',{method:method.value,idempotency_key:startKey,contact_id:Number(contactId.value),campaign_id:campaignId.value,consent_confirmed:consent.value,consent_evidence:evidence.value,queue_reservation_id:props.reservation?.id||null});if(disposed||attempt!==generation){await api('/calls/'+grant.id+'/cancel','POST');return}grantId=grant.id;startKey=null
  if(grant.method==='programmable_voice'){
   const {Device}=await import('@twilio/voice-sdk');if(disposed||attempt!==generation)return
   phase.value='connecting';device=new Device(grant.access_token,{edge:grant.edge,logLevel:'silent',closeProtection:true})
   device.on('incoming',incoming=>incoming.reject())
   device.on('error',()=>{if(attempt===generation&&!closing){providerEnded('A Twilio não conectou o áudio. Confira a configuração e o histórico.')}})
   deadline=setTimeout(()=>{if(attempt===generation){error.value='Limite de duração atingido. Confira o resultado no histórico.';stop()}},(grant.max_seconds+grant.ring_seconds+20)*1000)
   const connected=await device.connect({params:grant.params});if(disposed||attempt!==generation){connected.disconnect();return}apiCall=connected
   apiCall.on('accept',()=>{if(attempt===generation){phase.value='active';refresh()}})
   apiCall.on('sample',sample=>{if(attempt===generation)metrics.value={packets_sent:sample.totals?.packetsSent||0,packets_received:sample.totals?.packetsReceived||0,audio_energy:0}})
   apiCall.on('disconnect',()=>{if(attempt===generation&&!closing)stop()})
   apiCall.on('cancel',()=>{if(attempt===generation&&!closing)stop()})
   apiCall.on('error',()=>{if(attempt===generation&&!closing){providerEnded('A ligação foi interrompida sem resultado confirmado. Consulte o histórico antes de retomar.')}})
   return
  }
  const {UserAgent,Inviter,SessionState}=await import('sip.js');if(disposed||attempt!==generation)return
  phase.value='connecting';deadline=setTimeout(()=>{if(phase.value!=='idle'){error.value='A conexão foi encerrada pelo limite de duração ou por falta de resposta. Confira o histórico.';stop()}},(grant.max_seconds+grant.ring_seconds+15)*1000)
  ua=new UserAgent({uri:UserAgent.makeURI(grant.aor),authorizationUsername:grant.username,authorizationPassword:grant.password,transportOptions:{server:grant.server},logBuiltinEnabled:false,logConfiguration:false,sessionDescriptionHandlerFactoryOptions:{peerConnectionConfiguration:{iceServers:[]}},delegate:{onInvite:i=>i.reject(),onDisconnect:()=>{if(attempt===generation&&!closing&&phase.value!=='idle'){error.value='A conexão de áudio foi interrompida. Atualize o diagnóstico e tente novamente.';stop()}}}})
  await ua.start();if(disposed||attempt!==generation)return
  call=new Inviter(ua,UserAgent.makeURI(grant.destination),{sessionDescriptionHandlerOptions:{constraints:{audio:true,video:false}}})
  call.stateChange.addListener(async value=>{
   if(attempt!==generation||disposed)return
   if(value===SessionState.Established){phase.value='active';const stream=new MediaStream();pc()?.getReceivers().forEach(r=>{if(r.track?.kind==='audio')stream.addTrack(r.track)});if(audio.value){audio.value.srcObject=stream;try{await audio.value.play()}catch{autoplayBlocked.value=true}}statsTimer=setInterval(collect,1000);await refresh()}
   if(value===SessionState.Terminated&&!closing){if(phase.value!=='active')error.value='Ligação não conectada. Confira o resultado confirmado pelo servidor no histórico.';await stop()}
  })
  await call.invite()
 }catch(e){if(attempt!==generation||disposed)return;emit('failed');error.value=e.name==='NotAllowedError'?'Permita o uso do microfone no navegador e tente novamente.':e.message||'Falha ao conectar o áudio.';await stop()}
}
async function startAuthorized(){await refresh();consent.value=true;await begin()}
defineExpose({startAuthorized,stop})
async function reconcile(id){try{await api('/calls/'+id+'/reconcile','POST');await refresh()}catch(e){error.value=e.message}}
onMounted(()=>{refresh();poll=setInterval(refresh,10000)})
onBeforeUnmount(()=>{disposed=true;clearInterval(poll);stop()})
const date=s=>s?new Date(s.replace(' ','T')+'Z').toLocaleString('pt-BR'):'—'
</script>
<template>
 <section class="calling-panel">
  <div v-if="!compact" class="calling-heading"><div><span class="eyebrow">VOZ · HOMOLOGAÇÃO TWILIO</span><h2>Ligar pelo navegador</h2><p>Chamadas manuais para contatos autorizados. Escolha a conexão. O histórico é confirmado pelo provedor de cada chamada.</p></div><button class="secondary" @click="refresh"><RefreshCw :size="16"/> Atualizar chamadas</button></div>
  <div v-if="error" role="alert" class="error">{{error}}</div><button v-if="compact&&initialMethod==='programmable_voice'&&reservation?.call_id&&state?.calls.some(c=>c.id===reservation.call_id&&!c.capacity_released_at)" type="button" class="secondary" @click="reconcile(reservation.call_id)">Consultar resultado na Twilio</button>
  <article v-if="!compact" class="table-card calling-box"><label>Método de chamada<select v-model="method" :disabled="phase!=='idle'" @change="startKey=null"><option value="programmable_voice">Twilio Programmable Voice · API</option><option value="sip_trunk">Twilio Elastic SIP Trunking · Asterisk</option></select></label><p>{{method==='programmable_voice'?'Áudio do navegador conectado diretamente à Twilio. Configure a API e uma TwiML App na aba Twilio.':'Áudio do navegador conectado ao Asterisk do MA. Configure o tronco e instale a rota de saída na aba Twilio.'}}</p></article>
  <article v-if="!compact" class="table-card calling-box"><span :class="['status',connection.ready?'active':'paused']">{{connection.ready?'Disponível para homologação':'Chamadas externas aguardando configuração'}}</span><div v-if="state" class="calling-grid"><div><h3>Preparação da telefonia</h3><ul><li>Credenciais do método: {{connection.provider_configured?'cadastradas':'pendentes'}}</li><li>Destinos e limites: {{connection.configured?'cadastrados':'pendentes'}}</li><li v-if="method==='sip_trunk'">Rota exclusiva no PBX: {{connection.installed?'instalada':'pendente'}}</li><li v-if="method==='programmable_voice'">API habilitada: {{connection.enabled?'sim':'pendente'}}</li><li>Liberação para teste: {{connection.ready?'disponível':'pendente'}}</li></ul></div><div><h3>Limites de homologação</h3><p>Uma ligação externa por vez · até {{connection.max_seconds}} segundos de conversa · {{connection.ring_seconds}} segundos de toque · {{connection.daily_limit}} tentativas por dia (UTC).</p><p>Origem: {{connection.caller_id||'a configurar'}}</p><p>Destinos autorizados: {{(connection.allowed_recipients||[]).join(', ')||'a configurar'}}</p></div></div><p>Os dois métodos e o teste interno de áudio compartilham o controle de homologação do MA. Os limites de homologação podem evoluir após os testes de capacidade. Tarifas e permissões da rota devem ser confirmadas na Twilio.</p></article>
  <article class="table-card calling-box"><h3>{{compact?'Conversa com o contato':'Nova ligação de teste'}}</h3><p v-if="settling" role="status">{{settling}}</p><form @submit.prevent="compact?startAuthorized():begin()"><fieldset v-if="!compact" :disabled="phase!=='idle'||!connection.ready"><div class="calling-grid"><label>Contato para ligar<select v-model="contactId" :disabled="!!reservation" required @change="startKey=null"><option value="">Selecione um contato</option><option v-for="c in (state?.contacts||[]).filter(c=>c.consent&&!c.suppressed_at&&!c.replied_at)" :key="c.id" :value="c.id">{{c.name}} · {{c.phone}}</option></select></label><label>Campanha da ligação · opcional<select v-model="campaignId" :disabled="!!reservation" @change="startKey=null"><option :value="null">Teste avulso</option><option v-for="c in state?.campaigns||[]" :key="c.id" :value="c.id">{{c.name}}</option></select></label></div><label>Evidência da autorização da ligação<textarea v-model="evidence" minlength="8" maxlength="1000" required @input="startKey=null"/></label><label class="check-label"><input type="checkbox" v-model="consent" required>Confirmo a autorização do destinatário para esta ligação de teste.</label></fieldset><div class="calling-controls"><button v-if="phase==='idle'" class="primary" :disabled="!connection.ready||(compact&&!!reservation?.call_id)"><Phone :size="17"/> Ligar para contato</button><button v-else type="button" class="secondary" @click="stop"><PhoneOff :size="17"/> Encerrar ligação</button></div></form><p role="status">{{({idle:'Use fones de ouvido. O microfone será solicitado ao iniciar.',permission:'Aguardando permissão do microfone',connecting:'Discando / aguardando atendimento',active:'Áudio conectado'})[phase]}}</p><audio ref="audio" autoplay playsinline/><button v-if="autoplayBlocked" class="secondary" @click="audio.play();autoplayBlocked=false">Permitir reprodução do áudio</button><p v-if="phase==='active'">Pacotes enviados: {{metrics.packets_sent}} · recebidos: {{metrics.packets_received}}</p><small>Envio real sujeito à cobrança da operadora. Não há gravação. O receptivo pode ser conectado em Minha operação, após configurar a rota de entrada. A sequência progressiva depende da disponibilidade do atendente.</small></article>
  <article v-if="!compact" class="table-card calling-box"><h3>Suas últimas 50 ligações</h3><div class="calling-table"><table><thead><tr><th>Método</th><th>Destino</th><th>Estado</th><th>Início</th><th>Conversa</th><th>Resultado técnico</th></tr></thead><tbody><tr v-for="c in state?.calls||[]" :key="c.id"><td>{{methodLabels[c.method]}}</td><td>{{c.destination}}</td><td>{{callLabels[c.status]}}<small v-if="c.status==='unknown'&&!c.capacity_released_at">Conferência do provedor necessária antes de outra ligação.</small></td><td>{{date(c.created_at)}}</td><td>{{c.bill_seconds}} s</td><td>{{c.dial_status||'—'}} {{c.cause?'· causa '+c.cause:''}}<button v-if="c.method==='programmable_voice'&&!c.capacity_released_at&&c.status!=='pending'" type="button" class="secondary" @click="reconcile(c.id)">Consultar na Twilio</button></td></tr></tbody></table></div><p v-if="!state?.calls?.length">Nenhuma ligação externa registrada.</p><small>Estabelecer áudio no navegador não substitui a confirmação de atendimento e encerramento no servidor. Para contar as tentativas e enviar WhatsApp após não atendimento, vincule a chamada à campanha com envio automático habilitado. Chamadas avulsas não disparam mensagens.</small></article>
 </section>
</template>
<style scoped>
.calling-heading{display:flex;justify-content:space-between;align-items:center;gap:18px;margin:22px 0}.calling-box{padding:24px;margin-bottom:22px}.calling-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.calling-box p,.calling-box li{line-height:1.7;color:#776e80}.calling-box label:not(.check-label){display:flex;flex-direction:column;gap:8px;font-size:13px;font-weight:600;margin-bottom:16px}.calling-box select{padding:11px;width:100%;border:1px solid #ddd5e7;border-radius:8px;background:white}.calling-box fieldset{border:0;padding:0;min-width:0}.calling-box small{display:block;color:#8a8092;font-size:12px;line-height:1.6}.calling-controls{display:flex;gap:12px;margin:20px 0}.calling-table{overflow:auto}.calling-panel button:disabled,.calling-panel fieldset:disabled{opacity:.5}.calling-panel .check-label{display:flex;flex-direction:row;align-items:center;gap:10px}.calling-panel .check-label input{width:auto}@media(max-width:800px){.calling-grid{grid-template-columns:1fr}.calling-heading{align-items:flex-start;flex-direction:column}.calling-box{padding:18px}}
</style>
