<script setup>
import {ref,onMounted,onBeforeUnmount,computed} from 'vue'
import {AudioQualityMonitor,qualityState,qualityLimits} from '../voice/audio-quality'
import {Headphones,Phone,PhoneOff,RefreshCw,Mic} from 'lucide-vue-next'
const state=ref(null),phase=ref('idle'),error=ref(''),audio=ref(null),autoplayBlocked=ref(false)
let monitor=new AudioQualityMonitor()
const metrics=ref(monitor.payload()),quality=ref(monitor.summary()),selectedHistory=ref(null)
const qualityLabels={good:'Indicadores dentro da referência',attention:'Atenção à conexão',insufficient:'Amostra insuficiente'}
const qualityLevel=computed(()=>qualityState(quality.value))
const value=(n,unit='')=>n===null||n===undefined?'Não medido':Number(n).toLocaleString('pt-BR',{maximumFractionDigits:2})+unit
const historyQuality=computed(()=>selectedHistory.value?.client_metrics?.quality)
function graph(q,key){const points=q?.timeline||[];const known=points.filter(s=>s[key]!==null);if(!known.length)return '';const max=Math.max(qualityLimits[key]||0,...known.map(s=>s[key]),1);return points.map((s,i)=>s[key]===null?null:`${i/Math.max(points.length-1,1)*300},${64-s[key]/max*58}`).filter(Boolean).join(' ')}
function download(){const blob=new Blob([JSON.stringify({kind:'internal_echo',quality:historyQuality.value||quality.value,scope:'Navegador → servidor MA. Não comprova qualidade da operadora ou microfone do cliente.'},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='diagnostico-audio-ma.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const labels={pending:'Reservado',connecting:'Conectando',active:'Áudio conectado',ended:'Encerrado pelo servidor',expired:'Sem confirmação final',cancelled:'Cancelado antes da conexão'}
let ua=null,call=null,grantId=null,poll=null,deadline=null,statsTimer=null,closing=false,disposed=false,startKey=null,generation=0
async function api(path='',method='GET',body){const r=await fetch('/api/voice/audio'+path,{method,signal:AbortSignal.timeout(8000),headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.message||'Não foi possível concluir o teste.');return d}
async function refresh(){try{state.value=await api()}catch(e){if(!disposed)error.value=e.message}}
function pc(){return call?.sessionDescriptionHandler?.peerConnection}
async function collect(){try{const reports=await pc()?.getStats();if(!reports)return;quality.value=monitor.sample(reports);metrics.value=monitor.payload()}catch{}}
async function stop(){generation++;if(closing)return;closing=true;clearInterval(statsTimer);clearTimeout(deadline);try{await collect();if(grantId)await api('/sessions/'+grantId+'/metrics','POST',metrics.value).catch(()=>{});if(call?.state==='Established')await call.bye();else if(call&&['Initial','Establishing'].includes(call.state))await call.cancel();}catch{}finally{const old=ua,connection=pc();ua=null;call=null;connection?.getSenders().forEach(s=>s.track?.stop());connection?.close();old?.stop().catch(()=>{});if(grantId)await api('/sessions/'+grantId+'/abandon','POST').catch(()=>{});grantId=null;if(audio.value){audio.value.srcObject?.getTracks().forEach(t=>t.stop());audio.value.srcObject=null}phase.value='idle';closing=false;await refresh()}}
async function begin(){if(phase.value!=='idle')return;error.value='';autoplayBlocked.value=false;phase.value='permission';const attempt=++generation;monitor=new AudioQualityMonitor();quality.value=monitor.summary();metrics.value=monitor.payload();selectedHistory.value=null
 try{
  if(!navigator.mediaDevices?.getUserMedia)throw new Error('Abra o MA em HTTPS em um navegador com suporte a microfone.')
  const microphone=await navigator.mediaDevices.getUserMedia({audio:true,video:false});microphone.getTracks().forEach(t=>t.stop());if(disposed||attempt!==generation)return
  startKey=crypto.randomUUID();const grant=await api('/sessions','POST',{idempotency_key:startKey});if(disposed||attempt!==generation){await api('/sessions/'+grant.id+'/abandon','POST');return}grantId=grant.id
  const {UserAgent,Inviter,SessionState}=await import('sip.js');if(disposed||attempt!==generation)return
  phase.value='connecting';deadline=setTimeout(()=>{if(phase.value!=='idle'){error.value='O teste foi encerrado pelo limite de duração ou por falta de conexão.';stop()}},75000)
  ua=new UserAgent({uri:UserAgent.makeURI(grant.aor),authorizationUsername:grant.username,authorizationPassword:grant.password,transportOptions:{server:grant.server},logBuiltinEnabled:false,logConfiguration:false,sessionDescriptionHandlerFactoryOptions:{peerConnectionConfiguration:{iceServers:[]}},delegate:{onInvite:i=>i.reject(),onDisconnect:()=>{if(attempt===generation&&!closing&&phase.value!=='idle'){error.value='A conexão de áudio foi interrompida. Atualize o diagnóstico e tente novamente.';stop()}}}})
  await ua.start();if(disposed||attempt!==generation)return
  call=new Inviter(ua,UserAgent.makeURI(grant.destination),{sessionDescriptionHandlerOptions:{constraints:{audio:true,video:false}}})
  call.stateChange.addListener(async value=>{
   if(attempt!==generation||disposed)return
   if(value===SessionState.Established){phase.value='active';const stream=new MediaStream();pc()?.getReceivers().forEach(r=>{if(r.track?.kind==='audio')stream.addTrack(r.track)});if(audio.value){audio.value.srcObject=stream;try{await audio.value.play()}catch{autoplayBlocked.value=true}}statsTimer=setInterval(collect,1000);await refresh()}
   if(value===SessionState.Terminated&&!closing){if(phase.value!=='active')error.value='O servidor não aceitou ou não conseguiu conectar o teste. Atualize o diagnóstico e tente novamente.';await stop()}
  })
  await call.invite()
 }catch(e){if(attempt!==generation||disposed)return;error.value=e.name==='NotAllowedError'?'Permita o uso do microfone no navegador e tente novamente.':e.message||'Falha ao conectar o áudio.';await stop()}
}
defineExpose({requestLeave:fn=>{if(phase.value!=='idle'){error.value='Encerre o diagnóstico de áudio antes de sair.';return}fn()}})
onMounted(()=>{refresh();poll=setInterval(refresh,5000)})
onBeforeUnmount(()=>{disposed=true;clearInterval(poll);stop()})
const date=s=>s?new Date(s.replace(' ','T')+'Z').toLocaleString('pt-BR'):'—'
</script>

<template>
 <section class="audio-panel">
  <div class="audio-intro"><div><span class="eyebrow">DIAGNÓSTICO · SEM TELEFONAR PARA CONTATOS</span><h2>Qualidade de voz e conexão</h2><p>Confira o retorno da sua voz e os indicadores da conexão com o servidor do MA. Nenhum telefone de cliente é chamado.</p></div><Headphones :size="40"/></div>
  <div v-if="error" class="error" role="alert">{{error}}</div>
  <div class="audio-grid"><article class="table-card audio-box"><span :class="['status',state?.ready?'active':'paused']">{{state?.ready?'Servidor de áudio disponível':'Verificando conexão / indisponível'}}</span><h3>Microfone e retorno de voz</h3><p>Use fones de ouvido para evitar realimentação. Ao iniciar, permita o acesso ao microfone. O teste termina em até 60 segundos.</p><div class="audio-controls"><button v-if="phase==='idle'" class="primary" :disabled="!state?.ready" @click="begin"><Mic :size="17"/> Iniciar teste de áudio</button><button v-else class="secondary" @click="stop"><PhoneOff :size="17"/> Encerrar teste</button><button class="secondary" @click="refresh"><RefreshCw :size="16"/> Atualizar diagnóstico</button></div><p role="status" class="audio-state">{{({idle:'Pronto para iniciar',permission:'Aguardando permissão do microfone',connecting:'Conectando ao servidor',active:'Áudio conectado · fale para ouvir o retorno'})[phase]}}</p><audio ref="audio" autoplay playsinline/><button v-if="autoplayBlocked" class="secondary" @click="audio.play();autoplayBlocked=false">Permitir reprodução do áudio</button><dl class="audio-metrics"><div><dt>Pacotes enviados</dt><dd>{{metrics.packets_sent}}</dd></div><div><dt>Pacotes recebidos</dt><dd>{{metrics.packets_received}}</dd></div></dl><small>Diagnóstico informado pelo navegador. O histórico abaixo é confirmado pelo servidor; a qualidade percebida deve ser conferida ouvindo o retorno.</small></article>
  <article class="table-card audio-box"><span :class="['status',qualityLevel==='good'?'active':'paused']">{{qualityLabels[qualityLevel]}}</span><h3>O que este teste mede</h3><p>Atraso de ida e volta, variação na chegada dos pacotes e perdas entre este navegador e o servidor. Deixe o teste ativo por pelo menos 10 segundos.</p><dl class="quality-grid"><div><dt>Atraso · RTT p95</dt><dd>{{value(quality.rtt_p95_ms,' ms')}}</dd></div><div><dt>Variação · jitter p95</dt><dd>{{value(quality.jitter_p95_ms,' ms')}}</dd></div><div><dt>Perda na recepção</dt><dd>{{value(quality.loss_percent,' %')}}</dd></div><div><dt>Codec negociado</dt><dd>{{quality.codec?.replace('audio/','')||'Aguardando conexão'}}<small v-if="quality.clock_rate">{{quality.clock_rate/1000}} kHz · {{quality.channels}} canal</small></dd></div></dl><p class="quality-note">Referências de atenção: RTT acima de 400 ms, jitter acima de 30 ms ou perda acima de 1%. São indicadores técnicos, não uma nota de qualidade percebida.</p><details><summary>Detalhes técnicos</summary><p>Protocolo: {{quality.transport||'Não medido'}} · mídia criptografada: {{quality.encrypted===null?'Não confirmada':quality.encrypted?'Sim':'Não confirmada'}}.</p><p>RTT obtido por {{quality.rtt_source||'medição ainda indisponível'}}. Buffer médio: {{value(quality.jitter_buffer_ms,' ms')}}. Amostras reconstruídas: {{value(quality.concealment_percent,' %')}}.</p><p>Envio: {{value(quality.send_kbps,' kbps')}} · recepção: {{value(quality.receive_kbps,' kbps')}}.</p><p>Sem rota alternativa TURN no teste interno. Redes que bloqueiam UDP precisam ser verificadas antes da operação.</p></details><p>Este diagnóstico não mede a ligação pela Twilio/operadora até o cliente. O resultado também depende do computador, headset e rede de quem inicia o teste. Nenhum áudio é gravado.</p></article></div>
  <div v-if="quality.sample_count" class="table-card quality-chart"><div><h3>Evolução durante o teste</h3><button class="secondary" @click="selectedHistory=null;download()">Baixar diagnóstico</button></div><p>{{quality.sample_count}} medições · {{value(quality.observed_seconds,' s')}} observados</p><div class="quality-grid"><figure><figcaption>Jitter · {{value(quality.jitter_ms,' ms')}}</figcaption><svg viewBox="0 0 300 70" role="img" aria-label="Evolução do jitter"><polyline :points="graph(quality,'jitter_ms')" fill="none" stroke="#be9134" stroke-width="2"/></svg></figure><figure><figcaption>Ida e volta · {{value(quality.rtt_ms,' ms')}}</figcaption><svg viewBox="0 0 300 70" role="img" aria-label="Evolução do atraso de ida e volta"><polyline :points="graph(quality,'rtt_ms')" fill="none" stroke="#397b5b" stroke-width="2"/></svg></figure></div></div>
  <div class="table-card audio-history"><h3>Seus testes internos de áudio</h3><table><thead><tr><th>Início</th><th>Estado</th><th>Atendido pelo servidor</th><th>Duração</th><th>Diagnóstico</th></tr></thead><tbody><tr v-for="s in state?.sessions||[]" :key="s.id"><td>{{date(s.created_at)}}</td><td>{{labels[s.status]}}</td><td>{{date(s.answered_at)}}</td><td>{{s.duration}} s</td><td><button v-if="s.client_metrics?.quality" class="secondary" @click="selectedHistory=s">{{qualityLabels[qualityState(s.client_metrics.quality)]}}</button><span v-else>Sem métricas detalhadas</span></td></tr></tbody></table><div v-if="historyQuality" class="history-quality"><h3>Diagnóstico de {{date(selectedHistory.created_at)}}</h3><p>{{qualityLabels[qualityState(historyQuality)]}} · {{historyQuality.codec}} · RTT p95 {{value(historyQuality.rtt_p95_ms,' ms')}} · jitter p95 {{value(historyQuality.jitter_p95_ms,' ms')}} · perda {{value(historyQuality.loss_percent,' %')}}.</p><button class="secondary" @click="download">Baixar diagnóstico selecionado</button> <button class="secondary" @click="selectedHistory=null">Fechar detalhes</button></div><p v-if="!state?.sessions?.length">Nenhum teste interno registrado.</p></div>
 </section>
</template>

<style scoped>
.audio-intro{display:flex;justify-content:space-between;gap:20px;align-items:center;margin:24px 0}.audio-intro p{max-width:750px;color:#776e80;line-height:1.7}.audio-grid{display:grid;grid-template-columns:1.2fr 1fr;gap:22px}.audio-box{padding:26px}.audio-box p,.audio-box li{color:#776e80;line-height:1.7;font-size:14px}.audio-box small{display:block;color:#8a8092;line-height:1.6}.audio-controls{display:flex;gap:10px;flex-wrap:wrap;margin:24px 0}.audio-state{font-weight:600;color:#513775!important}.audio-metrics{display:flex;gap:30px;padding:18px;background:#f8f5fa;border-radius:10px}.audio-metrics dt{font-size:12px;color:#776e80}.audio-metrics dd{margin:8px 0 0;font-size:25px;font-weight:600}.audio-history{padding:22px;margin-top:22px;overflow:auto}.audio-history p{color:#8a8092}.quality-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:22px 0}.quality-grid dt,.quality-grid figcaption{font-size:12px;color:#707966}.quality-grid dd{font-size:22px;margin:8px 0;color:#343e2c}.quality-grid small{font-size:11px}.quality-grid figure{margin:0;min-width:0}.quality-grid svg{width:100%;height:90px;background:#f4f6ef;border-radius:9px;margin-top:12px}.quality-chart{padding:24px;margin-top:22px}.quality-chart>div:first-child{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.quality-chart p,.quality-note{font-size:12px!important;color:#738067!important}.history-quality{margin-top:18px;border-top:1px solid #e0e5d7;padding-top:20px}.audio-box summary{font-size:12px;cursor:pointer}.audio-box details{border-top:1px solid #e0e5d7;padding-top:15px;margin:18px 0}.audio-panel button:disabled{opacity:.5;cursor:not-allowed}@media(max-width:900px){.audio-grid{grid-template-columns:1fr}.audio-intro svg{display:none}}
</style>
