<script setup>
import {checkMicrophone,microphoneMessage} from '../voice/microphone'
import {ref,computed,onMounted,onBeforeUnmount,nextTick} from 'vue'
import {voiceApi as api,labels} from '../voice/operations'
import {isEmbedded,voiceBase,voiceAuth} from '../voice/embed-session'
import VoiceCallingPanel from './VoiceCallingPanel.vue'
import MicrophoneCheck from './MicrophoneCheck.vue'
import VoiceDispositionForm from './VoiceDispositionForm.vue'
const props=defineProps({catalog:Object,view:{type:String,default:'supervisor'},inboundReady:Boolean})
const state=ref(null),selected=ref(''),form=ref(null),error=ref(''),notice=ref(''),busy=ref(false),armed=ref(false),authorization=ref(false),dialer=ref(null),countdown=ref(0)
const voiceNumbers=computed(()=>{const options=(props.catalog.queue_channels?.voice_numbers||[]).filter(n=>n.method===form.value?.calling_method).map(n=>n.number);if(form.value?.voice_number&&!options.includes(form.value.voice_number))options.push(form.value.voice_number);return options})
const whatsappSenders=computed(()=>(props.catalog.queue_channels?.senders||[]).filter(s=>form.value?.number_mode!=='single'||s.number===form.value?.voice_number))
const directions={inbound:'Receptivo',outbound:'Saída',mixed:'Entrada e saída'}
const method=computed(()=>queue.value?.calling_method||'programmable_voice')
const outgoing=computed(()=>(state.value?.queues||[]).filter(q=>q.direction!=='inbound'))
const queue=computed(()=>state.value?.queues.find(q=>q.id===Number(selected.value)))
let timer=null,disposed=false,polling=false,claimKey=null,epoch=0,nextAt=0
function pause(){armed.value=false;epoch++;countdown.value=0}
async function refresh(){const s=await api('/operations/queues');if(props.view==='agent')s.queues=s.queues.filter(q=>q.agent_ids.includes(props.catalog.user_id));if(!disposed){state.value=s;if(props.view==='agent'&&!s.current&&!s.queues.some(q=>q.id===Number(selected.value)&&q.direction!=='inbound')){selected.value='';pause()}}}
async function run(fn){if(busy.value)return;busy.value=true;error.value='';try{await fn()}catch(e){error.value=microphoneMessage(e);pause()}finally{busy.value=false}}
function edit(q=null){form.value=q?{...q,incoming_number:null,agent_ids:[...q.agent_ids],campaign_ids:[...(q.campaign_ids||[])]}:{name:'',direction:'outbound',campaign_ids:[],calling_method:'programmable_voice',manual_enabled:true,allow_landline:true,allow_mobile:true,mode:'preview',strategy:'fifo',wrapup_seconds:30,agent_ids:[],incoming_number:null,voice_number:null,whatsapp_sender_id:null,number_mode:'separate',revision:0}}
async function save(){const q=form.value;await api('/operations/queues'+(q.id?'/'+q.id:''),q.id?'PUT':'POST',{name:q.name,direction:q.direction,incoming_number:q.direction==='outbound'?null:(q.incoming_number||null),voice_number:q.voice_number||null,whatsapp_sender_id:q.whatsapp_sender_id||null,number_mode:q.number_mode||'separate',calling_method:q.calling_method,manual_enabled:q.manual_enabled,allow_landline:q.allow_landline,allow_mobile:q.allow_mobile,mode:q.mode,strategy:'fifo',wrapup_seconds:q.wrapup_seconds,agent_ids:q.agent_ids,revision:q.revision});form.value=null;await refresh()}
async function presence(status){if(status!=='available')pause();await api('/queues/presence','POST',{status,pause_reason:status==='paused'?'Pausa na operação real':null});await refresh()}
async function online(){if(!authorization.value)return;if(!queue.value&&!props.inboundReady)throw Error('Escolha uma fila de saída ou conecte o receptivo antes de ficar disponível.');if(queue.value&&isEmbedded()&&method.value==='sip_trunk')throw Error('Esta fila usa SIP. Abra Minha operação no MA ou solicite uma fila Twilio API para o discador incorporado.');await checkMicrophone();if(disposed)return;await presence('available');if(queue.value?.mode==='progressive')await startProgressive()}
async function claim(auto=false){const version=epoch;claimKey ||= crypto.randomUUID();const result=await api('/operations/queues/'+queue.value.id+'/claim','POST',{idempotency_key:claimKey});claimKey=null;await refresh();if(!result.reservation){notice.value=[result.message,...Object.entries(result.reasons||{}).map(([k,v])=>`${v}: ${k}`)].join(' ');nextAt=Date.now()+Math.max(5,result.retry_after||15)*1000;return}if(auto&&armed.value&&version===epoch&&!disposed){await nextTick();await dialer.value?.startAuthorized()}}
async function startProgressive(){if(!authorization.value)return;pause();armed.value=true;nextAt=Date.now()+5000;notice.value='Progressivo iniciado. Você pode parar a sequência a qualquer momento.'}
async function tick(){if(disposed||polling||busy.value)return;polling=true;try{if(props.view==='agent')await api('/queues/heartbeat','POST',{});await refresh();if(!armed.value||disposed)return;if(state.value.presence?.status!=='available'){pause();return}if(!queue.value||queue.value.direction==='inbound'||queue.value.mode!=='progressive'){pause();return}if(queue.value?.status!=='running'){notice.value='Aguardando a supervisão habilitar a fila.';return}if(state.value.current){nextAt=Date.now()+5000;if(state.value.current.call?.status==='unknown'){error.value='Chamada sem confirmação final. Consulte a Twilio antes de continuar.';pause()}return}const wrap=state.value.presence?.available_after;const after=wrap?Date.parse(/[Zz]|[+-]\d\d:\d\d$/.test(wrap)?wrap:wrap.replace(' ','T')+'Z'):0;countdown.value=Math.max(0,Math.ceil((Math.max(nextAt,after)-Date.now())/1000));if(!countdown.value)await claim(true)}catch(e){if(!disposed){error.value=microphoneMessage(e);pause()}}finally{polling=false}}
onMounted(()=>{run(refresh);timer=setInterval(tick,5000)})
function beforeUnload(e){if(props.view==='agent'&&(armed.value||state.value?.current)){e.preventDefault();e.returnValue=''}}
function pageHide(){if(props.view!=='agent')return;if(isEmbedded()){fetch(voiceBase()+'/queues/presence',{method:'POST',credentials:'omit',keepalive:true,headers:{'Content-Type':'application/json',...voiceAuth()},body:JSON.stringify({status:'offline'})}).catch(()=>{});return}const token=document.querySelector('meta[name="csrf-token"]').content;navigator.sendBeacon('/api/voice/queues/presence',new Blob([JSON.stringify({status:'offline',_token:token})],{type:'application/json'}))}
onMounted(()=>{window.addEventListener('beforeunload',beforeUnload);window.addEventListener('pagehide',pageHide)})
onBeforeUnmount(()=>{disposed=true;pause();clearInterval(timer);window.removeEventListener('beforeunload',beforeUnload);window.removeEventListener('pagehide',pageHide);if(props.view==='agent')api('/queues/presence','POST',{status:'offline'}).catch(()=>{})})
async function requestLeave(fn){if(props.view==='agent'&&state.value?.current){error.value='Conclua a chamada e a tabulação antes de sair da operação.';return}if(props.view==='agent'){pause();await api('/queues/presence','POST',{status:'offline'})}fn()}
async function failure(){pause();await presence('paused')}
defineExpose({requestLeave})
</script>
<template><section class="live-operation">
 <h3>{{view==='agent'?'Sua disponibilidade e filas':'Filas e vínculos de atendimento'}}</h3>
 <p>{{view==='agent'?'O administrador define suas filas. Você controla sua disponibilidade; a campanha de cada contato é escolhida pela fila.':'Defina aqui a equipe, os números e as permissões. Na cadência, selecione a fila responsável.'}}</p>
 <p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p>
 <div class="op-tabs"><button v-if="view==='supervisor'&&catalog.can_manage" class="primary" @click="edit()">Nova fila</button><button class="secondary" :disabled="busy" @click="run(refresh)">Atualizar filas</button><a v-if="view==='supervisor'" class="secondary" href="#/inbound">Vincular números de entrada</a></div>
 <template v-if="view==='supervisor'"><form v-if="form" class="table-card op-box queue-config" @submit.prevent="run(save)"><h3>{{form.id?'Editar':'Criar'}} fila</h3><p>A fila define a equipe, os números e as permissões. Selecione esta fila dentro de cada cadência.</p>
<fieldset><legend>Identificação e atendimento</legend><div class="queue-form-grid"><label>Nome da fila<input v-model="form.name" required maxlength="160" placeholder="Ex.: Equipe comercial"></label><label>Tipo de atendimento<select v-model="form.direction"><option value="inbound">Receptivo · entrada</option><option value="outbound">Ativo · saída</option><option value="mixed">Entrada e saída</option></select></label><label>Pós-atendimento (segundos)<input type="number" v-model.number="form.wrapup_seconds" min="0" max="120" required></label></div></fieldset>
<fieldset><legend>Números e canais da fila</legend><div class="queue-form-grid"><template v-if="form.direction!=='inbound'"><label>Telefonia da saída<select v-model="form.calling_method" @change="form.voice_number=null"><option value="programmable_voice">Twilio API</option><option value="sip_trunk">SIP / Asterisk</option></select></label><label>Número de voz da fila<select aria-label="Número de voz da fila" v-model="form.voice_number" required><option :value="null">Selecione uma origem autorizada</option><option v-for="n in voiceNumbers" :key="n" :value="n">{{n}}</option></select></label><label>Modo da saída<select v-model="form.mode"><option value="preview">Preview · agente confirma a ligação</option><option value="progressive">Progressivo · próximo contato elegível</option></select></label></template><label>Números de voz e WhatsApp<select aria-label="Números de voz e WhatsApp" v-model="form.number_mode" @change="form.whatsapp_sender_id=null"><option value="separate">Números separados</option><option value="single">Mesmo número nos dois canais</option></select></label><label>WhatsApp da fila<select aria-label="WhatsApp da fila" v-model="form.whatsapp_sender_id"><option :value="null">Sem WhatsApp</option><option v-for="s in whatsappSenders" :key="s.id" :value="s.id">{{s.label}} · {{s.number}} · {{s.provider==='qr'?'QR Code':'Twilio API'}}</option></select></label></div><p>As cadências vinculadas herdam estes números. Conecte novos canais em Cadências → Canais.</p><div v-if="form.direction!=='outbound'" class="queue-incoming"><strong>Números de entrada</strong><label>Adicionar número de entrada<select aria-label="Adicionar número de entrada" v-model="form.incoming_number"><option :value="null">Selecione um número</option><option v-for="n in catalog.queue_channels?.incoming_numbers||[]" :key="n" :value="n">{{n}}</option></select></label><p>Novos vínculos são salvos pausados. A ativação da rota na operadora é feita em Receptivo.</p><p v-for="n in form.incoming_numbers||[]" :key="n.id">{{n.number}} · {{n.enabled?'Rota ativa':'Rota pausada'}}</p><p v-if="!form.incoming_numbers?.length">Nenhum número de entrada vinculado.</p><a class="secondary" href="#/inbound">Configurar números de entrada</a></div></fieldset>
<fieldset v-if="form.direction!=='inbound'"><legend>Permissões dos atendentes</legend><div class="queue-permissions"><label class="check"><input type="checkbox" v-model="form.manual_enabled">Permitir discagem manual pelos atendentes</label><label class="check"><input type="checkbox" v-model="form.allow_landline">Permitir telefones fixos · qualquer DDD</label><label class="check"><input type="checkbox" v-model="form.allow_mobile">Permitir celulares</label></div><p>Os agentes herdam estas permissões. Pausar cadências mantém a discagem manual autorizada disponível.</p></fieldset>
<fieldset><legend>Atendentes desta fila</legend><div class="queue-team"><label v-for="u in catalog.agents" :key="u.id" class="check"><input type="checkbox" v-model="form.agent_ids" :value="u.id">{{u.name}}</label></div></fieldset>
<fieldset v-if="form.direction!=='inbound'"><legend>Cadências que usam esta fila</legend><p>O vínculo é definido na cadência, no cartão “Ligar para o cliente”.</p><a v-for="c in form.campaigns||[]" :key="c.id" class="queue-cadence-link" :href="'#/cadences/voice/'+c.id">{{c.name}} →</a><p v-if="!form.campaigns?.length">Nenhuma cadência vinculada.</p></fieldset>
<p>Pause as cadências e conclua os atendimentos antes de trocar canais ou vínculos.</p><div class="op-tabs"><button class="primary" :disabled="busy||!form.agent_ids.length">Salvar fila</button><button type="button" class="secondary" @click="form=null">Fechar</button></div></form>
 <div class="table-card op-box"><h3>Equipe agora</h3><table><thead><tr><th>Atendente</th><th>Disponibilidade</th></tr></thead><tbody><tr v-for="a in state?.team||[]" :key="a.id"><td>{{a.name}}</td><td>{{({available:'Disponível',paused:'Pausado',offline:'Offline'})[a.status]||'Offline'}}</td></tr></tbody></table></div>
 <label>Fila de atendimento<select v-model="selected" aria-label="Fila de atendimento"><option value="">Selecione</option><option v-for="q in state?.queues||[]" :key="q.id" :value="q.id">{{q.name}} · {{directions[q.direction]||'Entrada e saída'}}</option></select></label>
 <article v-if="queue" class="table-card op-box"><h3>{{queue.name}}</h3><p>{{directions[queue.direction]}} · {{queue.wrapup_seconds}} s de pós-atendimento</p><template v-if="queue.direction!=='inbound'"><h4>Saída · {{labels[queue.status]}}</h4><p>{{queue.mode==='progressive'?'Progressivo':'Preview'}} · {{queue.calling_method==='sip_trunk'?'SIP / Asterisk':'Twilio API'}}</p><ul><li v-for="c in queue.campaigns" :key="c.id">{{c.name}}</li></ul><p v-if="!queue.campaigns?.length">Sem campanhas vinculadas.</p><button class="secondary" :disabled="busy" @click="run(async()=>{await api('/operations/queues/'+queue.id+'/status','POST',{channel:'outbound',status:queue.status==='running'?'paused':'running'});await refresh()})">{{queue.status==='running'?'Pausar cadências':'Habilitar cadências'}}</button></template><template v-if="queue.direction!=='outbound'"><h4>Entrada · {{queue.inbound_enabled?'Habilitada':'Pausada'}}</h4><p v-for="n in queue.incoming_numbers" :key="n.id">{{n.number}} · rota {{n.enabled?'ativa':'pausada'}}</p><p v-if="!queue.incoming_numbers?.length">Nenhum número vinculado.</p><button class="secondary" :disabled="busy" @click="run(async()=>{await api('/operations/queues/'+queue.id+'/status','POST',{channel:'inbound',status:queue.inbound_enabled?'paused':'running'});await refresh()})">{{queue.inbound_enabled?'Pausar entrada':'Habilitar entrada'}}</button></template><div class="op-tabs"><button class="secondary" @click="edit(queue)">Editar fila e vínculos</button><span v-for="(n,s) in queue.counts" :key="s">{{labels[s]||s}}: {{n}}</span></div></article></template>
 <template v-else><MicrophoneCheck :disabled="armed||!!state?.current"/><div class="table-card op-box"><h3>Filas atribuídas a você</h3><p v-if="!state?.queues.length">Você ainda não pertence a uma fila. Solicite o vínculo ao administrador.</p><ul><li v-for="q in state?.queues" :key="q.id"><strong>{{q.name}}</strong> · {{directions[q.direction]||'Entrada e saída'}}<small v-if="q.direction!=='inbound'">Campanhas: {{q.campaigns?.map(c=>c.name).join(' · ')||'Nenhuma vinculada'}}</small><small v-if="q.direction!=='outbound'">Entrada {{q.inbound_enabled?'habilitada':'pausada'}} · {{inboundReady?'navegador conectado':'conecte o receptivo abaixo'}}</small></li></ul>
 <label v-if="outgoing.length">Fila para chamadas de saída<select v-model="selected" aria-label="Fila para chamadas de saída" :disabled="armed||!!state?.current" @change="pause();claimKey=null"><option value="">Somente receptivo / nenhuma fila de saída</option><option v-for="q in outgoing" :key="q.id" :value="q.id">{{q.name}} · {{labels[q.status]}}</option></select></label>
 <p v-if="queue">{{queue.mode==='progressive'?'Progressivo':'Preview'}} · {{method==='sip_trunk'?'SIP / Asterisk':'Twilio API'}} · definido pelo administrador</p><label class="check"><input type="checkbox" v-model="authorization" :disabled="armed">Estou pronto para atender chamadas reais das minhas filas.</label><div class="op-tabs"><button class="primary" :disabled="busy||!authorization||armed||!!state?.current||(!queue&&!inboundReady)" @click="run(online)">Ficar disponível</button><button class="secondary" :disabled="busy" @click="run(()=>presence('paused'))">Pausar atendimento</button><button class="secondary" :disabled="busy" @click="run(()=>presence('offline'))">Ficar offline</button></div><p role="status">{{state?.presence?.status==='available'?'Disponível':state?.presence?.status==='paused'?'Pausado':'Offline'}}{{armed?' · Progressivo ativo':''}}</p><p v-if="armed">{{state?.current?'Conclua a chamada e a tabulação.':queue?.status!=='running'?'Aguardando a supervisão habilitar a saída.':'Aguardando contato elegível. Nova consulta em até '+Math.max(countdown,5)+' segundos.'}}</p><button v-if="queue?.mode==='preview'" class="primary" :disabled="busy||!authorization||!!state?.current||queue.status!=='running'||state?.presence?.status!=='available'" @click="run(()=>claim())">Reservar próximo contato</button></div></template>
 <article v-if="view==='agent'&&state?.current" class="table-card op-box"><h3>Contato reservado: {{state.current.contact.name}}</h3><p>{{state.current.contact.phone}} · {{labels[state.current.status]}}</p><p>Fila: {{state.current.queue.name}} · Campanha: {{state.current.campaign?.name||'Campanha vinculada'}}</p><button v-if="!state.current.call_id" class="secondary" :disabled="busy" @click="run(async()=>{pause();await api('/operations/reservations/'+state.current.id+'/cancel','POST',{});await refresh()})">Devolver contato à fila</button><VoiceCallingPanel v-if="state.current.status!=='tabulation'" :key="state.current.id" ref="dialer" :reservation="state.current" :initial-method="state.current.queue.calling_method||method" compact @failed="run(failure)"/><VoiceDispositionForm v-else :key="state.current.call.id" :call="{...state.current.call,destination:state.current.contact.phone}" :codes="catalog.codes" @saved="run(refresh)" @cancel="pause"/></article>
 <p v-if="view==='agent'">Mantenha esta aba aberta. A disponibilidade é compartilhada entre entrada e saída. Pausar impede novas distribuições e permite concluir a ligação atual.</p>
 </section></template>
<style scoped>
.live-operation{min-width:0}.live-operation p{color:#727b65;line-height:1.65}.live-operation .op-box{padding:24px;margin:20px 0}.live-operation .op-box>h3{padding:0;margin:0 0 16px}.live-operation .op-tabs{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:18px 0}.live-operation label:not(.check){display:flex;flex-direction:column;gap:8px;margin:16px 0;font-size:13px;font-weight:600}.live-operation select{width:100%;max-width:100%;min-width:0;padding:12px;border:1px solid #dddccd;border-radius:10px;background:white}.live-operation .check{display:flex;gap:10px;align-items:center;font-size:13px;line-height:1.6;margin:18px 0}.live-operation .check input{width:auto;flex-shrink:0}.live-operation small{display:block;color:#727b65;font-size:12px;margin:6px 0}.live-operation li{margin:12px 0}.live-operation fieldset{border:0;padding:0}.live-operation .op-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:16px}.live-operation button:disabled{opacity:.55}.live-operation .error{color:#9e302d}@media(max-width:650px){.live-operation .op-box{padding:16px}.live-operation .op-tabs{gap:8px}}
.queue-config{max-width:1200px}.queue-config fieldset{border-top:1px solid #e8eadf;padding:20px 0 8px;margin:16px 0}.queue-config legend{font-weight:700;font-size:14px;padding:0 8px 0 0}.queue-config .queue-form-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px 20px}.queue-config .queue-permissions,.queue-config .queue-team{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 20px}.queue-config .check{margin:10px 0}.queue-config p{font-size:12px}.queue-config .queue-cadence-link{display:block;margin:10px 0;color:#956f21;font-size:13px}.queue-incoming{margin-top:18px}.queue-incoming strong{font-size:12px}@media(max-width:1000px){.queue-config .queue-form-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:620px){.queue-config .queue-form-grid,.queue-config .queue-permissions,.queue-config .queue-team{grid-template-columns:1fr}}
</style>
