<script setup>
import {ref,computed,watch} from 'vue'
const props=defineProps({senders:Array,contacts:Array,templates:Array,campaigns:Array})
const emit=defineEmits(['changed'])
const fresh=()=>({sender_id:'',contact_id:'',campaign_id:null,qr_template_id:null,experimental_confirmed:false,body:'',consent_evidence:'',consent_confirmed:false,idempotency_key:crypto.randomUUID()})
const form=ref(fresh()),busy=ref(false),locked=ref(false),error=ref(''),receipt=ref(null),preview=ref(null)
const template=computed(()=>props.templates?.find(t=>t.id===form.value.qr_template_id))
watch(()=>[form.value.qr_template_id,form.value.contact_id,form.value.campaign_id],()=>{preview.value=null;form.value.experimental_confirmed=false})
async function api(path,body){const r=await fetch('/api/voice/whatsapp/qr/'+path,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.errors?Object.values(d.errors).flat().join(' · '):d.message||'Não foi possível concluir.');return d}
async function showPreview(){busy.value=true;error.value='';try{preview.value=await api('preview',{qr_template_id:form.value.qr_template_id,contact_id:form.value.contact_id,campaign_id:form.value.campaign_id})}catch(e){error.value=e.message}finally{busy.value=false}}
async function send(){busy.value=true;error.value='';locked.value=true;try{receipt.value=await api('messages',{...form.value,body:form.value.qr_template_id?null:form.value.body});emit('changed')}catch(e){error.value=e.message}finally{busy.value=false}}
function reset(){form.value=fresh();locked.value=false;receipt.value=null;error.value='';preview.value=null}
</script>
<template>
 <form class="table-card qr-test" @submit.prevent="send"><h3>Mensagem pelo número conectado por QR</h3><p>Envio real para um contato autorizado. Confira a prévia quando usar botões experimentais.</p>
 <p v-if="!senders.some(s=>s.provider==='qr'&&s.status==='ONLINE')" class="qr-help">Conecte um número na área Números conectados para liberar este teste.</p><p v-if="!contacts.some(c=>c.consent&&!c.suppressed_at&&!c.replied_at)" class="qr-help">Não há contatos elegíveis para este teste. Quem respondeu ou pediu para sair não aparece na seleção.</p><fieldset :disabled="busy||locked">
  <label>Remetente QR<select aria-label="Remetente QR" v-model="form.sender_id" required><option value="">Selecione</option><option v-for="s in senders.filter(s=>s.provider==='qr')" :key="s.id" :value="s.id" :disabled="s.status!=='ONLINE'">{{s.label}} · {{s.number}}{{s.status!=='ONLINE'?' · Desconectado':''}}</option></select></label>
  <label>Contato do teste QR<select aria-label="Contato do teste QR" v-model="form.contact_id" required><option value="">Selecione</option><option v-for="c in contacts.filter(c=>c.consent&&!c.suppressed_at&&!c.replied_at)" :key="c.id" :value="c.id">{{c.name}} · {{c.phone}}</option></select></label>
  <label>Campanha do teste QR · opcional<select aria-label="Campanha do teste QR" v-model="form.campaign_id"><option :value="null">Sem campanha</option><option v-for="c in campaigns" :key="c.id" :value="c.id">{{c.name}}</option></select></label>
  <label>Template QR do teste<select aria-label="Template QR do teste" v-model="form.qr_template_id"><option :value="null">Texto livre sem botões</option><option v-for="t in templates" :key="t.id" :value="t.id">{{t.name}} · experimental</option></select></label>
  <template v-if="template"><p class="qr-body">{{template.body}}</p><button type="button" class="secondary" :disabled="!form.contact_id" @click="showPreview">Conferir prévia personalizada</button><div v-if="preview" class="qr-preview"><p class="qr-body">{{preview.body}}</p><span v-for="b in preview.buttons" :key="b.id">{{b.label}}</span></div><label><input type="checkbox" v-model="form.experimental_confirmed" required>Confirmo o teste de botões experimentais por QR Code.</label></template>
  <label v-else>Texto do teste QR<textarea v-model="form.body" required maxlength="4000" rows="3"/></label>
  <label>Evidência de autorização QR<textarea v-model="form.consent_evidence" required minlength="8" maxlength="1000" rows="2"/></label>
  <label><input type="checkbox" v-model="form.consent_confirmed" required>Confirmo a autorização do destinatário para este teste.</label>
 </fieldset>
 <button v-if="!locked" class="primary" :disabled="busy||!senders.some(s=>s.provider==='qr'&&s.status==='ONLINE')||!contacts.some(c=>c.consent&&!c.suppressed_at&&!c.replied_at)">Enviar teste real por QR</button><button v-else-if="!receipt" type="button" class="secondary" :disabled="busy" @click="send">Consultar ou retomar a mesma tentativa QR</button><button v-if="locked" type="button" class="secondary" :disabled="busy" @click="reset">Preparar outro teste QR</button>
 <p v-if="receipt">Estado: {{receipt.status}}. Consulte o histórico. “Enviada” não confirma entrega nem exibição dos botões.</p><p v-if="error" role="alert" class="error">{{error}}</p><p v-if="locked">Se o envio estiver sem confirmação, consulte o histórico antes de preparar outro. Não há reenvio automático em texto.</p>
 </form>
</template>
<style scoped>.qr-test{padding:26px;margin-bottom:22px;border:1px solid #dfe3d8;border-radius:17px}.qr-test h3{font-size:18px;margin:0 0 12px}.qr-help{padding:12px 15px;background:#f6f0e2;border-radius:9px;color:#8b682b}.qr-test button:focus-visible{outline:3px solid #be9134;outline-offset:3px}.qr-test textarea{min-width:0;max-width:100%}.qr-test input[type=checkbox]{width:auto;accent-color:#bd8e2e}.qr-test fieldset:disabled{opacity:.6}.qr-test fieldset{border:0;padding:0;min-width:0}.qr-test label{display:flex;gap:8px;margin:14px 0;flex-wrap:wrap;font-size:13px}.qr-test label:has(input[type=checkbox]){flex-direction:row;align-items:flex-start}.qr-test label:has(select),.qr-test label:has(textarea){flex-direction:column}.qr-test select{padding:11px;border:1px solid #daddd0;border-radius:8px;width:100%;min-width:0}.qr-test p{font-size:12px;line-height:1.6}.qr-test button{margin-right:8px}.qr-body{white-space:pre-wrap}.qr-preview{background:#f7f8f3;padding:15px;border-radius:10px}.qr-preview span{display:inline-block;padding:8px;border:1px solid #d6c59a;border-radius:8px;margin:5px;font-size:12px}</style>
