<script setup>
import {ref,shallowRef,watch,onMounted,onBeforeUnmount} from 'vue'
import {Building2,UserRound,CheckCircle2,ArrowRight,RefreshCw} from 'lucide-vue-next'
import {signupEvent,loadMetaSdk} from '../whatsapp-signup.mjs'
const props=defineProps({sender:{type:Object,required:true}}),emit=defineEmits(['changed'])
const state=ref(null),mode=ref('own'),busy=ref(false),error=ref(''),notice=ref(''),readiness=ref(null),code=ref(''),confirmed=ref(false),displayName=ref(''),method=ref('sms'),settings=ref({}),canEdit=ref(false),session=ref(null),meta=shallowRef(null),authorizing=ref(false),authorization=ref(null)
const statusLabels={PENDING_VERIFICATION:'aguardando o código',VERIFYING:'validando o código',CREATING:'preparando o cadastro',TWILIO_REVIEW:'em análise pela Twilio',OFFLINE:'aguardando ativação',DRAFT:'cadastro em rascunho',STUBBED:'cadastro em preparação','ONLINE:UPDATING':'atualizando a conexão',UNKNOWN:'sem confirmação'}
let expiresTimer
async function api(path,method='GET',body){const r=await fetch('/api/voice/whatsapp'+path,{method,headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.errors?Object.values(d.errors).flat().join(' · '):d.message||'Não foi possível concluir.');return d}
const path=()=>'/senders/'+props.sender.id+'/onboarding'
async function refresh(){state.value=await api(path())}
async function run(fn){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await fn()}catch(e){error.value=e.message}finally{busy.value=false}}
async function discover(){await run(async()=>{readiness.value=await api(path()+'/discover','POST',{});await refresh();if(readiness.value.found){notice.value='Número encontrado e vinculado. Confira o estado da conexão.';emit('changed')}else notice.value=readiness.value.message})}
async function register(waba){await run(async()=>{state.value=await api(path()+'/register','POST',{mode:mode.value,display_name:displayName.value,verification_method:method.value,confirmed:confirmed.value,...(waba?{waba_id:waba,session_id:session.value.session_id}:{})});authorization.value=null;authorizing.value=false;clearTimeout(expiresTimer);emit('changed')})}
async function verify(){await run(async()=>{const value=code.value;code.value='';state.value=await api(path()+'/verify','POST',{code:value});notice.value='Código enviado para confirmação. Consulte a conexão em alguns instantes.';emit('changed')})}
async function saveSettings(){await run(async()=>{const r=await api('/onboarding/settings','PUT',settings.value);settings.value=r.settings;session.value=null;meta.value=null;notice.value='Configuração salva. A autorização e a liberação serão confirmadas pelos provedores durante o cadastro.'})}
async function prepareMeta(){await run(async()=>{session.value=await api(path()+'/embedded','POST',{});meta.value=await loadMetaSdk(session.value.settings);notice.value='Tudo pronto para abrir a janela de autorização.'})}
function openMeta(){if(!meta.value||!session.value)return;error.value='';authorizing.value=true;authorization.value=null;clearTimeout(expiresTimer);expiresTimer=setTimeout(()=>{authorizing.value=false;error.value='A sessão expirou. Prepare uma nova conexão para continuar.';session.value=null;meta.value=null},20*60*1000)
try{meta.value.login(()=>{}, {config_id:session.value.settings.config_id,auth_type:'rerequest',response_type:'code',override_default_response_type:true,extras:{setup:{solutionID:session.value.settings.solution_id}}})}catch{authorizing.value=false;error.value='Não foi possível abrir a Meta. Verifique se o navegador bloqueou a janela.'}}
function cancelMeta(){authorizing.value=false;meta.value=null;session.value=null;clearTimeout(expiresTimer)}
function receive(event){const result=signupEvent(event,authorizing.value);if(!result)return;authorizing.value=false;clearTimeout(expiresTimer);if(result.event==='FINISH'){authorization.value=result;notice.value='Autorização recebida. Conclua a conexão para validar o vínculo na Twilio.'}else{error.value=result.event==='CANCEL'?'Cadastro cancelado na Meta. Você pode tentar novamente.':'A Meta não concluiu o cadastro. Confira as permissões da empresa e tente novamente.';session.value=null;meta.value=null}}
watch(()=>[props.sender.provider_sid,props.sender.status],()=>{if(state.value)state.value.sender={...props.sender}})
onMounted(()=>{window.addEventListener('message',receive);run(async()=>{const r=await api('/onboarding/settings');settings.value=r.settings;canEdit.value=r.can_edit;await refresh()})})
onBeforeUnmount(()=>{window.removeEventListener('message',receive);clearTimeout(expiresTimer);code.value=''})
</script>
<template>
 <section class="onboarding" aria-label="Conectar WhatsApp oficial" :aria-busy="busy">
  <div v-if="error" class="error" role="alert">{{error}}</div><p v-if="notice" class="feedback" role="status">{{notice}}</p>
  <template v-if="state">
   <div v-if="state.sender.provider_sid" class="connected-state"><CheckCircle2 :size="24"/><div><strong>{{state.sender.status==='ONLINE'?'Número conectado':'Cadastro localizado'}}</strong><p>{{state.sender.status==='ONLINE'?'Você já pode preparar os templates deste número.':'A Twilio ainda precisa confirmar a ativação: '+(statusLabels[state.sender.status]||'aguardando confirmação')}}</p></div></div>
   <template v-else>
    <h4>Como deseja conectar este número?</h4>
    <div class="choices"><button :disabled="busy||authorizing||!!authorization" :aria-pressed="mode==='own'" :class="{selected:mode==='own'}" @click="mode='own'"><Building2 :size="22"/><strong>Minha empresa</strong><span>Números da própria empresa, na conta Twilio configurada.</span></button><button :disabled="busy||authorizing||!!authorization" :aria-pressed="mode==='embedded'" :class="{selected:mode==='embedded'}" @click="mode='embedded'"><UserRound :size="22"/><strong>Empresa cliente</strong><span>Autorização oficial pela Meta e subconta dedicada.</span></button></div>
    <div v-if="mode==='own'" class="step"><strong>1. Confira a conta e o número</strong><p>No primeiro cadastro, a Twilio abre a autorização da Meta pelo seu console. Depois, os números adicionais podem ser cadastrados aqui.</p><a href="https://www.twilio.com/console/sms/whatsapp/senders" target="_blank" rel="noopener">Cadastrar primeiro número na Twilio ↗</a></div>
    <div v-else class="step"><strong>1. Autorize a empresa na Meta</strong><p>Selecione a conta empresarial e confirme o número {{sender.number}} na janela oficial. A conta Twilio deste workspace deve ser uma subconta exclusiva dessa empresa.</p><p v-if="!settings.enabled" class="pending">Aguardando habilitação do Tech Provider pelo administrador.</p><template v-else><button v-if="!meta" class="secondary" :disabled="busy" @click="prepareMeta">Preparar conexão com Meta</button><button v-else class="meta-button" :disabled="busy||authorizing||!!authorization" @click="openMeta">{{authorizing?'Conclua na janela da Meta…':'Continuar com Facebook'}}</button><button v-if="authorizing" class="secondary" @click="cancelMeta">Cancelar espera</button></template><p v-if="sender.ownership==='twilio'" class="pending">Para o primeiro número Twilio, obtenha o código nos registros de SMS da subconta. O acesso aos códigos pode exigir liberação da Twilio.</p></div>
    <div v-if="mode==='own'&&readiness?.can_register||mode==='embedded'&&authorization" class="step"><strong>2. Cadastre o perfil</strong><label>Nome de exibição da empresa<input v-model="displayName" maxlength="100" placeholder="Ex.: Zyrex" :disabled="busy"></label><label v-if="mode==='own'">Receber código por<select v-model="method" :disabled="busy"><option value="sms">SMS</option><option value="voice">Ligação de verificação</option></select></label><p v-if="mode==='own'&&sender.ownership==='twilio'">Números Twilio compatíveis com SMS podem ser verificados automaticamente.</p><label class="confirmation"><input type="checkbox" v-model="confirmed" :disabled="busy">Tenho autorização para conectar este número e iniciar sua verificação.</label><p>Se o número já usa WhatsApp, confira a migração com o provedor antes de prosseguir.</p><button class="primary" :disabled="busy||!confirmed||displayName.trim().length<2||['creating','unknown','pending','online'].includes(state.onboarding?.state)" @click="register(authorization?.waba_id)">Concluir conexão <ArrowRight :size="15"/></button></div>
   </template>
   <p v-if="['creating','unknown'].includes(state.onboarding?.state)" class="pending">O cadastro foi solicitado, mas ainda não há confirmação. Busque o número na Twilio para recuperá-lo. Não será feita outra criação automática.</p><p v-if="state.onboarding?.state==='rejected'" class="error">A Twilio recusou o cadastro. Confira a habilitação da conta, o nome e a situação do número antes de tentar novamente.</p>
   <div class="actions"><button class="secondary" :disabled="busy||authorizing" @click="discover"><RefreshCw :size="15"/>{{state.sender.provider_sid?'Consultar conexão':'Buscar número na Twilio'}}</button></div>
   <form v-if="state.sender.provider_sid&&state.sender.status!=='ONLINE'&&state.onboarding" class="step" @submit.prevent="verify"><strong>Confirme a posse do número</strong><p>Se recebeu um código, informe abaixo. Aguarde pelo menos um minuto entre confirmações.</p><label>Código recebido<input v-model="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required placeholder="6 dígitos"></label><button class="primary" :disabled="busy||code.length!==6">Confirmar código</button></form>
   <details v-if="state.sender.provider_sid" class="step"><summary>Recebimento de mensagens</summary><p>O cadastro feito aqui já configura o recebimento. Se o número veio do console, este botão direciona as novas mensagens para o MA.</p><button class="secondary" :disabled="busy" @click="run(async()=>{state=await api(path()+'/webhook','POST',{confirmed:true});notice='Recebimento direcionado ao MA.'})">Direcionar recebimento para o MA</button></details>
  </template>
  <details class="step" v-if="canEdit"><summary>Configuração da plataforma · Tech Provider</summary><p>Preencha após a aprovação do aplicativo Meta e do vínculo com a Twilio. Esta configuração não troca as credenciais nem os números atuais.</p><form @submit.prevent="saveSettings"><label>Meta App ID<input v-model="settings.app_id" inputmode="numeric" pattern="[0-9]{5,40}" :required="settings.enabled"></label><label>Configuration ID · Embedded Signup v4<input v-model="settings.config_id" inputmode="numeric" pattern="[0-9]{5,40}" :required="settings.enabled"></label><label>Partner Solution ID<input v-model="settings.solution_id" inputmode="numeric" pattern="[0-9]{5,40}" :required="settings.enabled"></label><label>Versão Graph API do aplicativo<input v-model="settings.graph_version" pattern="v[0-9]{2}\.0" placeholder="Versão habilitada no painel Meta" :required="settings.enabled"></label><label class="confirmation"><input type="checkbox" v-model="settings.enabled">Aplicativo e parceria habilitados; liberar cadastro de clientes</label><button class="secondary" :disabled="busy">Salvar configuração da plataforma</button></form><a href="https://www.twilio.com/docs/whatsapp/isv/tech-provider-program/integration-guide" target="_blank" rel="noopener">Ver requisitos e configuração oficial ↗</a></details>
 </section>
</template>
<style scoped>
.onboarding{font-size:13px;line-height:1.65}.onboarding h4{margin:8px 0 16px}.choices{display:grid;grid-template-columns:1fr 1fr;gap:12px}.choices button{display:flex;flex-direction:column;align-items:flex-start;gap:10px;background:white;border:1px solid #dce1d5;border-radius:14px;padding:18px;text-align:left;color:#46513a;font:inherit;cursor:pointer}.choices button.selected{border-color:#c79938;background:#fbf6e9}.choices span{font-size:12px;color:#747f68}.step{margin:20px 0;padding-top:18px;border-top:1px solid #e3e6db}.step p{color:#78816e;font-size:12px;margin:8px 0 14px}.onboarding label{display:flex;flex-direction:column;gap:6px;margin:15px 0;font-size:12px;font-weight:600}.onboarding input,.onboarding select{border:1px solid #d7ddce;border-radius:9px;padding:12px;font:inherit;min-width:0;width:100%;box-sizing:border-box}.onboarding label.confirmation{flex-direction:row;align-items:flex-start;font-weight:400}.confirmation input{width:auto;margin:4px 0}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.feedback{padding:13px 16px;background:#edf5e9;color:#476437;border-radius:10px}.pending{background:#faf2de;padding:12px;border-radius:10px;color:#8f691f!important}.connected-state{display:flex;align-items:flex-start;gap:12px;color:#367358}.connected-state p{color:#78816e}.meta-button{border:0;border-radius:8px;background:#1877f2;color:white;font:inherit;padding:13px 22px;cursor:pointer}summary{cursor:pointer;font-size:12px;font-weight:600}.onboarding button:disabled{opacity:.5;cursor:not-allowed}@media(max-width:650px){.choices{grid-template-columns:1fr}}
</style>
