<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Zyrex · Cliente de referência</title><style>body{font:15px system-ui;background:#f7f6f0;color:#293026;max-width:1100px;margin:30px auto;padding:20px}select,button{padding:12px;margin:5px;border:1px solid #d8dacb;border-radius:8px}button{background:#c69a3c}iframe{width:100%;height:850px;border:1px solid #d8dacb;border-radius:16px}code{word-break:break-all}#status{padding:15px}</style></head><body><h1>Cliente de referência · discador no CRM</h1><p>Este exemplo roda no MA e exige login de administrador. Crie uma integração com escopo <code>voice:embed</code>, origem <code id="origin"></code> e atendentes permitidos. O CRM real não é alterado.</p><label>Integração <select id="integration"></select></label><label>Atendente <select id="agent"></select></label><button id="start">Abrir / renovar sessão</button><p id="status">Carregando configurações…</p><iframe id="dialer" title="Discador Zyrex" allow="microphone"></iframe><script>
const $=id=>document.getElementById(id);$('origin').textContent=location.origin;let data,session;
async function api(path,method='GET',body){const r=await fetch('/api/voice/integrations'+path,{method,headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.message||'Falha');return d}
function agents(){const i=data.integrations.find(v=>v.id===$('integration').value);$('agent').replaceChildren(...data.agents.filter(a=>JSON.parse(i?.agent_ids||'[]').includes(a.id)).map(a=>new Option(a.name,a.id)))}
api('').then(d=>{data=d;$('integration').replaceChildren(...d.integrations.filter(i=>i.active&&i.embed_origin===location.origin&&JSON.parse(i.scopes).includes('voice:embed')).map(i=>new Option(i.name,i.id)));agents();$('status').textContent='Selecione a integração e o atendente. Abrir a sessão não inicia uma chamada.'}).catch(e=>$('status').textContent=e.message);
$('integration').onchange=agents;
$('start').onclick=async()=>{try{session=await api('/'+$('integration').value+'/reference-session','POST',{user_id:Number($('agent').value)});const frame=$('dialer');if(frame.src===session.iframe_url)frame.contentWindow.postMessage({type:'zyrex.session',access_token:session.access_token},location.origin);else frame.src=session.iframe_url;$('status').textContent='Sessão emitida por 10 minutos. Use os controles do atendente para conectar o áudio.'}catch(e){$('status').textContent=e.message}};
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('dialer').contentWindow)return;if(e.data?.type==='zyrex.ready'&&session)e.source.postMessage({type:'zyrex.session',access_token:session.access_token},location.origin);if(e.data?.type==='zyrex.session-expiring')$('status').textContent='Renove a sessão pelo botão acima.'});
</script></body></html>
