<?php
/** Isolated PostgreSQL contention experiment. Refuses any non-QA database. */
require __DIR__.'/../vendor/autoload.php';$app=require __DIR__.'/../bootstrap/app.php';$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
use Illuminate\Support\Facades\{DB,Artisan,Http};
use App\Services\InboundVoice;
if(!app()->environment('testing')||config('database.default')!=='pgsql'||config('database.connections.pgsql.database')!=='milestones_qa')throw new RuntimeException('Isolated QA database required');
Http::preventStrayRequests();
if(($argv[1]??'')==='worker'){
 $start=microtime(true);$xml=app(InboundVoice::class)->receive(['AccountSid'=>'AC'.str_repeat('a',32),'CallSid'=>'CA'.str_pad($argv[2],32,'0',STR_PAD_LEFT),'From'=>'+5511999990000','To'=>'+16890000000']);echo json_encode(['ms'=>round((microtime(true)-$start)*1000,2),'dial'=>str_contains($xml,'<Dial'),'rejected'=>str_contains($xml,'<Reject')]);exit;
}
Artisan::call('migrate:fresh',['--force'=>true]);$u=App\Models\User::factory()->create(['voice_workspace_id'=>1,'voice_role'=>'agent']);$campaign=DB::table('voice_campaigns')->insertGetId(['workspace_id'=>1,'name'=>'Load QA','settings'=>'{}']);$queue=DB::table('voice_live_queues')->insertGetId(['workspace_id'=>1,'campaign_id'=>$campaign,'name'=>'Load QA','agent_ids'=>json_encode([$u->id])]);DB::table('voice_inbound_routes')->insert(['workspace_id'=>1,'queue_id'=>$queue,'number'=>'+16890000000','enabled'=>true]);DB::table('voice_agent_presence')->insert(['user_id'=>$u->id,'workspace_id'=>1,'status'=>'available','last_seen_at'=>now()]);DB::table('voice_inbound_devices')->insert(['user_id'=>$u->id,'workspace_id'=>1,'session_id'=>(string)Illuminate\Support\Str::uuid(),'identity'=>'load_agent','ready'=>true,'last_seen_at'=>now()]);
$results=[];$parallel=4;$total=40;$wall=microtime(true);
for($batch=0;$batch<$total/$parallel;$batch++){$jobs=[];for($n=0;$n<$parallel;$n++){$pipes=[];$p=proc_open([PHP_BINARY,__FILE__,'worker',(string)($batch*$parallel+$n+1)],[1=>['pipe','w'],2=>['pipe','w']],$pipes);$jobs[]=[$p,$pipes];}foreach($jobs as [$p,$pipes]){$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);if(proc_close($p)!==0)throw new RuntimeException($err);$v=json_decode($out,true,flags:JSON_THROW_ON_ERROR);$results[]=$v;}}
$accepted=count(array_filter($results,fn($v)=>$v['dial']));$rejected=count(array_filter($results,fn($v)=>$v['rejected']));if($accepted!==1||$rejected!==39||DB::table('voice_inbound_calls')->count()!==1||DB::table('voice_inbound_offers')->count()!==1)throw new RuntimeException('Capacity invariant failed');
$ms=array_column($results,'ms');sort($ms);$report=['mode'=>'isolated PostgreSQL admission contention, no media or provider calls','requests'=>$total,'parallel_workers'=>$parallel,'accepted'=>$accepted,'capacity_rejections'=>$rejected,'duplicate_reservations'=>0,'p50_ms'=>$ms[(int)floor(($total-1)*.5)],'p95_ms'=>$ms[(int)floor(($total-1)*.95)],'max_ms'=>max($ms),'wall_seconds'=>round(microtime(true)-$wall,2),'runtime_container_cpus'=>1,'runtime_container_memory_mb'=>512,'production_capacity_unchanged'=>true];echo json_encode($report,JSON_PRETTY_PRINT).PHP_EOL;
